import { useEffect,useRef } from 'react'
import { BAT_QUALITY_COUNTS,BAT_SCENE_DURATION,BAT_WING_FRAME_PATHS,getBatQuality,getBatWingFrame,sampleTargetPixels } from './batSwarmConfig'

type Particle={x:number;y:number;vx:number;vy:number;depth:number;scale:number;rotation:number;rotationOffset:number;wingPhase:number;wingSpeed:number;wingSpan:number;bodyScale:number;aspectRatio:number;spawnAt:number;targeted:boolean;targetIndex:number;opacity:number;wanderSeed:number;arrival:number}

const MASK_SOURCE='/brand/sphex-symbol-mask.png'
const clamp=(value:number,min:number,max:number)=>Math.max(min,Math.min(max,value))
const smooth=(from:number,to:number,value:number)=>{const x=clamp((value-from)/(to-from),0,1);return x*x*(3-2*x)}
function seededRandom(seed=0x5f3759df){return()=>{seed=Math.imul(seed^seed>>>15,1|seed);seed^=seed+Math.imul(seed^seed>>>7,61|seed);return((seed^seed>>>14)>>>0)/4294967296}}

function makeParticles(count:number,width:number,height:number,random:()=>number):Particle[]{return Array.from({length:count},(_,index)=>{
 const layer=index<count*.3?0:index<count*.9?1:2,depth=layer===0?.42+random()*.2:layer===1?.85+random()*.35:1.55+random()*.42
 const edge=index%5,margin=width*(layer===2?.22:.12),x=edge===0?-margin:edge===1?width+margin:edge===4?width*(.38+random()*.24):random()*width
 const y=edge===2?height+margin:edge===3?height*(.8+random()*.25):edge===4?height*(.4+random()*.2):height*(.05+random()*.76)
 const centerAngle=Math.atan2(height*.47-y,width*.5-x),arcBias=(random()-.5)*1.55,speed=(layer===0?.025:layer===1?.046:.078)*(1+random()*.8)
 return{x,y,vx:Math.cos(centerAngle+arcBias)*speed,vy:Math.sin(centerAngle+arcBias)*speed,depth,scale:(.115+random()*.065)*depth,rotation:centerAngle,rotationOffset:(random()-.5)*.22,wingPhase:random()*4,wingSpeed:.0075+random()*.0065,wingSpan:.88+random()*.25,bodyScale:.86+random()*.25,aspectRatio:.86+random()*.22,spawnAt:250+random()*650,targeted:index<count*.82,targetIndex:index,opacity:0,wanderSeed:random()*Math.PI*2,arrival:.92+random()*.075}
})}

function sampleMask(image:HTMLImageElement,count:number,random:()=>number){const canvas=document.createElement('canvas');canvas.width=210;canvas.height=300;const context=canvas.getContext('2d',{willReadFrequently:true});if(!context)return[] as Array<[number,number]>;const ratio=Math.min(178/image.width,266/image.height),width=image.width*ratio,height=image.height*ratio;context.clearRect(0,0,canvas.width,canvas.height);context.drawImage(image,(canvas.width-width)/2,(canvas.height-height)/2,width,height);return sampleTargetPixels(context.getImageData(0,0,canvas.width,canvas.height).data,canvas.width,canvas.height,count,random)}

function assignNearestTargets(points:Array<[number,number]>,particles:Particle[],width:number,height:number){const available=[...points],assigned:Array<[number,number]>=[],markWidth=clamp(width*.39,138,202),markHeight=markWidth*1.45;for(const particle of particles.filter(item=>item.targeted)){let nearest=0,distance=Infinity;for(let index=0;index<available.length;index++){const [px,py]=available[index],dx=particle.x-(width*.5+px*markWidth),dy=particle.y-(height*.46+py*markHeight),next=dx*dx+dy*dy;if(next<distance){distance=next;nearest=index}}const target=available.splice(nearest,1)[0];if(!target)break;assigned[particle.targetIndex]=target}return assigned}

function makeBatFrames(){if(typeof Path2D==='undefined')return null;return BAT_WING_FRAME_PATHS.map(path=>new Path2D(path))}

function drawBat(context:CanvasRenderingContext2D,frames:Path2D[],particle:Particle,formation:number){const frame=frames[getBatWingFrame(particle.wingPhase)],size=particle.scale;context.save();context.translate(particle.x,particle.y);context.rotate(particle.rotation+particle.rotationOffset);context.scale(size*particle.wingSpan,size*particle.aspectRatio*particle.bodyScale);context.globalAlpha=particle.opacity;context.fillStyle='#fff';context.filter=particle.depth<.5||particle.depth>1.75?'blur(.55px)':'none';context.fill(frame);if(formation>.78&&particle.targeted){context.globalAlpha*=smooth(.78,.94,formation)*.18;context.filter='none';context.fill(frame)}context.restore()}

export function BatSwarmScene({reducedMotion=false,onFailure}:{reducedMotion?:boolean;onFailure?:()=>void}){const canvasRef=useRef<HTMLCanvasElement>(null);useEffect(()=>{
 if(reducedMotion)return
 const canvas=canvasRef.current,context=canvas?.getContext('2d'),frames=makeBatFrames();if(!canvas||!context||!frames){onFailure?.();return}
 let disposed=false,frame=0,width=0,height=0,dpr=1,particles:Particle[]=[],targets:Array<[number,number]>=[];const random=seededRandom(),cores=navigator.hardwareConcurrency||4
 const resize=()=>{const previousWidth=width,previousHeight=height;width=window.innerWidth;height=window.innerHeight;const quality=getBatQuality({width,dpr:window.devicePixelRatio||1,cores});dpr=Math.min(window.devicePixelRatio||1,quality==='high'&&width>900?2:1.5);canvas.width=Math.round(width*dpr);canvas.height=Math.round(height*dpr);canvas.style.width=`${width}px`;canvas.style.height=`${height}px`;context.setTransform(dpr,0,0,dpr,0,0);if(!particles.length)particles=makeParticles(BAT_QUALITY_COUNTS[quality],width,height,random);else if(previousWidth&&previousHeight)for(const particle of particles){particle.x*=width/previousWidth;particle.y*=height/previousHeight}}
 resize();window.addEventListener('resize',resize,{passive:true});const image=new Image();image.onload=()=>{if(!disposed)targets=assignNearestTargets(sampleMask(image,Math.ceil(particles.length*.82),random),particles,width,height)};image.onerror=()=>onFailure?.();image.src=MASK_SOURCE
 const started=performance.now();let previousFrame=started
 const render=(now:number)=>{if(disposed)return;const elapsed=now-started,dt=clamp(now-previousFrame,8,34),progress=clamp(elapsed/BAT_SCENE_DURATION,0,1),convergence=smooth(.5,.78,progress),lock=smooth(.72,.94,progress),formation=smooth(.55,.93,progress);previousFrame=now;context.setTransform(dpr,0,0,dpr,0,0);context.clearRect(0,0,width,height);const markWidth=clamp(width*.39,138,202),markHeight=markWidth*1.45,centerX=width*.5,centerY=height*.46
  for(let index=0;index<particles.length;index++){const particle=particles[index];if(elapsed<particle.spawnAt)continue;const phaseNoise=elapsed*.00115+particle.wanderSeed,wander=(1-convergence)*(.0014+particle.depth*.0005);particle.vx+=Math.cos(phaseNoise*1.13)*wander*dt;particle.vy+=Math.sin(phaseNoise*.87)*wander*dt
   if(particle.targeted&&targets[particle.targetIndex]){const [px,py]=targets[particle.targetIndex],tx=centerX+px*markWidth,ty=centerY+py*markHeight,dx=tx-particle.x,dy=ty-particle.y,distance=Math.hypot(dx,dy)||1,tangent=(1-lock)*convergence*.0016,curve=particle.targetIndex%2?-1:1;particle.vx+=(-dy/distance)*tangent*curve*dt;particle.vy+=(dx/distance)*tangent*curve*dt;const pull=(.000008+convergence*.000075+lock*.00019)*dt;particle.vx+=dx*pull;particle.vy+=dy*pull;const damping=Math.pow(.994-convergence*.018-lock*.025,dt/16);particle.vx*=damping;particle.vy*=damping;if(lock>.35){const settle=(.015+lock*.095)*particle.arrival;particle.x+=dx*settle;particle.y+=dy*settle}}
   else{const orbit=Math.atan2(particle.y-centerY,particle.x-centerX)+Math.PI/2;particle.vx+=Math.cos(orbit)*(1-convergence)*.00042*dt;particle.vy+=Math.sin(orbit)*(1-convergence)*.00042*dt}
   const neighbor=particles[index?index-1:particles.length-1],rx=particle.x-neighbor.x,ry=particle.y-neighbor.y,distanceSquared=rx*rx+ry*ry;if(distanceSquared>1&&distanceSquared<900){const repel=(1-lock)*.03/distanceSquared;particle.vx+=rx*repel;particle.vy+=ry*repel}particle.x+=particle.vx*dt;particle.y+=particle.vy*dt;particle.rotation=Math.atan2(particle.vy,particle.vx)+Math.sin(phaseNoise*2.1)*.13*(1-lock);particle.wingPhase+=dt*particle.wingSpeed*(1-lock*.72)
   const enter=smooth(particle.spawnAt,particle.spawnAt+180,elapsed),freeExit=1-smooth(.72,.94,progress),targetDissolve=1-smooth(.82,.98,progress),depthAlpha=particle.depth<.68?.32:particle.depth>1.5?.96:.66;particle.opacity=enter*depthAlpha*(particle.targeted?targetDissolve:freeExit);drawBat(context,frames,particle,formation)}context.filter='none';if(elapsed<BAT_SCENE_DURATION+80)frame=requestAnimationFrame(render)}
 frame=requestAnimationFrame(render);return()=>{disposed=true;cancelAnimationFrame(frame);window.removeEventListener('resize',resize);image.onload=null;image.onerror=null;context.clearRect(0,0,width,height)}
 },[onFailure,reducedMotion]);return <canvas className="app-boot-swarm" ref={canvasRef} aria-hidden="true"/>}
