import { act,render,screen } from '@testing-library/react'
import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { afterEach,beforeEach,describe,expect,it,vi } from 'vitest'
import { AUTH_ENTRANCE_TIMING,AuthEntranceExperience } from '../components/app-boot/AuthEntranceExperience'
import { BatSwarmScene } from '../components/app-boot/BatSwarmScene'
import { BAT_QUALITY_COUNTS,BAT_SCENE_DURATION,BAT_WING_FRAME_PATHS,getBatQuality,getBatWingFrame,sampleTargetPixels } from '../components/app-boot/batSwarmConfig'
import { clearAuthEntranceState,consumeAuthEntrance,markAuthEntrancePending,resetAuthEntranceForTests,shouldPlayAuthEntrance } from '../lib/authEntranceState'

describe('entrada autenticada premium',()=>{
 beforeEach(()=>{sessionStorage.clear();resetAuthEntranceForTests();vi.stubGlobal('Path2D',class {constructor(public path?:string){}});vi.useFakeTimers();vi.mocked(window.matchMedia).mockImplementation(query=>({matches:false,media:query,onchange:null,addListener:vi.fn(),removeListener:vi.fn(),addEventListener:vi.fn(),removeEventListener:vi.fn(),dispatchEvent:vi.fn()}))})
 afterEach(()=>{vi.useRealTimers();vi.restoreAllMocks()})
 it('uma sessão persistida executa na primeira entrada protegida do boot',()=>{render(<AuthEntranceExperience appReady><main>Dashboard</main></AuthEntranceExperience>);expect(screen.getByRole('status',{name:'Preparando sua operação'})).toBeInTheDocument();expect(screen.getByText('Dashboard').parentElement).toHaveAttribute('inert')})
 it('login confirmado rearma a experiência no mesmo boot',()=>{consumeAuthEntrance();expect(shouldPlayAuthEntrance()).toBe(false);markAuthEntrancePending();expect(shouldPlayAuthEntrance()).toBe(true)})
 it('não termina antes de cinco segundos e possui failsafe',()=>{render(<AuthEntranceExperience appReady={false}><main>Dashboard</main></AuthEntranceExperience>);act(()=>vi.advanceTimersByTime(4999));expect(screen.getByRole('status')).not.toHaveClass('leaving');act(()=>vi.advanceTimersByTime(AUTH_ENTRANCE_TIMING.desktop.max-4999+1));expect(screen.getByRole('status')).toHaveClass('leaving');expect(AUTH_ENTRANCE_TIMING.desktop.min).toBeGreaterThanOrEqual(5000);expect(AUTH_ENTRANCE_TIMING.desktop.max).toBeLessThanOrEqual(7000)})
 it('não repete na navegação SPA, mas um novo boot executa novamente',()=>{const first=render(<AuthEntranceExperience appReady={false}><main>Primeiro</main></AuthEntranceExperience>);act(()=>vi.advanceTimersByTime(AUTH_ENTRANCE_TIMING.desktop.max+20));act(()=>vi.advanceTimersByTime(AUTH_ENTRANCE_TIMING.desktop.exit+20));first.unmount();render(<AuthEntranceExperience><main>Segundo</main></AuthEntranceExperience>);expect(screen.queryByRole('status')).not.toBeInTheDocument();resetAuthEntranceForTests();render(<AuthEntranceExperience><main>Após reload</main></AuthEntranceExperience>);expect(screen.getByRole('status')).toBeInTheDocument()})
 it('logout rearma a próxima entrada',()=>{consumeAuthEntrance();clearAuthEntranceState();expect(shouldPlayAuthEntrance()).toBe(true)})
 it('usa três paths anatômicos, batida 1-2-3-2 e densidade adaptativa',()=>{render(<AuthEntranceExperience><main>Dashboard</main></AuthEntranceExperience>);expect(document.querySelectorAll('canvas.app-boot-swarm')).toHaveLength(1);expect(BAT_WING_FRAME_PATHS).toHaveLength(3);expect(BAT_WING_FRAME_PATHS.every(path=>path.includes('C')&&path.includes('L')&&path.includes('M-3-5'))).toBe(true);expect([0,1,2,3,4].map(getBatWingFrame)).toEqual([0,1,2,1,0]);expect(BAT_QUALITY_COUNTS).toEqual({low:36,medium:62,high:92});expect(BAT_SCENE_DURATION).toBe(5400)})
 it('gera target map com espaço negativo e qualidade responsiva',()=>{expect(getBatQuality({width:320,dpr:3,cores:4})).toBe('low');expect(getBatQuality({width:390,dpr:2,cores:8})).toBe('medium');expect(getBatQuality({width:1440,dpr:2,cores:12})).toBe('high');const pixels=new Uint8ClampedArray(24*24*4);for(let y=3;y<21;y++)for(let x=3;x<21;x++)if(!(x>8&&x<15&&y>8&&y<18))pixels[(y*24+x)*4+3]=255;const targets=sampleTargetPixels(pixels,24,24,20,()=>.31);expect(targets.length).toBeGreaterThan(8);expect(targets.every(([x,y])=>!(Math.abs(x)<.2&&y>-.15&&y<.35))).toBe(true)})
 it('remove a revoada no reduced motion',()=>{vi.mocked(window.matchMedia).mockImplementation(query=>({matches:query.includes('prefers-reduced-motion'),media:query,onchange:null,addListener:vi.fn(),removeListener:vi.fn(),addEventListener:vi.fn(),removeEventListener:vi.fn(),dispatchEvent:vi.fn()}));const raf=vi.spyOn(window,'requestAnimationFrame');markAuthEntrancePending();render(<AuthEntranceExperience><main>Dashboard</main></AuthEntranceExperience>);expect(document.querySelector('.app-boot-logo')).toBeInTheDocument();expect(raf).toHaveBeenCalledTimes(1)})
 it('limpa RAF, canvas e listener de resize',()=>{const context={setTransform:vi.fn(),clearRect:vi.fn(),save:vi.fn(),restore:vi.fn(),translate:vi.fn(),rotate:vi.fn(),scale:vi.fn(),beginPath:vi.fn(),moveTo:vi.fn(),bezierCurveTo:vi.fn(),lineTo:vi.fn(),quadraticCurveTo:vi.fn(),closePath:vi.fn(),fill:vi.fn(),globalAlpha:1,fillStyle:'',filter:''};vi.spyOn(HTMLCanvasElement.prototype,'getContext').mockReturnValue(context as never);const remove=vi.spyOn(window,'removeEventListener'),cancel=vi.spyOn(window,'cancelAnimationFrame');const view=render(<BatSwarmScene/>);act(()=>window.dispatchEvent(new Event('resize')));view.unmount();expect(remove).toHaveBeenCalledWith('resize',expect.any(Function));expect(cancel).toHaveBeenCalled();expect(context.clearRect).toHaveBeenCalled()})
 it('usa fallback sem bloquear a finalizacao',async()=>{vi.spyOn(HTMLCanvasElement.prototype,'getContext').mockReturnValue(null);markAuthEntrancePending();render(<AuthEntranceExperience appReady={false}><main>Dashboard preservado</main></AuthEntranceExperience>);await act(async()=>{await Promise.resolve()});expect(document.querySelector('.scene-fallback')).toBeInTheDocument();act(()=>vi.advanceTimersByTime(AUTH_ENTRANCE_TIMING.desktop.max+20));act(()=>vi.advanceTimersByTime(AUTH_ENTRANCE_TIMING.desktop.exit+20));expect(screen.getByText('Dashboard preservado')).toBeVisible()})
 it('mantem paleta monocromatica e fundo pre-React preto',()=>{const css=readFileSync(resolve(process.cwd(),'src/components/app-boot/app-boot-splash.css'),'utf8'),scene=readFileSync(resolve(process.cwd(),'src/components/app-boot/BatSwarmScene.tsx'),'utf8'),html=readFileSync(resolve(process.cwd(),'index.html'),'utf8');expect(css).toContain('background:#000');expect(css).not.toMatch(/#[0-9a-f]{6}/i);expect(scene).toContain("fillStyle='#fff'");expect(scene).not.toMatch(/#[0-9a-f]{6}/i);expect(html).toContain('background:#000');expect(html).not.toContain('app-boot-pending')})
})
