import {act,fireEvent,render,screen,waitFor} from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import {MemoryRouter} from 'react-router-dom'
import {beforeEach,describe,expect,it,vi} from 'vitest'
import {MobileAppDock} from '../components/mobile-navigation/MobileAppDock'
import {mobileNavigationIndex,navigationItems,primaryMobileNavigation,remainingMobileNavigation} from '../config/navigation'
import {useDemoStore} from '../store/useDemoStore'
import {getMobileDockVisualSettings,MOBILE_DOCK_DEFAULT_OPACITY,normalizeMobileDockOpacity} from '../lib/mobileDockVisual'
import {MobileNavigationPreferences} from '../pages/Settings'

describe('navegação mobile',()=>{
 beforeEach(()=>{vi.mocked(window.matchMedia).mockImplementation(query=>({matches:query.includes('max-width'),media:query,onchange:null,addListener:vi.fn(),removeListener:vi.fn(),addEventListener:vi.fn(),removeEventListener:vi.fn(),dispatchEvent:vi.fn()}));act(()=>useDemoStore.getState().reset())})
 it('identifica a posição ativa por rota e subrota',()=>{expect(mobileNavigationIndex('/app')).toBe(2);expect(mobileNavigationIndex('/app/relatorios/clientes')).toBe(0);expect(mobileNavigationIndex('/app/financeiro/saques')).toBe(1);expect(mobileNavigationIndex('/app/social/explore')).toBe(3);expect(mobileNavigationIndex('/app/assinaturas')).toBe(4)})
 it('descobre os módulos restantes a partir da configuração compartilhada',()=>{expect(primaryMobileNavigation.map(item=>item.label)).toEqual(['Relatórios','Financeiro','Dashboard','Social']);expect(remainingMobileNavigation.map(item=>item.label)).toContain('Assinaturas');for(const primary of primaryMobileNavigation)expect(remainingMobileNavigation).not.toContainEqual(primary);expect(navigationItems.map(item=>item.label)).toContain('Produtos')})
 it('abre e fecha o sheet Mais com saída animada e navegação acessível',async()=>{const user=userEvent.setup();const {container}=render(<MemoryRouter initialEntries={['/app/assinaturas']}><MobileAppDock/></MemoryRouter>),trigger=screen.getByRole('button',{name:'Mais módulos',hidden:true});expect(trigger).toHaveAttribute('aria-current','page');await user.click(trigger);expect(trigger).toHaveAttribute('aria-expanded','true');expect(screen.getByRole('dialog',{name:'Mais módulos',hidden:true})).toBeInTheDocument();expect(screen.getByRole('button',{name:'Assinaturas',hidden:true})).toBeInTheDocument();expect(document.body.style.overflow).toBe('hidden');fireEvent.keyDown(window,{key:'Escape'});await waitFor(()=>expect(container.querySelector('.mobile-more-layer')).toHaveClass('is-closing'));await waitFor(()=>expect(screen.queryByRole('dialog',{name:'Mais módulos',hidden:true})).not.toBeInTheDocument(),{timeout:700});expect(document.body.style.overflow).not.toBe('hidden')})
 it('persiste a opacidade dentro das preferências existentes',()=>{act(()=>useDemoStore.getState().updatePreferences('mobileNavigation',{opacity:67}));expect(useDemoStore.getState().preferences.mobileNavigation.opacity).toBe(67);const persisted=JSON.parse(localStorage.getItem('sphexpay-demo-v1')||'{}');expect(persisted.state.preferences.mobileNavigation.opacity).toBe(67)})
 it('usa 72 como padrão e normaliza entradas inválidas ou fora da faixa',()=>{expect(MOBILE_DOCK_DEFAULT_OPACITY).toBe(72);expect(useDemoStore.getState().preferences.mobileNavigation.opacity).toBe(72);expect(normalizeMobileDockOpacity(-20)).toBe(0);expect(normalizeMobileDockOpacity(140)).toBe(100);expect(normalizeMobileDockOpacity('34')).toBe(34);expect(normalizeMobileDockOpacity('inválido')).toBe(72);expect(normalizeMobileDockOpacity(null)).toBe(72);expect(normalizeMobileDockOpacity(Number.NaN)).toBe(72)})
 it('interpola uma superfície segura sem aplicar opacity ao container',()=>{expect(getMobileDockVisualSettings(0)).toMatchObject({opacity:0,backgroundAlpha:.46,blur:20});expect(getMobileDockVisualSettings(100)).toMatchObject({opacity:100,backgroundAlpha:.96,blur:8});const {container}=render(<MemoryRouter><MobileAppDock/></MemoryRouter>),dock=container.querySelector<HTMLElement>('.mobile-app-dock')!;expect(dock.style.getPropertyValue('--mobile-dock-bg-alpha')).toBe('0.82');expect(dock.style.opacity).toBe('')})
 it('lê e normaliza o valor persistido na hidratação',async()=>{const persisted=JSON.parse(localStorage.getItem('sphexpay-demo-v1')||'{}');persisted.state.preferences.mobileNavigation.opacity=91;localStorage.setItem('sphexpay-demo-v1',JSON.stringify(persisted));await act(async()=>useDemoStore.persist.rehydrate());expect(useDemoStore.getState().preferences.mobileNavigation.opacity).toBe(91);persisted.state.preferences.mobileNavigation.opacity=-400;localStorage.setItem('sphexpay-demo-v1',JSON.stringify(persisted));await act(async()=>useDemoStore.persist.rehydrate());expect(useDemoStore.getState().preferences.mobileNavigation.opacity).toBe(0)})
 it('atualiza slider, store e preview em tempo real',()=>{const {container}=render(<MobileNavigationPreferences/>),slider=screen.getByRole('slider',{name:'Transparência do menu mobile'}),preview=container.querySelector<HTMLElement>('.mobile-dock-preview>div')!;expect(slider).toHaveValue('72');expect(slider).toHaveAttribute('aria-valuemin','0');expect(slider).toHaveAttribute('aria-valuemax','100');expect(preview.style.getPropertyValue('--mobile-dock-bg-alpha')).toBe('0.82');fireEvent.change(slider,{target:{value:'25'}});expect(useDemoStore.getState().preferences.mobileNavigation.opacity).toBe(25);expect(screen.getByText('25%')).toBeInTheDocument();expect(preview.style.getPropertyValue('--mobile-dock-bg-alpha')).toBe('0.585')})
})
