import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { describe,expect,it } from 'vitest'

const read=(path:string)=>readFileSync(resolve(process.cwd(),path),'utf8')
const auth=read('src/services/authService.ts'),callback=read('src/pages/auth/AuthCallbackPage.tsx'),supabase=read('src/lib/supabase.ts'),html=read('index.html'),landing=read('src/pages/public/LandingPage.tsx'),css=read('src/public.css')

describe('segurança, SEO e responsividade pública',()=>{
 it('preserva os redirects Supabase existentes',()=>{
  expect(auth).toContain("`${window.location.origin}/auth/callback`")
  expect(auth).toContain("`${window.location.origin}/nova-senha`")
  expect(callback).toContain('exchangeCodeForSession')
  expect(callback).toContain("value?.startsWith('/app')")
 })
 it('reutiliza somente a chave publicável e não inclui service role no frontend público',()=>{
  expect(supabase).toContain('VITE_SUPABASE_PUBLISHABLE_KEY')
  expect(supabase).not.toMatch(/SERVICE_ROLE|SMTP|PRIVATE_KEY/)
  expect([landing,css,html].join('\n')).not.toMatch(/kingpay/i)
 })
 it('possui metadados essenciais e arquivos indexáveis',()=>{
  expect(html).toContain('rel="canonical"')
  expect(html).toContain('property="og:title"')
  expect(html).toContain('name="twitter:card"')
  expect(html).toContain('<meta name="theme-color" content="#fbfaf7"')
  expect(html).toContain('Sua operação no ritmo do próximo nível')
  expect(read('public/robots.txt')).toContain('sitemap.xml')
  expect(read('public/sitemap.xml')).toContain('https://sphexpay.vercel.app/')
 })
 it('usa direção pública clara e composição própria de celular e notificações',()=>{
  expect(landing).toContain('landing landing-v2')
  expect(landing).toContain('<PublicPhoneExperience/>')
  expect(landing).toContain('smart-notifications-section')
  expect(css).toContain('Public landing v2 — original light editorial direction for SphexPay.')
  expect(css).toContain('background:var(--pv2-paper)')
  expect(css).toContain('.public-phone-stage')
  expect(css).toContain('.smart-notifications-section')
 })
 it('mantém o hero final compacto, profundo e responsivo',()=>{
  const finalHero=css.slice(css.indexOf('/* Premium compact hero — final public cascade. */'))
  expect(finalHero).toContain('min-height:clamp(650px,78vh,740px)')
  expect(finalHero).toContain('grid-template-columns:minmax(0,44fr) minmax(0,56fr)')
  expect(finalHero).toContain('rotateZ(10deg) rotateY(-10deg)')
  expect(finalHero).toContain('max-width:178px')
  expect(finalHero).toContain('@media(min-width:768px) and (max-width:1100px)')
  expect(finalHero).toContain('@media(max-width:767px)')
  expect(finalHero).toContain('@media(prefers-reduced-motion:reduce)')
 })
 it('inclui narrativa editorial, fluxo e carrossel sem dependências pesadas',()=>{
  const editorial=read('src/components/landing/PublicEditorialSections.tsx')
  expect(editorial).toContain('PublicOperationalFlow')
  expect(editorial).toContain('PublicEditorialBenefits')
  expect(editorial).toContain('PublicResourceRail')
  expect(editorial).toContain("scrollBy({left:direction*340,behavior:'smooth'})")
  expect(editorial).not.toMatch(/WebGL|three|framer-motion|supabase|Realtime/)
  expect(css).toContain('scroll-snap-type:x mandatory')
  expect(css).toContain('overscroll-behavior-inline:contain')
 })
 it('cobre safe areas, áreas de toque, redução de movimento e larguras críticas',()=>{
  expect(css).toContain('env(safe-area-inset-top)')
  expect(css).toContain('min-height:44px')
  expect(css).toContain('@media(max-width:359px)')
  expect(css).toContain('@media(max-width:680px)')
  expect(css).toContain('@media(max-width:900px)')
  expect(css).toContain('@media(prefers-reduced-motion:reduce)')
  expect(css).toContain('overflow-x:clip')
 })
 it('mantém o hero e o mockup contidos abaixo de 768px sem alterar o breakpoint desktop',()=>{
  const finalHero=css.slice(css.indexOf('/* Premium compact hero — final public cascade. */'),css.indexOf('/* Editorial product story. */'))
  const mobileRule=finalHero.slice(finalHero.lastIndexOf('@media(max-width:767px)'))
  expect(mobileRule).toContain('grid-template-columns:minmax(0,1fr)')
  expect(mobileRule).toMatch(/\.landing-hero-visual\{[\s\S]*width:100%;[\s\S]*max-width:100%;[\s\S]*min-width:0;[\s\S]*transform:none/)
  expect(mobileRule).toContain('.public-phone-stage{width:100%;max-width:410px')
  expect(mobileRule).toContain('.phone-float-sale{top:61px;left:0}')
  expect(mobileRule).toContain('.phone-float-pix{right:0')
  expect(finalHero.slice(0,finalHero.lastIndexOf('@media(max-width:767px)'))).toContain('grid-template-columns:minmax(0,44fr) minmax(0,56fr)')
 })
})
