import { act,fireEvent,render,screen,within } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { beforeEach,describe,expect,it,vi } from 'vitest'
import App from '../App'
import { newLiveSale } from '../data/demo'
import { useDemoStore } from '../store/useDemoStore'
import { pwaInstallService } from '../services/pwaInstallService'
import { notificationTitles,saleEventType } from '../lib/notificationCatalog'
import { awardJourneyProgress } from '../services/awardProgressService'
import { INITIAL_BALANCE_IN_CENTS,WITHDRAWAL_ACCOUNT_KEY,WITHDRAWAL_BALANCE_KEY,WITHDRAWALS_KEY } from '../services/withdrawalService'

const authState=vi.hoisted(()=>({user:{id:'test-user',email:'player@sphexpay.test',email_confirmed_at:'2026-01-01',user_metadata:{full_name:'Ronald Rodriguez',onboarding_complete:true}},loading:false,configured:true,signOut:vi.fn(async()=>undefined)}))
vi.mock('../hooks/useAuth',()=>({useAuth:()=>authState}))
const privatePath=(path:string)=>path==='/'?'/app':path.startsWith('/app')?path:`/app${path}`
const renderAt=(path='/')=>{window.history.pushState({},'',privatePath(path));return render(<App/>)}
const renderPublic=(path:string)=>{window.history.pushState({},'',path);return render(<App/>)}
beforeEach(()=>{authState.user={id:'test-user',email:'player@sphexpay.test',email_confirmed_at:'2026-01-01',user_metadata:{full_name:'Ronald Rodriguez',onboarding_complete:true}};localStorage.clear();sessionStorage.clear();act(()=>useDemoStore.getState().reset());document.documentElement.dataset.theme='light'})

describe('SphexPay integration',()=>{
 it('abre a landing pública e navega para entrar e criar conta',async()=>{authState.user=null as never;const u=userEvent.setup();renderPublic('/');expect(screen.getByRole('heading',{name:/Venda, receba e escale/i})).toBeInTheDocument();await u.click(screen.getAllByRole('link',{name:'Entrar'})[0]);expect(screen.getByRole('heading',{name:'Bem-vindo de volta'})).toBeInTheDocument()})
 it('redireciona acesso privado sem sessão e preserva a origem',()=>{authState.user=null as never;renderPublic('/app/configuracoes');expect(screen.getByRole('heading',{name:'Bem-vindo de volta'})).toBeInTheDocument();expect(window.location.pathname).toBe('/entrar')})
 it('não simula OAuth quando os provedores não estão configurados',()=>{authState.user=null as never;renderPublic('/entrar');expect(screen.getByRole('button',{name:'Continuar com Google'})).toBeDisabled();expect(screen.getByRole('button',{name:'Continuar com Apple'})).toBeDisabled();expect(screen.getByText(/Supabase Auth não configurado/i)).toBeInTheDocument()})
 it('redireciona rota privada desconhecida para a visão geral',()=>{renderPublic('/app/rota-inexistente');expect(window.location.pathname).toBe('/app');expect(screen.getByRole('heading',{name:'Visão geral'})).toBeInTheDocument()})
 it('navega por todos os módulos',async()=>{const u=userEvent.setup();renderAt();const labels=['Visão geral','Vendas','Transações','Produtos','Assinaturas','Clientes','Checkout','Links de pagamento','Financeiro','Saques','Premiações','Inteligência artificial','Relatórios','Notificações','Configurações'];for(const label of labels){await u.click(screen.getByRole('link',{name:label}));expect(screen.getByRole('heading',{name:label})).toBeInTheDocument()}expect(screen.queryByRole('link',{name:'Mapa de vendas'})).not.toBeInTheDocument()})
 it('alterna tema global e persiste a preferência',async()=>{const u=userEvent.setup();renderAt();await u.click(screen.getByRole('button',{name:'Alternar tema'}));expect(document.documentElement.dataset.theme).toBe('dark');expect(JSON.parse(localStorage.getItem('sphexpay-demo-v1')!).state.theme).toBe('dark');await u.click(screen.getByRole('button',{name:'Alternar tema'}));expect(document.documentElement.dataset.theme).toBe('light')})
 it('renderiza estruturas responsivas para menu, cartões, gráfico e tabelas',()=>{const {container}=renderAt();expect(container.querySelector('aside')).toHaveClass('max-lg:-translate-x-full');expect(container.querySelector('.dashboard-metrics')).toBeInTheDocument();expect(container.querySelector('.recharts-responsive-container')).toBeInTheDocument();fireEvent.click(screen.getByRole('link',{name:'Vendas'}));expect(container.querySelector('.table-wrap')).toBeInTheDocument()})
 it('exibe perfil Player e busca superior acessível sem sobreposição estrutural',()=>{const {container}=renderAt();expect(screen.getByText('Player')).toBeInTheDocument();const search=screen.getByRole('searchbox',{name:'Buscar vendas, clientes e produtos'});expect(search).toHaveAttribute('placeholder','Buscar vendas, clientes, produtos...');expect(search.closest('.top-search')?.querySelector('svg')).toBeInTheDocument();expect(container.querySelector('.app-header')).toBeInTheDocument()})
 it('mostra o banner real e conecta o CTA ao regulamento',async()=>{act(()=>useDemoStore.getState().setLiveSales(false));const u=userEvent.setup();const {container}=renderAt();expect(screen.getByText(/controle, performance e escala/i)).toBeInTheDocument();await u.click(screen.getByRole('button',{name:'Próximo banner'}));expect((container.querySelector('.overview-track') as HTMLElement).style.transform).toBe('translateX(-100%)');expect(screen.getByText(/concorra a um iPhone 17 Pro Max/i)).toBeInTheDocument();expect(container.querySelector('.competition-product-image')).toHaveAttribute('src','/competitions/iphone-17-pro-max.jpeg');expect(screen.getByRole('link',{name:/Ver regulamento/})).toHaveAttribute('href','/app/competicao#regulamento')})
 it('exibe a competição abaixo da marca e abre a rota autenticada sem participantes fictícios',async()=>{const u=userEvent.setup();renderAt();const item=screen.getByRole('link',{name:/Competição/});expect(item.closest('.competition-sidebar-slot')).toBeInTheDocument();await u.click(item);expect(await screen.findByRole('heading',{name:'Rumo ao iPhone 17 Pro Max'})).toBeInTheDocument();expect(screen.getByRole('heading',{name:'O pódio está aberto'})).toBeInTheDocument();expect(document.querySelector('#regulamento')).toBeInTheDocument();expect(screen.queryByRole('heading',{name:'Auditoria da competição'})).not.toBeInTheDocument()})
 it('troca banners automaticamente e encerra o temporizador ao desmontar',()=>{vi.useFakeTimers();act(()=>useDemoStore.getState().setLiveSales(false));const {container,unmount}=renderAt();const track=container.querySelector('.overview-track') as HTMLElement;expect(track.style.transform).toBe('translateX(-0%)');act(()=>vi.advanceTimersByTime(6500));expect(track.style.transform).toBe('translateX(-100%)');unmount();expect(vi.getTimerCount()).toBe(0);vi.useRealTimers()})
 it('aplica calendário personalizado ao gráfico e ao estado global',async()=>{const u=userEvent.setup();const {container}=renderAt();await u.selectOptions(screen.getByLabelText('Período do gráfico'),'custom');const from=screen.getByLabelText('Data inicial do gráfico'),to=screen.getByLabelText('Data final do gráfico');await u.type(from,'2026-07-01');await u.type(to,'2026-07-05');expect(useDemoStore.getState().period).toMatchObject({preset:'custom',from:'2026-07-01',to:'2026-07-05'});expect(container.querySelector('.premium-chart')).toHaveAttribute('data-domain')})
 it('recalcula ao vivo a próxima premiação pelo faturamento',()=>{renderAt();expect(screen.getByRole('heading',{name:'Sphex 500k'})).toBeInTheDocument();act(()=>useDemoStore.getState().updateMetrics({revenue:120000}));expect(screen.getByRole('heading',{name:'Sphex 250k'})).toBeInTheDocument();expect(screen.getByText(/R\$ 130.000,00 para alcançar/i)).toBeInTheDocument()})
 it('remodela o gráfico e mantém o domínio elevado ao editar faturamento',()=>{const {container}=renderAt();const before=useDemoStore.getState().chart.map(point=>point.revenue);act(()=>useDemoStore.getState().updateMetrics({revenue:420000}));const after=useDemoStore.getState().chart.map(point=>point.revenue);expect(after).not.toEqual(before);const [lower,upper]=(container.querySelector('.premium-chart')?.getAttribute('data-domain')||'0-0').split('-').map(Number);expect(lower).toBeGreaterThan(0);expect(upper).toBeGreaterThan(lower)})
 it('edita métricas e gráfico, recalculando e persistindo',async()=>{const u=userEvent.setup();renderAt();await u.click(screen.getByRole('button',{name:'Editar Faturamento total'}));const revenue=screen.getByLabelText('Faturamento total');await u.clear(revenue);await u.type(revenue,'500000');await u.click(screen.getByRole('button',{name:'Salvar'}));await u.click(screen.getByRole('button',{name:'Editar Último ponto do gráfico'}));const point=screen.getByLabelText('Último ponto do gráfico');await u.clear(point);await u.type(point,'18000');await u.click(screen.getByRole('button',{name:'Salvar'}));expect(useDemoStore.getState().revenue).toBe(500000);expect(useDemoStore.getState().chart.at(-1)?.revenue).toBe(18000);expect(useDemoStore.getState().chart.at(-1)?.profit).toBe(12960);expect(JSON.parse(localStorage.getItem('sphexpay-demo-v1')!).state.revenue).toBe(500000)})
 it('atualiza os dados do gráfico e mantém séries relacionadas coerentes',()=>{act(()=>useDemoStore.getState().updateChart(0,10000));expect(useDemoStore.getState().chart[0]).toMatchObject({revenue:10000,profit:7200,sales:26})})
 it('insere venda simulada e atualiza saldos',()=>{const before={...useDemoStore.getState()};const sale={...newLiveSale(),amount:1000,fee:30,status:'Aprovado' as const};act(()=>useDemoStore.getState().addSale(sale));const after=useDemoStore.getState();expect(after.sales[0].id).toBe(sale.id);expect(after.revenue).toBe(before.revenue+1000);expect(after.available).toBeCloseTo(before.available+970)})
 it('desbloqueia e solicita premiação com revisão, consentimento e endereço persistente',async()=>{act(()=>useDemoStore.getState().updateMetrics({revenue:500000}));const u=userEvent.setup();renderAt('/premiacoes');const card=screen.getByRole('heading',{name:'Sphex 500k'}).closest('.panel')!;await u.click(within(card as HTMLElement).getByRole('button',{name:'Solicitar premiação'}));const values:Record<string,string>={'Nome completo':'Ronald Rodriguez','CEP':'01310-100','Rua':'Avenida Paulista','Número':'1000','Bairro':'Bela Vista','Cidade':'São Paulo','Estado':'SP','País':'Brasil','Telefone':'11999990000'};for(const [label,value] of Object.entries(values)){const input=screen.getByLabelText(label);await u.clear(input);await u.type(input,value)}await u.click(screen.getByRole('button',{name:'Revisar solicitação'}));await u.click(screen.getByRole('checkbox'));await u.click(screen.getByRole('button',{name:'Confirmar solicitação'}));const award=useDemoStore.getState().achievements.find(x=>x.id==='500k');expect(award?.address?.city).toBe('São Paulo');expect(award?.request?.status).toBe('Solicitação recebida');expect(screen.getByRole('heading',{name:'Solicitação recebida'})).toBeInTheDocument();expect(JSON.parse(localStorage.getItem('sphexpay-demo-v1')!).state.achievements.find((x:{id:string})=>x.id==='500k').redeemed).toBe(true)})
 it('registra saque local, desconta em centavos e persiste saldo, conta e histórico',async()=>{const u=userEvent.setup();renderAt('/saques');expect(await screen.findByRole('option',{name:'Conta cadastrada •••• 4821'})).toBeInTheDocument();expect(screen.getByText(/167\.555,69/)).toBeInTheDocument();await u.type(screen.getByLabelText('Valor do saque'),'500');await u.click(screen.getByRole('button',{name:'Confirmar solicitação'}));await u.click(screen.getByRole('button',{name:'Confirmar saque'}));expect(await screen.findByText('Saque solicitado com sucesso')).toBeInTheDocument();expect(screen.getByText(/Valor: R\$\s500,00/)).toBeInTheDocument();expect(screen.getAllByText('Conta final 4821')).toHaveLength(2);expect(Number(localStorage.getItem(WITHDRAWAL_BALANCE_KEY))).toBe(INITIAL_BALANCE_IN_CENTS-50000);expect(JSON.parse(localStorage.getItem(WITHDRAWAL_ACCOUNT_KEY)!).lastDigits).toBe('4821');expect(JSON.parse(localStorage.getItem(WITHDRAWALS_KEY)!)[0]).toMatchObject({amountInCents:50000,currency:'BRL',destinationLastDigits:'4821',status:'completed'});expect(useDemoStore.getState().available).toBe(167055.69)})
 it('não produz venda falsa no frontend após o intervalo',()=>{vi.useFakeTimers();act(()=>useDemoStore.getState().setLiveSales(true));renderAt();const count=useDemoStore.getState().sales.length;act(()=>vi.advanceTimersByTime(18000));expect(useDemoStore.getState().sales.length).toBe(count);vi.useRealTimers()})
 it('abre e fecha o painel do sino e acessa todas as notificações',async()=>{const u=userEvent.setup();renderAt();const bell=screen.getByRole('button',{name:/Notificações,/});await u.click(bell);expect(screen.getByRole('dialog',{name:'Notificações recentes'})).toBeInTheDocument();await u.click(screen.getByRole('button',{name:'Ver todas as notificações'}));expect(screen.getByRole('heading',{name:'Notificações'})).toBeInTheDocument()})
 it('marca uma, marca todas e exclui notificações',async()=>{const u=userEvent.setup();renderAt('/notificacoes');const firstUnread=useDemoStore.getState().notifications.find(n=>!n.read)!;const item=screen.getByText(firstUnread.title).closest('article')!;await u.click(within(item).getByRole('button',{name:'Marcar como lida'}));expect(useDemoStore.getState().notifications.find(n=>n.id===firstUnread.id)?.read).toBe(true);await u.click(screen.getByRole('button',{name:'Marcar todas como lidas'}));expect(useDemoStore.getState().notifications.every(n=>n.read)).toBe(true);const count=useDemoStore.getState().notifications.length;await u.click(screen.getAllByRole('button',{name:'Excluir notificação'})[0]);expect(useDemoStore.getState().notifications).toHaveLength(count-1)})
 it('arquiva e filtra notificações preservando o histórico',async()=>{const u=userEvent.setup();renderAt('/notificacoes');const first=useDemoStore.getState().notifications[0];await u.click(screen.getAllByRole('button',{name:'Arquivar notificação'})[0]);expect(useDemoStore.getState().notifications.find(item=>item.id===first.id)?.archived).toBe(true);await u.click(screen.getByRole('tab',{name:'Arquivadas'}));expect(screen.getByText(first.title)).toBeInTheDocument()})
 it('não adiciona eventos comerciais ao sino interno',()=>{const before=useDemoStore.getState().notifications.length;act(()=>useDemoStore.getState().addNotification({kind:'sale',category:'Vendas',title:'Venda aprovada!',description:'Sua comissão: R$ 3,83'}));expect(useDemoStore.getState().notifications).toHaveLength(before)})
 it('preserva moeda sem converter valores e sem criar item comercial interno',()=>{const sale={...newLiveSale(),id:'SPX-EUR-META',amount:249,currency:'EUR' as const,status:'Aprovado' as const},before=useDemoStore.getState().notifications.length;act(()=>useDemoStore.getState().addSale(sale));expect(useDemoStore.getState().notifications).toHaveLength(before);expect(new Intl.NumberFormat('pt-BR',{style:'currency',currency:'EUR'}).format(249)).toContain('249,00')})
 it('classifica corretamente eventos Pix, cartão e venda pendente',()=>{const base=newLiveSale();expect(notificationTitles[saleEventType({...base,method:'Pix',status:'Pendente'})]).toBe('Pix gerado!');expect(notificationTitles[saleEventType({...base,method:'Pix',status:'Aprovado'})]).toBe('Pix pago!');expect(notificationTitles[saleEventType({...base,method:'Cartão de crédito',status:'Aprovado'})]).toBe('Pagamento no cartão aprovado!');expect(notificationTitles[saleEventType({...base,method:'Assinatura',status:'Pendente'})]).toBe('Venda pendente!')})
 it('abre o gerador, atualiza o preview e salva um preset',async()=>{const u=userEvent.setup();renderAt('/configuracoes?secao=Notificações');expect(screen.getByRole('heading',{name:/Crie campanhas de notificações/i})).toBeInTheDocument();const title=screen.getByLabelText('Título da notificação');await u.clear(title);await u.type(title,'Campanha premium');expect(screen.getByText('Campanha premium')).toBeInTheDocument();await u.type(screen.getByLabelText('Nome do preset'),'Campanha rápida');await u.click(screen.getByRole('button',{name:'Salvar preset'}));expect(screen.getByText('Campanha rápida')).toBeInTheDocument();expect(localStorage.getItem('sphexpay_notification_generator_v1')).toContain('Campanha rápida')})
 it('calcula a jornada entre marcos sem concluir antes de 5 milhões',()=>{const awards=useDemoStore.getState().achievements;expect(awardJourneyProgress(0,awards)).toBe(0);expect(awardJourneyProgress(1000000,awards)).toBeCloseTo(5/6*100);expect(awardJourneyProgress(5000000,awards)).toBe(100)})
 it('mostra jornada vertical e usa placa também no nível 10k',()=>{const {container}=renderAt('/premiacoes');expect(container.querySelector('.award-timeline')).toBeInTheDocument();expect(container.querySelector('.timeline-rail')).toBeInTheDocument();expect(screen.getByLabelText('Placa Sphex 10k')).toBeInTheDocument();expect(container.querySelector('.bracelet-premium')).not.toBeInTheDocument();expect(container.querySelectorAll('.plaque-premium')).toHaveLength(6)})
 it('atualiza o gráfico sem criar notificação comercial interna',()=>{const before=useDemoStore.getState(),point=before.chart.at(-1)!.revenue,notifications=before.notifications.length;const sale={...newLiveSale(),id:'SPX-UNIQUE-TEST',amount:197,fee:4,status:'Aprovado' as const};act(()=>before.addSale(sale));const after=useDemoStore.getState();expect(after.notifications).toHaveLength(notifications);expect(after.chart.at(-1)!.revenue).toBe(point+197);act(()=>after.addSale(sale));expect(useDemoStore.getState().sales.filter(x=>x.id===sale.id)).toHaveLength(1)})
 it('ativa e desliga o microfone e encerra faixas ao sair',async()=>{const stop=vi.fn();Object.defineProperty(navigator,'mediaDevices',{configurable:true,value:{getUserMedia:vi.fn().mockResolvedValue({getTracks:()=>[{stop}]})}});const u=userEvent.setup();const view=renderAt('/assistente');await u.click(screen.getAllByRole('button',{name:'Ativar microfone'})[0]);expect(await screen.findByText('Ouvindo você')).toBeInTheDocument();await u.click(screen.getAllByRole('button',{name:'Desligar microfone'})[0]);expect(stop).toHaveBeenCalled();await u.click(screen.getAllByRole('button',{name:'Ativar microfone'})[0]);view.unmount();expect(stop).toHaveBeenCalledTimes(2)})
 it('trata permissão negada do microfone sem quebrar a aplicação',async()=>{Object.defineProperty(navigator,'mediaDevices',{configurable:true,value:{getUserMedia:vi.fn().mockRejectedValue(new DOMException('blocked','NotAllowedError'))}});const u=userEvent.setup();renderAt('/assistente');await u.click(screen.getAllByRole('button',{name:'Ativar microfone'})[0]);expect(await screen.findByText('Verifique o acesso de voz')).toBeInTheDocument();expect(screen.getAllByRole('button',{name:'Permissão negada'})[0]).toBeInTheDocument()})
 it('mantém a configuração exclusivamente no dispositivo sem solicitar permissão ao carregar',()=>{class MockNotification{static permission='default';static requestPermission=vi.fn(async()=>'granted')}vi.stubGlobal('Notification',MockNotification);renderAt('/configuracoes?secao=Notificações');expect(MockNotification.requestPermission).not.toHaveBeenCalled();expect(screen.getByRole('button',{name:'Ativar notificações neste dispositivo'})).toBeInTheDocument();expect(screen.getAllByText('Notificação do sistema').length).toBeGreaterThan(0);expect(screen.queryByText(/Somente dentro do gateway|Gateway e sistema|Notificações internas/)).not.toBeInTheDocument()})
 it('abre a área de aplicativo e oferece fallback de instalação',async()=>{const u=userEvent.setup();renderAt('/configuracoes');await u.click(screen.getByRole('button',{name:'Aplicativo'}));expect(screen.getByRole('button',{name:/Instalar aplicativo/})).toBeInTheDocument();await u.click(screen.getByRole('button',{name:/Instalar aplicativo/}));expect(await screen.findByText(/instalação não está disponível/i)).toBeInTheDocument()})
 it('preserva o prompt PWA até o usuário solicitar a instalação',async()=>{pwaInstallService.initialize();const prompt=vi.fn(async()=>undefined),event=new Event('beforeinstallprompt');Object.assign(event,{prompt,userChoice:Promise.resolve({outcome:'accepted'})});window.dispatchEvent(event);const u=userEvent.setup();renderAt('/configuracoes?secao=Aplicativo');await u.click(screen.getByRole('button',{name:/Instalar aplicativo/}));expect(prompt).toHaveBeenCalledOnce();expect(await screen.findByText('Instalação iniciada.')).toBeInTheDocument()})
 it('aplica o período global ao dashboard, vendas e relatórios',async()=>{const u=userEvent.setup();renderAt();const selector=screen.getByLabelText('Período do gráfico');await u.selectOptions(selector,'7d');expect(useDemoStore.getState().period.preset).toBe('7d');await u.click(screen.getByRole('link',{name:'Vendas'}));expect(screen.getByLabelText('Período')).toHaveValue('7d');await u.click(screen.getByRole('link',{name:'Relatórios'}));expect(screen.getByLabelText('Período')).toHaveValue('7d')})
 it('registra eventos pendentes sem duplicar, sem item no sino e movimenta o saldo pendente',()=>{const state=useDemoStore.getState(),before=state.pending,notifications=state.notifications.length,sale={...newLiveSale(),id:'SPX-PENDING-UNIQUE',status:'Pendente' as const,amount:315,fee:0};act(()=>state.addSale(sale));expect(useDemoStore.getState().pending).toBeCloseTo(before+315);expect(useDemoStore.getState().notifications).toHaveLength(notifications);act(()=>useDemoStore.getState().addSale(sale));expect(useDemoStore.getState().sales.filter(x=>x.id===sale.id)).toHaveLength(1)})
 it('edita transação e recalcula receita, saldo e pendências',async()=>{const pending={...newLiveSale(),id:'SPX-EDITABLE',status:'Pendente' as const,amount:200,fee:0};act(()=>useDemoStore.getState().addSale(pending));const before=useDemoStore.getState();const u=userEvent.setup();renderAt('/transacoes');await u.click(screen.getByRole('button',{name:'Editar SPX-EDITABLE'}));await u.selectOptions(screen.getByLabelText('Status'),'Aprovado');const fee=screen.getByLabelText('Taxa');await u.clear(fee);await u.type(fee,'10');await u.click(screen.getByRole('button',{name:'Salvar'}));const after=useDemoStore.getState();expect(after.revenue).toBeCloseTo(before.revenue+200);expect(after.available).toBeCloseTo(before.available+190);expect(after.pending).toBeCloseTo(before.pending-200);expect(JSON.parse(localStorage.getItem('sphexpay-demo-v1')!).state.sales.find((x:{id:string})=>x.id==='SPX-EDITABLE').status).toBe('Aprovado')})
 it('edita clientes e assinaturas com persistência',async()=>{const u=userEvent.setup();renderAt('/clientes');const customer=useDemoStore.getState().customers[0];await u.click(screen.getByRole('button',{name:`Editar ${customer.name}`}));const spent=screen.getByLabelText('Total gasto');await u.clear(spent);await u.type(spent,'9000');await u.click(screen.getByRole('button',{name:'Salvar'}));expect(useDemoStore.getState().customers[0].spent).toBe(9000);await u.click(screen.getByRole('link',{name:'Assinaturas'}));const subscription=useDemoStore.getState().subscriptions[0];await u.click(screen.getByRole('button',{name:`Editar assinatura de ${subscription.customer}`}));const amount=screen.getByLabelText('Valor');await u.clear(amount);await u.type(amount,'599');await u.click(screen.getByRole('button',{name:'Salvar'}));expect(useDemoStore.getState().subscriptions[0].amount).toBe(599);expect(JSON.parse(localStorage.getItem('sphexpay-demo-v1')!).state.subscriptions[0].amount).toBe(599)})
})
