import { create } from 'zustand'
import { persist } from 'zustand/middleware'
import { initialData } from '../data/demo'
import type { AppNotification, AppPreferences, Customer, DemoState, PeriodFilter, Product, Sale, ShippingAddress, Subscription, Theme,Withdrawal } from '../types'

const cleanLegacyEmail=(email:string)=>email.replace(/@demo\.local$/i,'@example.local')
const cleanLegacyAccount=(account:string)=>account.replace(/Banco demonstrativo/gi,'Conta cadastrada')
const impact=(sale:Sale)=>({revenue:sale.status==='Aprovado'?sale.amount:0,available:sale.status==='Aprovado'?sale.amount-sale.fee:0,pending:sale.status==='Pendente'||sale.status==='Em análise'?sale.amount:0,sales:sale.status==='Aprovado'?1:0})
const notificationTitle=(sale:Sale)=>sale.status==='Aprovado'?'Nova venda aprovada':sale.status==='Pendente'?'Pagamento pendente':sale.status==='Em análise'?'Pagamento em análise':sale.status==='Recusado'?'Pagamento recusado':'Venda atualizada'

interface Actions { setTheme:(theme:Theme)=>void; setPeriod:(period:PeriodFilter)=>void; setLiveSales:(v:boolean)=>void; addSale:(sale:Sale)=>void; updateSale:(sale:Sale)=>void; updateCustomer:(customer:Customer)=>void; updateSubscription:(subscription:Subscription)=>void; updateMetrics:(v:Partial<Pick<DemoState,'revenue'|'available'|'pending'|'goal'>>)=>void; syncWithdrawalCache:(available:number,withdrawals:Withdrawal[])=>void; updateChart:(index:number,value:number)=>void; addProduct:(p:Product)=>void; updateProduct:(p:Product)=>void; deleteProduct:(id:string)=>void; redeem:(id:string,address?:ShippingAddress)=>void; addNotification:(n:Omit<AppNotification,'id'|'createdAt'|'read'> & Partial<Pick<AppNotification,'id'|'createdAt'|'read'>>)=>void; markNotificationRead:(id:string)=>void; markAllNotificationsRead:()=>void; archiveNotification:(id:string)=>void; clearNotifications:()=>void; deleteNotification:(id:string)=>void; updatePreferences:(section:keyof AppPreferences,values:Partial<AppPreferences[keyof AppPreferences]>)=>void; reset:()=>void }
export const useDemoStore=create<DemoState&Actions>()(persist((set)=>({...initialData,
 setTheme:(theme)=>{document.documentElement.dataset.theme=theme;set({theme})},setPeriod:(period)=>set({period}),setLiveSales:(liveSales)=>set(s=>({liveSales,preferences:{...s.preferences,sales:{...s.preferences.sales,automaticUpdates:liveSales}}})),
 addSale:(sale)=>set(s=>{if(s.sales.some(existing=>existing.id===sale.id))return s;const change=impact(sale),chart=[...s.chart];if(change.sales&&chart.length){const last=chart.length-1;chart[last]={...chart[last],revenue:chart[last].revenue+change.revenue,profit:chart[last].profit+Math.round(change.available*.72),sales:chart[last].sales+1}}const notification:AppNotification={id:`NTF-${sale.id}`,kind:sale.status==='Aprovado'?'sale':'payment',category:sale.status==='Aprovado'?'Vendas':'Financeiro',title:notificationTitle(sale),description:`${sale.customer} · ${sale.product} · ${new Intl.NumberFormat('pt-BR',{style:'currency',currency:sale.currency}).format(sale.amount)}`,createdAt:new Date().toISOString(),read:false,priority:sale.status==='Aprovado'?'high':'normal',metadata:{buyer:sale.customer,product:sale.product,amount:sale.amount,currency:sale.currency,method:sale.method,status:sale.status,country:sale.country,source:'local'},detailPath:sale.status==='Aprovado'?'/vendas':'/transacoes'};return{sales:[sale,...s.sales].slice(0,500),revenue:s.revenue+change.revenue,available:s.available+change.available,pending:s.pending+change.pending,chart,notifications:s.preferences.notifications.internal&&s.preferences.sales.showNotifications?[notification,...s.notifications].slice(0,300):s.notifications}}),
 updateSale:(sale)=>set(s=>{const previous=s.sales.find(item=>item.id===sale.id);if(!previous)return s;const before=impact(previous),after=impact(sale),chart=[...s.chart],revenueDelta=after.revenue-before.revenue,availableDelta=after.available-before.available,salesDelta=after.sales-before.sales;if(chart.length&&(revenueDelta||salesDelta)){const last=chart.length-1;chart[last]={...chart[last],revenue:Math.max(0,chart[last].revenue+revenueDelta),profit:Math.max(0,chart[last].profit+Math.round(availableDelta*.72)),sales:Math.max(0,chart[last].sales+salesDelta)}}return{sales:s.sales.map(item=>item.id===sale.id?sale:item),revenue:Math.max(0,s.revenue+revenueDelta),available:Math.max(0,s.available+availableDelta),pending:Math.max(0,s.pending+after.pending-before.pending),chart}}),updateCustomer:(customer)=>set(s=>({customers:s.customers.map(item=>item.id===customer.id?customer:item)})),updateSubscription:(subscription)=>set(s=>({subscriptions:s.subscriptions.map(item=>item.id===subscription.id?subscription:item)})),
 updateMetrics:(v)=>set(s=>{const nextRevenue=v.revenue??s.revenue,revenueChanged=v.revenue!==undefined&&v.revenue!==s.revenue,factor=revenueChanged&&s.revenue>0?nextRevenue/s.revenue:1,chart=revenueChanged?s.chart.map(point=>{const revenue=Math.max(0,Math.round(point.revenue*factor));return{...point,revenue,profit:Math.round(revenue*.72),sales:Math.max(0,Math.round(point.sales*factor))}}):s.chart,reached=s.revenue<s.goal&&nextRevenue>=s.goal,newAwards=s.achievements.filter(item=>s.revenue<item.target&&nextRevenue>=item.target),events:AppNotification[]=[...(reached?[{id:`NTF-GOAL-${Date.now()}`,kind:'goal' as const,category:'Sistema' as const,title:'Meta de faturamento alcançada',description:`A meta de ${new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(s.goal)} foi alcançada.`,createdAt:new Date().toISOString(),read:false,priority:'high' as const,detailPath:'/'}]:[]),...newAwards.map(item=>({id:`NTF-AWARD-UNLOCK-${item.id}`,kind:'achievement' as const,category:'Sistema' as const,title:'Placa desbloqueada',description:`${item.title} está disponível para solicitação.`,createdAt:new Date().toISOString(),read:false,priority:'high' as const,detailPath:'/premiacoes'}))];return{...v,chart,notifications:events.length?[...events,...s.notifications.filter(item=>!events.some(event=>event.id===item.id))]:s.notifications}}),syncWithdrawalCache:(available,withdrawals)=>set({available,withdrawals}),updateChart:(index,value)=>set(s=>({chart:s.chart.map((p,i)=>i===index?{...p,revenue:value,profit:Math.round(value*.72),sales:Math.round(value/380)}:p)})),
 addProduct:(p)=>set(s=>({products:[p,...s.products]})),updateProduct:(p)=>set(s=>({products:s.products.map(x=>x.id===p.id?p:x)})),deleteProduct:(id)=>set(s=>({products:s.products.filter(p=>p.id!==id)})),
 redeem:(id,address)=>set(s=>{const achievement=s.achievements.find(a=>a.id===id),now=new Date().toISOString(),request=address?{id:`AWR-${id}-${Date.now()}`,requestedAt:achievement?.request?.requestedAt||now,updatedAt:now,status:'Solicitação recebida' as const,address}:undefined;return{achievements:s.achievements.map(a=>a.id===id&&address?{...a,redeemed:true,address,request,requestHistory:[...(a.requestHistory||[]),request!]}:a),notifications:achievement&&address&&s.preferences.notifications.internal?[{id:`NTF-AWARD-${id}-${Date.now()}`,kind:'achievement',category:'Sistema',title:'Solicitação de premiação recebida',description:`A solicitação de ${achievement.title} foi registrada.`,createdAt:now,read:false,priority:'high',detailPath:'/premiacoes'},...s.notifications]:s.notifications}}),
 addNotification:(n)=>set(s=>({notifications:[{...n,id:n.id||`NTF-${crypto.randomUUID?.()||Date.now()}`,createdAt:n.createdAt||new Date().toISOString(),read:n.read??false},...s.notifications.filter(x=>x.id!==n.id)].slice(0,300)})),
 markNotificationRead:(id)=>set(s=>({notifications:s.notifications.map(n=>n.id===id?{...n,read:true}:n)})),markAllNotificationsRead:()=>set(s=>({notifications:s.notifications.map(n=>({...n,read:true}))})),archiveNotification:(id)=>set(s=>({notifications:s.notifications.map(n=>n.id===id?{...n,archived:true,read:true}:n)})),clearNotifications:()=>set({notifications:[]}),deleteNotification:(id)=>set(s=>({notifications:s.notifications.filter(n=>n.id!==id)})),
 updatePreferences:(section,values)=>set(s=>({preferences:{...s.preferences,[section]:{...s.preferences[section],...values}} as AppPreferences,liveSales:section==='sales'&&'automaticUpdates' in values?Boolean(values.automaticUpdates):s.liveSales})),
 reset:()=>{document.documentElement.dataset.theme='light';set({...initialData})}
}),{name:'sphexpay-demo-v1',version:2,migrate:(persisted)=>persisted as DemoState,merge:(persisted,current)=>{const saved=persisted as Partial<DemoState>;return{...current,...saved,storageVersion:2,period:saved.period??current.period,sales:(saved.sales??current.sales).map(sale=>({...sale,email:cleanLegacyEmail(sale.email)})),customers:(saved.customers??current.customers).map(customer=>({...customer,email:cleanLegacyEmail(customer.email)})),withdrawals:(saved.withdrawals??current.withdrawals).map(withdrawal=>({...withdrawal,account:cleanLegacyAccount(withdrawal.account)})),notifications:saved.notifications??current.notifications,achievements:current.achievements.map(base=>{const old=saved.achievements?.find(a=>a.id===base.id);return old?{...base,redeemed:old.redeemed,address:old.address,request:old.request,requestHistory:old.requestHistory}:base}),preferences:{notifications:{...current.preferences.notifications,...saved.preferences?.notifications},assistant:{...current.preferences.assistant,...saved.preferences?.assistant},sales:{...current.preferences.sales,...saved.preferences?.sales}}}}}))
