import {useCallback,useEffect,useMemo,useState} from 'react'
import {Check,ChevronLeft,ChevronRight,Copy,Download,Info,Search,SlidersHorizontal,UserRoundCheck,Users,X} from 'lucide-react'
import {Badge,Button,Input,Select,Skeleton,Tooltip} from '../../components/ui'
import {affiliateService} from './affiliateService'
import type {Affiliate,AffiliateFilters,AffiliateProductOption,AffiliateStatus,CommissionType} from './types'
import './affiliates.css'

const emptyFilters:AffiliateFilters={query:'',status:'',productId:'',from:'',to:''},pageSize=20
const statusLabel:Record<AffiliateStatus,string>={active:'Ativo',pending:'Pendente',suspended:'Suspenso',inactive:'Inativo'}
const statusTone:Record<AffiliateStatus,'ok'|'warn'|'bad'|'neutral'>={active:'ok',pending:'warn',suspended:'bad',inactive:'neutral'}
const date=(value:string)=>new Intl.DateTimeFormat('pt-BR').format(new Date(value))
const commission=(type:CommissionType,value:number,currency='BRL')=>type==='percentage'?`${new Intl.NumberFormat('pt-BR',{maximumFractionDigits:2}).format(value)}%`:new Intl.NumberFormat('pt-BR',{style:'currency',currency}).format(value/100)
const csvCell=(value:string|number)=>`"${String(value).replace(/"/g,'""')}"`

export default function AffiliatesPage(){
 const [filters,setFilters]=useState(emptyFilters),[debouncedQuery,setDebouncedQuery]=useState(''),[page,setPage]=useState(1),[items,setItems]=useState<Affiliate[]>([]),[count,setCount]=useState(0),[products,setProducts]=useState<AffiliateProductOption[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(false),[filtersOpen,setFiltersOpen]=useState(false),[selected,setSelected]=useState<Affiliate|null>(null),[exporting,setExporting]=useState(false)
 useEffect(()=>{const timer=setTimeout(()=>setDebouncedQuery(filters.query),300);return()=>clearTimeout(timer)},[filters.query])
 useEffect(()=>{void affiliateService.products().then(setProducts).catch(()=>setProducts([]))},[])
 const activeFilters=useMemo(()=>({...filters,query:debouncedQuery}),[filters,debouncedQuery])
 const load=useCallback(async()=>{setLoading(true);setError(false);try{const result=await affiliateService.list(activeFilters,page,pageSize);setItems(result.items);setCount(result.count)}catch{setError(true);setItems([]);setCount(0)}finally{setLoading(false)}},[activeFilters,page])
 useEffect(()=>{void load()},[load])
 useEffect(()=>setPage(1),[activeFilters])
 const pages=Math.max(1,Math.ceil(count/pageSize)),counter=`${count} ${count===1?'afiliado':'afiliados'}`
 const update=<K extends keyof AffiliateFilters>(key:K,value:AffiliateFilters[K])=>setFilters(current=>({...current,[key]:value}))
 const exportCsv=async()=>{setExporting(true);try{const rows=await affiliateService.all(activeFilters),header=['Nome','Email','Produto','Comissão','ID do afiliado','Data de afiliação','Status'],body=rows.flatMap(person=>person.products.length?person.products.map(product=>[person.name,person.email||'',product.productName,commission(product.commissionType,product.commissionValue,product.currency),person.publicId,date(person.joinedAt),statusLabel[person.status]]):[[person.name,person.email||'','', '',person.publicId,date(person.joinedAt),statusLabel[person.status]]]),csv='\uFEFF'+[header,...body].map(row=>row.map(csvCell).join(';')).join('\n'),url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'})),link=document.createElement('a');link.href=url;link.download=`afiliados-${new Date().toISOString().slice(0,10)}.csv`;link.click();URL.revokeObjectURL(url)}finally{setExporting(false)}}
 return <section className="affiliates-page">
  <header className="affiliates-heading"><div><h1>Afiliados</h1><p aria-live="polite">{loading?'Carregando afiliados…':counter}</p></div><Button onClick={()=>void exportCsv()} disabled={loading||exporting||count===0}><Download/>{exporting?'Exportando…':'Exportar'}</Button></header>
  <div className="affiliates-toolbar"><label className="affiliates-search"><Search/><span className="sr-only">Pesquisar afiliados</span><Input value={filters.query} onChange={event=>update('query',event.target.value)} placeholder="Nome, email, ID ou produto"/>{filters.query&&<button aria-label="Limpar pesquisa" onClick={()=>update('query','')}><X/></button>}</label><Button aria-expanded={filtersOpen} aria-controls="affiliate-filters" onClick={()=>setFiltersOpen(value=>!value)}><SlidersHorizontal/>Filtros</Button></div>
  {filtersOpen&&<div id="affiliate-filters" className="affiliate-filters"><label>Status<Select aria-label="Filtrar por status" value={filters.status} onChange={event=>update('status',event.target.value as AffiliateStatus|'')}><option value="">Todos</option>{Object.entries(statusLabel).map(([value,label])=><option value={value} key={value}>{label}</option>)}</Select></label><label>Produto<Select aria-label="Filtrar por produto" value={filters.productId} onChange={event=>update('productId',event.target.value)}><option value="">Todos</option>{products.map(product=><option value={product.id} key={product.id}>{product.name}</option>)}</Select></label><label>De<Input aria-label="Data inicial" type="date" value={filters.from} onChange={event=>update('from',event.target.value)}/></label><label>Até<Input aria-label="Data final" type="date" value={filters.to} onChange={event=>update('to',event.target.value)}/></label><Button variant="ghost" onClick={()=>setFilters(emptyFilters)}>Limpar filtros</Button></div>}
  <div className="affiliate-surface">{loading?<AffiliateSkeleton/>:error?<div className="affiliate-state" role="alert"><Users/><h2>Não foi possível carregar os afiliados.</h2><p>Verifique sua conexão e tente novamente.</p><Button onClick={()=>void load()}>Tentar novamente</Button></div>:!items.length?<div className="affiliate-state"><UserRoundCheck/><h2>Nenhum afiliado encontrado</h2><p>Quando afiliados forem adicionados, eles aparecerão aqui.</p></div>:<><div className="affiliate-table-wrap"><table><thead><tr><th>Nome</th><th>Produto</th><th><span className="commission-title">Comissão <Tooltip content="Valor ou percentual recebido pelo afiliado por cada venda elegível."><Info aria-label="Sobre a comissão" tabIndex={0}/></Tooltip></span></th><th>ID de afiliado</th><th>Data de afiliação</th><th><span className="sr-only">Ações</span></th></tr></thead><tbody>{items.map(person=><AffiliateRow person={person} onSelect={setSelected} key={person.id}/>)}</tbody></table></div><div className="affiliate-mobile-list">{items.map(person=><AffiliateCard person={person} onSelect={setSelected} key={person.id}/>)}</div></>}
  </div>
  {!loading&&!error&&count>pageSize&&<nav className="affiliate-pagination" aria-label="Paginação de afiliados"><span>Página {page} de {pages}</span><div><Button size="icon" aria-label="Página anterior" disabled={page===1} onClick={()=>setPage(value=>value-1)}><ChevronLeft/></Button><Button size="icon" aria-label="Próxima página" disabled={page===pages} onClick={()=>setPage(value=>value+1)}><ChevronRight/></Button></div></nav>}
  {selected&&<AffiliateDetails affiliate={selected} onClose={()=>setSelected(null)}/>}
 </section>
}

function ProductSummary({person}:{person:Affiliate}){const first=person.products[0];return first?<span>{first.productName}{person.products.length>1&&<small> +{person.products.length-1}</small>}</span>:<span className="muted">Sem produto</span>}
function AffiliateRow({person,onSelect}:{person:Affiliate;onSelect:(value:Affiliate)=>void}){return <tr><td><button className="affiliate-name" onClick={()=>onSelect(person)}><b>{person.name}</b>{person.email&&<small>{person.email}</small>}</button></td><td><ProductSummary person={person}/></td><td>{person.products[0]?commission(person.products[0].commissionType,person.products[0].commissionValue,person.products[0].currency):'—'}</td><td><CopyId value={person.publicId}/></td><td>{date(person.joinedAt)}</td><td><Button variant="ghost" size="sm" onClick={()=>onSelect(person)}>Detalhes</Button></td></tr>}
function AffiliateCard({person,onSelect}:{person:Affiliate;onSelect:(value:Affiliate)=>void}){return <button className="affiliate-card" onClick={()=>onSelect(person)}><header><span><b>{person.name}</b>{person.email&&<small>{person.email}</small>}</span><Badge tone={statusTone[person.status]}>{statusLabel[person.status]}</Badge></header><dl><div><dt>Produto</dt><dd><ProductSummary person={person}/></dd></div><div><dt>Comissão</dt><dd>{person.products[0]?commission(person.products[0].commissionType,person.products[0].commissionValue,person.products[0].currency):'—'}</dd></div><div><dt>ID</dt><dd>{person.publicId}</dd></div></dl></button>}
function CopyId({value}:{value:string}){const [copied,setCopied]=useState(false);return <button className="affiliate-copy" aria-label={`Copiar ID ${value}`} onClick={()=>void navigator.clipboard.writeText(value).then(()=>{setCopied(true);setTimeout(()=>setCopied(false),1200)})}>{value}{copied?<Check/>:<Copy/>}</button>}
function AffiliateDetails({affiliate,onClose}:{affiliate:Affiliate;onClose:()=>void}){useEffect(()=>{const escape=(event:KeyboardEvent)=>{if(event.key==='Escape')onClose()};addEventListener('keydown',escape);return()=>removeEventListener('keydown',escape)},[onClose]);return <div className="affiliate-drawer-backdrop" onMouseDown={onClose}><aside className="affiliate-drawer" role="dialog" aria-modal="true" aria-labelledby="affiliate-detail-title" onMouseDown={event=>event.stopPropagation()}><header><div><span>Afiliado</span><h2 id="affiliate-detail-title">{affiliate.name}</h2></div><Button size="icon" variant="ghost" aria-label="Fechar detalhes" onClick={onClose}><X/></Button></header><section><h3>Informações</h3><dl><div><dt>Email</dt><dd>{affiliate.email||'Não informado'}</dd></div><div><dt>ID público</dt><dd>{affiliate.publicId}</dd></div><div><dt>Status</dt><dd><Badge tone={statusTone[affiliate.status]}>{statusLabel[affiliate.status]}</Badge></dd></div><div><dt>Data de entrada</dt><dd>{date(affiliate.joinedAt)}</dd></div></dl></section><section><h3>Produtos e comissão</h3>{affiliate.products.length?<div className="affiliate-product-list">{affiliate.products.map(product=><article key={product.id}><span><b>{product.productName}</b><small>{product.commissionType==='percentage'?'Comissão percentual':'Comissão fixa'}</small></span><strong>{commission(product.commissionType,product.commissionValue,product.currency)}</strong></article>)}</div>:<p className="muted">Nenhum produto vinculado.</p>}</section></aside></div>}
function AffiliateSkeleton(){return <div className="affiliate-skeleton" role="status" aria-label="Carregando afiliados">{Array.from({length:6},(_,index)=><div key={index}><Skeleton/><Skeleton/><Skeleton/><Skeleton/></div>)}</div>}
