import { useEffect,useRef,useState,type FormEvent } from 'react'
import { Link } from 'react-router-dom'
import { ArrowLeft,Mail } from 'lucide-react'
import { AuthLayout } from '../../components/auth/AuthLayout'
import { AuthNotice } from '../../components/auth/AuthError'
import { supabaseUnavailableMessage } from '../../lib/supabase'
import { authMessage,authService } from '../../services/authService'
import { useAuth } from '../../hooks/useAuth'
export default function ForgotPasswordPage(){const [email,setEmail]=useState(''),[error,setError]=useState(''),[sent,setSent]=useState(false),[loading,setLoading]=useState(false),[cooldown,setCooldown]=useState(false),timer=useRef<ReturnType<typeof setTimeout>|null>(null),{configured}=useAuth();useEffect(()=>()=>{if(timer.current)clearTimeout(timer.current)},[]);const submit=async(event:FormEvent)=>{event.preventDefault();if(loading||cooldown)return;if(!configured){setError(supabaseUnavailableMessage);return}setLoading(true);setError('');try{const {error:failure}=await authService.resetPassword(email.trim());if(failure)throw failure;setSent(true);setCooldown(true);timer.current=setTimeout(()=>setCooldown(false),30000)}catch(reason){setError(authMessage(reason))}finally{setLoading(false)}};return <AuthLayout eyebrow="RECUPERAÇÃO DE ACESSO"><h1>Recupere sua senha</h1><p className="auth-subtitle">Enviaremos um link seguro para o e-mail cadastrado.</p><form className="auth-form" onSubmit={submit}><label className="auth-field"><span>E-mail</span><div className="field-control"><Mail/><input type="email" value={email} onChange={e=>setEmail(e.target.value)} autoComplete="email" inputMode="email" required/></div></label><AuthNotice message={sent?'Se o e-mail estiver cadastrado, você receberá as instruções. Verifique também a caixa de spam.':error} success={sent}/><button className="auth-submit" disabled={loading||cooldown} aria-busy={loading}>{loading?'Enviando...':cooldown?'Aguarde para reenviar':'Enviar link de recuperação'}</button></form><Link className="auth-return" to="/entrar"><ArrowLeft/> Voltar ao login</Link></AuthLayout>}
