import { useEffect,useRef,useState,type FormEvent } from 'react'
import { Link,useNavigate } from 'react-router-dom'
import { AuthLayout } from '../../components/auth/AuthLayout'
import { AuthNotice } from '../../components/auth/AuthError'
import { AuthLoading } from '../../components/auth/AuthLoading'
import { PasswordField } from '../../components/auth/PasswordField'
import { PasswordStrength } from '../../components/auth/PasswordStrength'
import { passwordScore } from '../../lib/authValidation'
import { authMessage,authService } from '../../services/authService'
import { useAuth } from '../../hooks/useAuth'

export default function ResetPasswordPage(){const [password,setPassword]=useState(''),[confirm,setConfirm]=useState(''),[message,setMessage]=useState(''),[success,setSuccess]=useState(false),[loading,setLoading]=useState(false),timer=useRef<ReturnType<typeof setTimeout>|null>(null),navigate=useNavigate(),auth=useAuth();useEffect(()=>()=>{if(timer.current)clearTimeout(timer.current)},[]);if(auth.loading)return <AuthLoading/>;if(!auth.user)return <AuthLayout eyebrow="LINK DE RECUPERAÇÃO"><h1>Link inválido ou expirado</h1><p className="auth-subtitle">Solicite um novo link para definir sua senha com segurança.</p><AuthNotice message="A sessão de recuperação não foi encontrada."/><p className="auth-switch"><Link to="/recuperar-senha">Solicitar novo link</Link></p></AuthLayout>;const submit=async(event:FormEvent)=>{event.preventDefault();if(loading)return;if(passwordScore(password)<4){setMessage('Use uma senha forte com pelo menos 8 caracteres, maiúscula, número e símbolo.');return}if(password!==confirm){setMessage('As senhas não coincidem.');return}setLoading(true);setMessage('');try{const {error}=await authService.updatePassword(password);if(error)throw error;setSuccess(true);setMessage('Sua senha foi atualizada. Você será direcionado ao painel.');timer.current=setTimeout(()=>navigate(auth.user?.user_metadata?.onboarding_complete?'/app':'/onboarding',{replace:true}),1800)}catch(reason){setMessage(authMessage(reason))}finally{setLoading(false)}};return <AuthLayout eyebrow="NOVA SENHA"><h1>Defina uma nova senha</h1><p className="auth-subtitle">Escolha uma senha exclusiva e difícil de adivinhar.</p><form className="auth-form" onSubmit={submit}><PasswordField label="Nova senha" value={password} onChange={setPassword} autoComplete="new-password"/><PasswordStrength value={password}/><PasswordField label="Confirmar nova senha" value={confirm} onChange={setConfirm} autoComplete="new-password"/><AuthNotice message={message} success={success}/><button className="auth-submit" disabled={loading||success} aria-busy={loading}>{loading?'Atualizando...':'Atualizar senha'}</button></form></AuthLayout>}
