import {useEffect,useMemo,useRef,useState,type ReactNode} from 'react'
import {CalendarDays,ChevronDown,ChevronLeft,ChevronRight,Download,Info,Search,SlidersHorizontal} from 'lucide-react'
import {Line,LineChart,ResponsiveContainer,Tooltip as ChartTooltip,XAxis,YAxis} from 'recharts'
import {Button,Skeleton} from '../../components/ui'
import {useAuth} from '../../hooks/useAuth'
import {subscriptionService} from './subscriptionService'
import type {SubscriptionDataset,SubscriptionProduct,SubscriptionRecord,SubscriptionStatus} from './types'
import './subscriptions.css'

type Tab='overview'|'list'
type PeriodKey='month'|'last-month'|'30-days'|'90-days'|'all'
type SortKey='createdAt'|'currentPeriodEnd'
type SortDirection='asc'|'desc'
const pageSize=20
const labels:Record<SubscriptionStatus,string>={active:'Ativa',cancelled:'Cancelada',inactive:'Inativa'}
const emptyData:SubscriptionDataset={items:[],products:[],truncated:false}
const day=(value:Date)=>new Date(value.getFullYear(),value.getMonth(),value.getDate())
const endDay=(value:Date)=>new Date(value.getFullYear(),value.getMonth(),value.getDate(),23,59,59,999)
const rangeFor=(key:PeriodKey,now=new Date())=>{let start:Date,end=endDay(now);if(key==='month')start=new Date(now.getFullYear(),now.getMonth(),1);else if(key==='last-month'){start=new Date(now.getFullYear(),now.getMonth()-1,1);end=endDay(new Date(now.getFullYear(),now.getMonth(),0))}else if(key==='30-days')start=day(new Date(now.getFullYear(),now.getMonth(),now.getDate()-29));else if(key==='90-days')start=day(new Date(now.getFullYear(),now.getMonth(),now.getDate()-89));else start=new Date(0);const duration=end.getTime()-start.getTime()+1,previousEnd=new Date(start.getTime()-1),previousStart=new Date(previousEnd.getTime()-duration+1);return{start,end,previousStart,previousEnd}}
const inside=(value:string|null,start:Date,end:Date)=>Boolean(value&&new Date(value)>=start&&new Date(value)<=end)
const date=(value:string|null)=>value?new Intl.DateTimeFormat('pt-BR').format(new Date(value)):'—'
const rangeDate=(value:Date)=>new Intl.DateTimeFormat('pt-BR',{day:'numeric',month:'short'}).format(value).replace('.','')
const percent=(current:number,previous:number)=>previous===0?(current===0?0:100):((current-previous)/previous)*100
const csvCell=(value:string)=>`"${value.replace(/"/g,'""')}"`

export default function SubscriptionsPage(){
 const {user}=useAuth(),[tab,setTab]=useState<Tab>('overview'),[data,setData]=useState(emptyData),[loading,setLoading]=useState(true),[error,setError]=useState(false)
 useEffect(()=>{let active=true;setLoading(true);setError(false);if(!user?.id){setLoading(false);return}subscriptionService.load(user.id).then(value=>{if(active)setData(value)}).catch(()=>{if(active)setError(true)}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[user?.id])
 return <section className="subscriptions-page page-enter" aria-labelledby="subscriptions-title">
  <header className="subscriptions-heading"><h1 id="subscriptions-title">Assinaturas</h1></header>
  <nav className="subscriptions-tabs" aria-label="Seções de assinaturas"><button className={tab==='overview'?'active':''} onClick={()=>setTab('overview')} aria-current={tab==='overview'?'page':undefined}>Visão geral</button><button className={tab==='list'?'active':''} onClick={()=>setTab('list')} aria-current={tab==='list'?'page':undefined}>Assinaturas</button></nav>
  {error?<ErrorState onRetry={()=>{if(!user?.id)return;setLoading(true);setError(false);subscriptionService.load(user.id).then(setData).catch(()=>setError(true)).finally(()=>setLoading(false))}}/>:tab==='overview'?<Overview data={data} loading={loading}/>:<SubscriptionList data={data} loading={loading}/>} 
 </section>
}

function Overview({data,loading}:{data:SubscriptionDataset;loading:boolean}){
 const [period,setPeriod]=useState<PeriodKey>('month'),[products,setProducts]=useState<string[]>([]),range=useMemo(()=>rangeFor(period),[period]),items=useMemo(()=>data.items.filter(item=>!products.length||(item.productId&&products.includes(item.productId))),[data.items,products])
 const metrics=useMemo(()=>metricSet(items,range),[items,range]),series=useMemo(()=>chartSeries(items,range.start,range.end),[items,range])
 return <div className="subscriptions-overview">
  <div className="subscriptions-filter-row"><MultiSelect label="Produto(s)" icon={<SlidersHorizontal/>} options={data.products} selected={products} onChange={setProducts}/><div className="subscriptions-date-group"><span><CalendarDays/>Data</span><label className="subscriptions-select"><select aria-label="Período da visão geral" value={period} onChange={event=>setPeriod(event.target.value as PeriodKey)}><option value="month">Esse mês</option><option value="last-month">Mês passado</option><option value="30-days">Últimos 30 dias</option><option value="90-days">Últimos 90 dias</option><option value="all">Todo o período</option></select><ChevronDown/></label></div></div>
  <p className="subscriptions-comparison">em comparação com o período anterior ({rangeDate(range.previousStart)} - {rangeDate(range.previousEnd)})</p>
  {data.truncated&&<p className="subscriptions-notice">A análise considera as 500 transações recorrentes mais recentes.</p>}
  {loading?<OverviewSkeleton/>:<div className="subscriptions-metric-grid"><article className="subscriptions-primary-card"><MetricHeader label="Assinaturas ativas"/><strong className="subscriptions-value">{metrics.active.current}</strong><Variation value={metrics.active.change}/><div className="subscriptions-chart" aria-label="Evolução de assinaturas ativas"><ResponsiveContainer width="100%" height="100%"><LineChart data={series} margin={{top:20,right:10,left:-28,bottom:0}}><XAxis dataKey="label" axisLine={false} tickLine={false} minTickGap={28} tick={{fill:'var(--muted)',fontSize:10}}/><YAxis allowDecimals={false} axisLine={false} tickLine={false} tick={{fill:'var(--muted)',fontSize:10}}/><ChartTooltip content={<ChartTip/>}/><Line type="monotone" dataKey="value" stroke="var(--text)" strokeWidth={1.75} dot={false} activeDot={{r:4,fill:'var(--text)',stroke:'var(--panel)',strokeWidth:2}}/></LineChart></ResponsiveContainer></div></article><div className="subscriptions-side-metrics"><MetricCard label="Novos assinantes" metric={metrics.new}/><MetricCard label="Assinaturas canceladas" metric={metrics.cancelled}/><MetricCard label="Assinaturas inativadas" metric={metrics.inactive}/></div></div>}
 </div>
}

function metricSet(items:SubscriptionRecord[],range:ReturnType<typeof rangeFor>){
 const countActive=(at:Date)=>items.filter(item=>new Date(item.createdAt)<=at&&(!item.cancelledAt||new Date(item.cancelledAt)>at)&&(item.status!=='inactive'||!item.currentPeriodEnd||new Date(item.currentPeriodEnd)>at)).length
 const build=(current:number,previous:number)=>({current,change:percent(current,previous)})
 return {active:build(countActive(range.end),countActive(range.previousEnd)),new:build(items.filter(item=>inside(item.createdAt,range.start,range.end)).length,items.filter(item=>inside(item.createdAt,range.previousStart,range.previousEnd)).length),cancelled:build(items.filter(item=>item.status==='cancelled'&&inside(item.cancelledAt||item.statusChangedAt,range.start,range.end)).length,items.filter(item=>item.status==='cancelled'&&inside(item.cancelledAt||item.statusChangedAt,range.previousStart,range.previousEnd)).length),inactive:build(items.filter(item=>item.status==='inactive'&&inside(item.currentPeriodEnd||item.statusChangedAt,range.start,range.end)).length,items.filter(item=>item.status==='inactive'&&inside(item.currentPeriodEnd||item.statusChangedAt,range.previousStart,range.previousEnd)).length)}
}
function chartSeries(items:SubscriptionRecord[],start:Date,end:Date){const totalDays=Math.max(1,Math.ceil((end.getTime()-start.getTime())/86400000)+1),step=Math.max(1,Math.ceil(totalDays/30)),points=[];for(let index=0;index<totalDays;index+=step){const at=endDay(new Date(start.getTime()+index*86400000)),value=items.filter(item=>new Date(item.createdAt)<=at&&(!item.cancelledAt||new Date(item.cancelledAt)>at)&&(item.status!=='inactive'||!item.currentPeriodEnd||new Date(item.currentPeriodEnd)>at)).length;points.push({label:new Intl.DateTimeFormat('pt-BR',{day:'2-digit',month:'short'}).format(at).replace('.',''),value})}return points}
function MetricHeader({label}:{label:string}){return <div className="subscriptions-metric-label"><span>{label}</span><Info aria-label={`Sobre ${label}`}/></div>}
function Variation({value}:{value:number}){return <div className="subscriptions-variation"><span className={value>0?'positive':value<0?'negative':''}>{value>0?'+':''}{value.toLocaleString('pt-BR',{minimumFractionDigits:2,maximumFractionDigits:2})}%</span><small>vs. o período anterior</small></div>}
function MetricCard({label,metric}:{label:string;metric:{current:number;change:number}}){return <article className="subscriptions-side-card"><MetricHeader label={label}/><strong className="subscriptions-value">{metric.current}</strong><Variation value={metric.change}/></article>}
function ChartTip({active,payload,label}:{active?:boolean;payload?:Array<{value:number}>;label?:string}){return active&&payload?.length?<div className="subscriptions-chart-tip"><span>{label}</span><strong>{payload[0].value}</strong><small>assinaturas ativas</small></div>:null}

function SubscriptionList({data,loading}:{data:SubscriptionDataset;loading:boolean}){
 const [query,setQuery]=useState(''),[debounced,setDebounced]=useState(''),[products,setProducts]=useState<string[]>([]),[statuses,setStatuses]=useState<string[]>(['active','cancelled','inactive']),[period,setPeriod]=useState<PeriodKey>('all'),[sort,setSort]=useState<{key:SortKey;direction:SortDirection}>({key:'createdAt',direction:'desc'}),[page,setPage]=useState(1),[selected,setSelected]=useState<string[]>([])
 useEffect(()=>{const timer=setTimeout(()=>setDebounced(query.trim().toLowerCase()),250);return()=>clearTimeout(timer)},[query])
 useEffect(()=>setPage(1),[debounced,products,statuses,period,sort])
 const rows=useMemo(()=>{const range=rangeFor(period);return data.items.filter(item=>(!debounced||[item.customerName,item.customerEmail,item.id,item.productName].some(value=>value?.toLowerCase().includes(debounced)))&&(!products.length||(item.productId&&products.includes(item.productId)))&&(!statuses.length||statuses.includes(item.status))&&(period==='all'||inside(item.createdAt,range.start,range.end))).sort((a,b)=>{const av=a[sort.key]?new Date(a[sort.key] as string).getTime():0,bv=b[sort.key]?new Date(b[sort.key] as string).getTime():0;return(av-bv)*(sort.direction==='asc'?1:-1)})},[data.items,debounced,products,statuses,period,sort]),pages=Math.max(1,Math.ceil(rows.length/pageSize)),visible=rows.slice((page-1)*pageSize,page*pageSize)
 const changeSort=(key:SortKey)=>setSort(current=>({key,direction:current.key===key&&current.direction==='desc'?'asc':'desc'})),exportCsv=()=>{const header=['Cliente','Email','Status','ID da assinatura','Produto','Data da criação','Data de vencimento'],body=rows.map(item=>[item.customerName,item.customerEmail||'',labels[item.status],item.id,item.productName,date(item.createdAt),date(item.currentPeriodEnd)]),csv='\uFEFF'+[header,...body].map(row=>row.map(csvCell).join(';')).join('\n'),url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'})),link=document.createElement('a');link.href=url;link.download=`assinaturas-${new Date().toISOString().slice(0,10)}.csv`;link.click();URL.revokeObjectURL(url)}
 return <div className="subscriptions-list"><div className="subscriptions-toolbar"><label className="subscriptions-search"><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Buscar..." aria-label="Buscar assinaturas"/><Search/></label><MultiSelect label="Produto(s)" options={data.products} selected={products} onChange={setProducts}/><label className="subscriptions-select"><CalendarDays/><select aria-label="Filtrar por período" value={period} onChange={event=>setPeriod(event.target.value as PeriodKey)}><option value="all">Período</option><option value="month">Esse mês</option><option value="last-month">Mês passado</option><option value="30-days">Últimos 30 dias</option><option value="90-days">Últimos 90 dias</option></select><ChevronDown/></label><MultiSelect label="Status" options={Object.entries(labels).map(([id,name])=>({id,name}))} selected={statuses} onChange={setStatuses}/><Button className="subscriptions-export" onClick={exportCsv} disabled={loading||!rows.length}><Download/>Exportar</Button></div>
  <div className="subscriptions-table-surface">{loading?<ListSkeleton/>:<><div className="subscriptions-table-scroll"><table><thead><tr><th><SelectAll visible={visible} selected={selected} onChange={setSelected}/></th><th>Cliente</th><th>Status</th><th>ID da assinatura</th><th>Produto</th><th><button onClick={()=>changeSort('createdAt')}>Data da criação <SortMark active={sort.key==='createdAt'} direction={sort.direction}/></button></th><th><button onClick={()=>changeSort('currentPeriodEnd')}>Data de vencimento <SortMark active={sort.key==='currentPeriodEnd'} direction={sort.direction}/></button></th></tr></thead><tbody>{visible.map(item=><tr key={item.id}><td><input type="checkbox" aria-label={`Selecionar assinatura ${item.id}`} checked={selected.includes(item.id)} onChange={()=>setSelected(current=>current.includes(item.id)?current.filter(id=>id!==item.id):[...current,item.id])}/></td><td><b>{item.customerName}</b>{item.customerEmail&&<small>{item.customerEmail}</small>}</td><td><StatusBadge status={item.status}/></td><td><code>{item.id}</code></td><td>{item.productName}</td><td>{date(item.createdAt)}</td><td>{date(item.currentPeriodEnd)}</td></tr>)}</tbody></table></div><div className="subscriptions-mobile-list">{visible.map(item=><SubscriptionCard item={item} selected={selected.includes(item.id)} toggle={()=>setSelected(current=>current.includes(item.id)?current.filter(id=>id!==item.id):[...current,item.id])} key={item.id}/>)}</div>{!visible.length&&<EmptyState/>}</>}</div>
  {!loading&&rows.length>pageSize&&<nav className="subscriptions-pagination" aria-label="Paginação de assinaturas"><span>{rows.length} resultados · Página {page} de {pages}</span><div><Button size="icon" aria-label="Página anterior" disabled={page===1} onClick={()=>setPage(value=>value-1)}><ChevronLeft/></Button><Button size="icon" aria-label="Próxima página" disabled={page===pages} onClick={()=>setPage(value=>value+1)}><ChevronRight/></Button></div></nav>}
 </div>
}

function MultiSelect({label,icon,options,selected,onChange}:{label:string;icon?:ReactNode;options:SubscriptionProduct[];selected:string[];onChange:(value:string[])=>void}){const summary=selected.length?`${selected.length} selecionado(s)`:'';return <details className="subscriptions-multiselect"><summary>{icon}{label}<span>{summary}</span><ChevronDown/></summary><div role="group" aria-label={`Filtrar por ${label}`}>{options.length?options.map(option=><label key={option.id}><input type="checkbox" checked={selected.includes(option.id)} onChange={()=>onChange(selected.includes(option.id)?selected.filter(id=>id!==option.id):[...selected,option.id])}/><span>{option.name}</span></label>):<p>Nenhuma opção disponível.</p>}{selected.length>0&&<button type="button" onClick={()=>onChange([])}>Limpar seleção</button>}</div></details>}
function SelectAll({visible,selected,onChange}:{visible:SubscriptionRecord[];selected:string[];onChange:(value:string[])=>void}){const ref=useRef<HTMLInputElement>(null),ids=visible.map(item=>item.id),checked=ids.length>0&&ids.every(id=>selected.includes(id)),partial=ids.some(id=>selected.includes(id))&&!checked;useEffect(()=>{if(ref.current)ref.current.indeterminate=partial},[partial]);return <input ref={ref} type="checkbox" aria-label="Selecionar todas as assinaturas visíveis" checked={checked} onChange={()=>onChange(checked?selected.filter(id=>!ids.includes(id)):Array.from(new Set([...selected,...ids])))}/>}
function SortMark({active,direction}:{active:boolean;direction:SortDirection}){return <span aria-hidden="true">{active?(direction==='asc'?'↑':'↓'):'↕'}</span>}
function StatusBadge({status}:{status:SubscriptionStatus}){return <span className={`subscriptions-status ${status}`}>{labels[status]}</span>}
function SubscriptionCard({item,selected,toggle}:{item:SubscriptionRecord;selected:boolean;toggle:()=>void}){return <article className="subscription-mobile-card"><header><label><input type="checkbox" aria-label={`Selecionar assinatura ${item.id}`} checked={selected} onChange={toggle}/><span><b>{item.customerName}</b><small>{item.customerEmail||item.id}</small></span></label><StatusBadge status={item.status}/></header><dl><div><dt>Produto</dt><dd>{item.productName}</dd></div><div><dt>Criação</dt><dd>{date(item.createdAt)}</dd></div><div><dt>Vencimento</dt><dd>{date(item.currentPeriodEnd)}</dd></div></dl></article>}
function EmptyState(){return <div className="subscriptions-empty"><Search/><h2>Nenhum resultado encontrado</h2><p>Ajuste seus critérios de busca ou redefina os filtros para obter mais resultados.</p></div>}
function ErrorState({onRetry}:{onRetry:()=>void}){return <div className="subscriptions-empty" role="alert"><Info/><h2>Não foi possível carregar as assinaturas</h2><p>Verifique sua conexão e tente novamente.</p><Button onClick={onRetry}>Tentar novamente</Button></div>}
function OverviewSkeleton(){return <div className="subscriptions-metric-grid"><div className="subscriptions-primary-card subscriptions-skeleton"><Skeleton/><Skeleton/><Skeleton/></div><div className="subscriptions-side-metrics">{[1,2,3].map(item=><div className="subscriptions-side-card subscriptions-skeleton" key={item}><Skeleton/><Skeleton/></div>)}</div></div>}
function ListSkeleton(){return <div className="subscriptions-list-skeleton">{Array.from({length:7},(_,index)=><div key={index}><Skeleton/><Skeleton/><Skeleton/><Skeleton/></div>)}</div>}
