import {useEffect,useRef,useState} from 'react'
import {useNavigate} from 'react-router-dom'
import {remainingMobileNavigation} from '../../config/navigation'

export function MobileMoreSheet({open,onClose}:{open:boolean;onClose:()=>void}){
 const navigate=useNavigate(),sheet=useRef<HTMLElement>(null),startY=useRef(0),[drag,setDrag]=useState(0)
 useEffect(()=>{if(!open)return;const previous=document.body.style.overflow;document.body.style.overflow='hidden';history.pushState({...history.state,mobileMore:true},'');const pop=()=>onClose(),key=(event:KeyboardEvent)=>{if(event.key==='Escape'){event.preventDefault();history.replaceState({...history.state,mobileMore:false},'');onClose()}};addEventListener('popstate',pop,{once:true});addEventListener('keydown',key);requestAnimationFrame(()=>sheet.current?.focus());return()=>{document.body.style.overflow=previous;removeEventListener('popstate',pop);removeEventListener('keydown',key)}},[open,onClose])
 if(!open)return null
 const close=()=>history.state?.mobileMore?history.back():onClose(),go=(path:string)=>{if(history.state?.mobileMore)history.replaceState({...history.state,mobileMore:false},'');onClose();navigate(path)}
 return <div className="mobile-more-layer"><button className="mobile-more-backdrop" aria-label="Fechar mais módulos" onClick={close}/><section ref={sheet} className="mobile-more-sheet" role="dialog" aria-modal="true" aria-labelledby="mobile-more-title" tabIndex={-1} style={{'--sheet-drag':`${drag}px`} as React.CSSProperties}><div className="mobile-more-handle" aria-hidden="true" onPointerDown={event=>{startY.current=event.clientY;setDrag(0);event.currentTarget.setPointerCapture(event.pointerId)}} onPointerMove={event=>{if(startY.current)setDrag(Math.max(0,event.clientY-startY.current))}} onPointerUp={()=>{if(drag>84)close();else setDrag(0);startY.current=0}}/><header><span>SPHEX PAY</span><h2 id="mobile-more-title">Mais módulos</h2><p>Acesse todas as áreas disponíveis da sua operação.</p></header><nav className="mobile-more-grid" aria-label="Outros módulos">{remainingMobileNavigation.map(item=><button key={item.id} aria-label={item.label} onClick={()=>go(item.path)}><item.icon/><span>{item.label}</span><small>{item.group}</small></button>)}</nav></section></div>
}
