import { Crown,RefreshCcw,Trophy,UserRound } from 'lucide-react'
import { competitionConfig,formatCompetitionMoney } from '../../config/competition'
import type { CompetitionStanding } from '../../services/competitionEngine'

const orderedPositions=[2,1,3]
const statusLabel=(row:CompetitionStanding)=>row.targetReachedAt?'Meta alcançada':row.auditStatus==='ineligible'?'Não elegível':'Participando'
const Avatar=({row}:{row?:CompetitionStanding})=><span className="competition-avatar">{row?.avatarUrl?<img src={row.avatarUrl} alt=""/>:<UserRound/>}</span>

export function CompetitionPodium({standings}:{standings:CompetitionStanding[]}){
 return <section className="competition-section"><header><span>PÓDIO</span><h2>Disputa pelas principais posições</h2></header><div className="competition-podium">{orderedPositions.map(position=>{const row=standings[position-1];return <article className={`podium-place podium-${position}`} key={position}>{position===1&&<Crown className="podium-crown"/>}<Avatar row={row}/><b>{row?.publicName||'Posição disponível'}</b><strong>{row?formatCompetitionMoney(row.eligibleRevenueCents):'—'}</strong><small>{row?`${Math.min(100,row.eligibleRevenueCents/competitionConfig.targetCents*100).toFixed(1)}% da meta`:'Aguardando participante elegível'}</small><span>{row?statusLabel(row):`${position}º lugar`}</span>{row?.targetReachedAt&&<time>{new Date(row.targetReachedAt).toLocaleString('pt-BR')}</time>}<i>{position}</i></article>})}</div></section>
}

export function CompetitionLeaderboard({standings,loading,error,realtime,updatedAt,onRefresh}:{standings:CompetitionStanding[];loading:boolean;error:string;realtime:string;updatedAt:string;onRefresh:()=>void}){
 return <section className="competition-section competition-ranking"><header><div><span>RANKING</span><h2>Classificação em tempo real</h2></div><div className={`competition-live ${realtime}`}><i/>{realtime==='live'?'Atualização ao vivo':realtime==='reconnecting'?'Reconectando':'Atualização manual'}{updatedAt&&<small>{new Date(updatedAt).toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'})}</small>}<button onClick={onRefresh} aria-label="Atualizar ranking"><RefreshCcw/></button></div></header>{loading?<div className="competition-loading" aria-label="Carregando ranking">{Array.from({length:4},(_,index)=><i key={index}/>)}</div>:error?<div className="competition-empty"><Trophy/><h3>Ranking temporariamente indisponível</h3><p>{error}</p><button className="btn" onClick={onRefresh}>Tentar novamente</button></div>:standings.length?<div className="competition-table-wrap"><table><thead><tr><th>Posição</th><th>Participante</th><th>Faturamento elegível</th><th>Vendas</th><th>Progresso</th><th>Status</th></tr></thead><tbody>{standings.map((row,index)=><tr key={row.userId}><td><b>#{index+1}</b></td><td><span className="leader-name"><Avatar row={row}/>{row.publicName}</span></td><td>{formatCompetitionMoney(row.eligibleRevenueCents)}</td><td>{row.eligibleSalesCount}</td><td>{Math.min(100,row.eligibleRevenueCents/competitionConfig.targetCents*100).toFixed(1)}%</td><td>{statusLabel(row)}</td></tr>)}</tbody></table></div>:<div className="competition-empty"><Trophy/><h3>O pódio está aberto</h3><p>Nenhum participante elegível foi registrado. As posições serão preenchidas somente por transações reais confirmadas.</p></div>}</section>
}
