import { BarChart3,ReceiptText,Target,TrendingUp } from 'lucide-react'
import { competitionConfig,formatCompetitionMoney,type CompetitionStatus } from '../../config/competition'
import type { CompetitionStanding } from '../../services/competitionEngine'

export function CompetitionUserProgress({row,position,status}:{row?:CompetitionStanding;position:number|null;status:CompetitionStatus}){
 const revenue=row?.eligibleRevenueCents||0,count=row?.eligibleSalesCount||0,remaining=Math.max(0,competitionConfig.targetCents-revenue),percent=revenue/competitionConfig.targetCents*100,excess=Math.max(0,revenue-competitionConfig.targetCents)
 const message=status==='upcoming'?'A competição ainda não começou.':status==='active'?row?.targetReachedAt?'Meta alcançada. Resultado em validação.':percent>=80?'Você está próximo da meta principal.':'Somente vendas reais elegíveis contam para o ranking.':status==='audit'?'Resultados em auditoria administrativa.':'A campanha foi encerrada.'
 return <section className="competition-section competition-performance" id="meu-desempenho"><header><span>MEU DESEMPENHO</span><h2>Sua evolução na competição</h2><p>{message}</p></header><div className="competition-performance-grid"><article><TrophyIcon/><span>Posição atual</span><b>{position?`#${position}`:'—'}</b></article><article><BarChart3/><span>Faturamento elegível</span><b>{formatCompetitionMoney(revenue)}</b></article><article><Target/><span>Valor restante</span><b>{formatCompetitionMoney(remaining)}</b></article><article><ReceiptText/><span>Vendas elegíveis</span><b>{count}</b></article><article><TrendingUp/><span>Ticket médio</span><b>{formatCompetitionMoney(count?Math.round(revenue/count):0)}</b></article><article><ReceiptText/><span>Última venda elegível</span><b>{row?.lastEligibleSaleAt?new Date(row.lastEligibleSaleAt).toLocaleDateString('pt-BR'):'—'}</b></article></div><div className="competition-progress"><div><span>Progresso para {formatCompetitionMoney(competitionConfig.targetCents)}</span><b>{Math.min(100,percent).toFixed(1)}%</b></div><i><em style={{width:`${Math.min(100,percent)}%`}}/></i>{excess>0&&<small>Excedente: {formatCompetitionMoney(excess)}</small>}</div></section>
}
function TrophyIcon(){return <Target/>}
