import { useCallback,useEffect,useRef,useState } from 'react'
import { audioManager } from '../services/audioManager'
export type MicrophoneStatus='off'|'requesting'|'on'|'listening'|'processing'|'denied'|'unavailable'|'error'
export function useMicrophone(){const [status,setStatus]=useState<MicrophoneStatus>('off'),[level,setLevel]=useState(0),stream=useRef<MediaStream|undefined>(undefined),frame=useRef<number|undefined>(undefined),mounted=useRef(true)
 const release=useCallback((update=true)=>{if(frame.current)cancelAnimationFrame(frame.current);frame.current=undefined;stream.current?.getTracks().forEach(track=>{track.onended=null;track.stop()});stream.current=undefined;if(update&&mounted.current){setLevel(0);setStatus('off')}},[])
 const stop=useCallback(()=>release(true),[release])
 const start=useCallback(async()=>{if(!navigator.mediaDevices?.getUserMedia){setStatus('unavailable');return false}release(false);setStatus('requesting');try{const sharedContextPromise=audioManager.getContextForUserGesture(),media=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:true,channelCount:1}});if(!mounted.current){media.getTracks().forEach(track=>track.stop());return false}stream.current=media;const audioTracks=media.getAudioTracks?.()||media.getTracks().filter(track=>track.kind==='audio'||!track.kind);audioTracks.forEach(track=>{track.onended=()=>release(true)});setStatus('listening');try{const audio=await sharedContextPromise;if(!audio)throw new Error('AudioContext indisponível');const analyser=audio.createAnalyser();analyser.fftSize=256;analyser.smoothingTimeConstant=.72;audio.createMediaStreamSource(media).connect(analyser);const data=new Uint8Array(analyser.frequencyBinCount);const sample=()=>{if(!mounted.current)return;analyser.getByteTimeDomainData(data);let sum=0;for(const value of data){const normalized=(value-128)/128;sum+=normalized*normalized}setLevel(Math.min(1,Math.sqrt(sum/data.length)*3.4));frame.current=requestAnimationFrame(sample)};sample()}catch{/* O indicador permanece funcional sem análise visual de volume. */}return true}catch(error){if(!mounted.current)return false;const name=(error as DOMException).name;setStatus(name==='NotAllowedError'||name==='PermissionDeniedError'?'denied':name==='NotFoundError'?'unavailable':'error');return false}},[release])
 useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;release(false)}},[release]);return{status,level,start,stop,setStatus}
}
