import { useEffect, useRef } from 'react'
import { useDemoStore } from '../store/useDemoStore'
import { realtimeEventsService } from '../services/realtimeEventsService'
import { notificationService } from '../services/notificationService'
import { audioService } from '../services/audioService'
import { notificationQueueService } from '../services/notificationQueueService'
import { saleNotification } from '../services/notificationEventService'
import { commercePayloadFromSale } from '../lib/notificationCatalog'
import { notificationToastService } from '../services/notificationToastService'

export function useRealtimeSales(){
 const active=useDemoStore(s=>s.preferences.sales.automaticUpdates),frequency=useDemoStore(s=>s.preferences.sales.updateFrequency),addSale=useDemoStore(s=>s.addSale),addNotification=useDemoStore(s=>s.addNotification),deleteNotification=useDemoStore(s=>s.deleteNotification),prefs=useDemoStore(s=>s.preferences)
 const prefsRef=useRef(prefs);prefsRef.current=prefs
 useEffect(()=>{if(!active){audioService.dispose();notificationService.dispose();notificationQueueService.clear();return}const pump=()=>notificationQueueService.drain(prefsRef.current.notifications.frequency).forEach(addNotification),pumpTimer=window.setInterval(pump,100),unsubscribe=realtimeEventsService.subscribe(sale=>{addSale(sale);const event=saleNotification(sale),payload=commercePayloadFromSale(sale);deleteNotification(event.id);notificationQueueService.enqueue(event);pump();const current=prefsRef.current,notifications=current.notifications,quiet=notifications.doNotDisturb||(notifications.quietHours&&inQuietHours(notifications.quietFrom,notifications.quietTo)),soundOn=current.sales.saleSound||notifications.sound,allowed=eventAllowed(payload.type,notifications);if(!quiet&&allowed&&notifications.internal)notificationToastService.emit(payload);if(!quiet&&allowed&&notifications.device&&document.visibilityState!=='visible')void notificationService.showCommerce(payload);if(!quiet&&allowed&&soundOn){if(sale.status==='Aprovado')void audioService.playSale(notifications.soundVolume,notifications.soundStyle,sale.id);else if(sale.status==='Recusado')void audioService.playNotification('error',notifications.soundVolume,sale.id);else if(sale.method==='Pix'&&sale.status==='Pendente')void audioService.playNotification('alert',notifications.soundVolume,sale.id)}if(sale.status==='Aprovado'&&!quiet&&allowed&&notifications.vibration)audioService.vibrate()},frequency);return()=>{unsubscribe();window.clearInterval(pumpTimer);notificationQueueService.clear();audioService.dispose();notificationService.dispose()}},[active,frequency,addSale,addNotification,deleteNotification])
}
function inQuietHours(from:string,to:string){const now=new Date(),value=now.getHours()*60+now.getMinutes(),[fromHour,fromMinute]=from.split(':').map(Number),[toHour,toMinute]=to.split(':').map(Number),start=fromHour*60+fromMinute,end=toHour*60+toMinute;return start<=end?value>=start&&value<end:value>=start||value<end}
function eventAllowed(type:import('../types').CommerceNotificationType,prefs:import('../types').NotificationPreferences){if(type==='sale_approved')return prefs.saleApproved!==false&&prefs.sales;if(type==='pix_generated')return prefs.pixGenerated!==false&&prefs.sales;if(type==='credit_card_approved')return prefs.cardApproved!==false&&prefs.sales;if(type==='subscription_approved'||type==='subscription_renewed')return prefs.subscriptionEvents!==false&&prefs.subscriptions;if(type==='withdrawal_sent')return prefs.withdrawalEvents!==false&&prefs.withdrawals;return prefs.sales}
