import { useCallback,useEffect,useRef,useState } from 'react'
interface RecognitionResult {isFinal:boolean;0:{transcript:string;confidence?:number}}
interface RecognitionEvent extends Event {results:ArrayLike<RecognitionResult>;resultIndex:number}
interface RecognitionErrorEvent extends Event {error:string;message?:string}
interface Recognition {lang:string;interimResults:boolean;continuous:boolean;maxAlternatives:number;start():void;stop():void;abort():void;onstart:(()=>void)|null;onspeechstart:(()=>void)|null;onspeechend:(()=>void)|null;onresult:((e:RecognitionEvent)=>void)|null;onend:(()=>void)|null;onerror:((e:RecognitionErrorEvent)=>void)|null}
type RecognitionConstructor=new()=>Recognition
export type RecognitionStatus='idle'|'starting'|'listening'|'recognizing'|'ended'|'denied'|'error'|'unsupported'
export function useSpeechRecognition(language:string,onText:(text:string,isFinal:boolean)=>void){const recognition=useRef<Recognition|undefined>(undefined),finalText=useRef(''),manualStop=useRef(false),[status,setStatus]=useState<RecognitionStatus>('idle'),[error,setError]=useState('');const api=window as unknown as {SpeechRecognition?:RecognitionConstructor;webkitSpeechRecognition?:RecognitionConstructor},supported=Boolean(api.SpeechRecognition||api.webkitSpeechRecognition)
 const stop=useCallback(()=>{manualStop.current=true;try{recognition.current?.stop()}catch{/* already stopped */}recognition.current=undefined;finalText.current='';setStatus('idle')},[])
 const start=useCallback(()=>{const Ctor=api.SpeechRecognition||api.webkitSpeechRecognition;if(!Ctor){setStatus('unsupported');return false}if(recognition.current)stop();const instance=new Ctor();manualStop.current=false;finalText.current='';setError('');setStatus('starting');instance.lang=language;instance.interimResults=true;instance.continuous=true;instance.maxAlternatives=1;instance.onstart=()=>setStatus('listening');instance.onspeechstart=()=>setStatus('recognizing');instance.onspeechend=()=>setStatus('listening');instance.onresult=event=>{let interim='';for(let index=event.resultIndex;index<event.results.length;index++){const transcript=event.results[index][0].transcript;if(event.results[index].isFinal)finalText.current+=`${transcript} `;else interim+=transcript}const text=`${finalText.current}${interim}`.trim();if(text)onText(text,!interim&&Boolean(finalText.current.trim()))};instance.onerror=event=>{const denied=event.error==='not-allowed'||event.error==='service-not-allowed';setStatus(denied?'denied':'error');setError(denied?'Permissão de reconhecimento de voz negada.':`Não foi possível reconhecer a fala (${event.error}).`)};instance.onend=()=>{recognition.current=undefined;if(!manualStop.current)setStatus(current=>current==='denied'||current==='error'?current:'ended')};try{instance.start();recognition.current=instance;return true}catch{setStatus('error');setError('Não foi possível iniciar o reconhecimento de voz.');return false}},[api.SpeechRecognition,api.webkitSpeechRecognition,language,onText,stop])
 useEffect(()=>stop,[stop]);return{supported,status,error,start,stop}
}
