import { useState } from 'react'
import { Bell,Building2,ChevronDown,LayoutDashboard,Menu,Plug,RadioTower,Save,Settings as SettingsIcon,Shield,SlidersHorizontal,UserRound,WalletCards,X } from 'lucide-react'
import { Card } from '../components/ui'
import { SphexPayLogo } from '../components/branding/SphexPayLogo'

const sections=[['Perfil',UserRound],['Empresa',Building2],['Notificações',Bell],['Preferências',SlidersHorizontal],['Aparência',SettingsIcon],['Segurança',Shield],['Integrações',Plug],['Dados bancários',WalletCards]] as const
const nav=[['Visão geral',LayoutDashboard],['Vendas ao vivo',RadioTower],['Configurações',SettingsIcon]] as const
export default function DevSettingsPreview(){
 const [mobileOpen,setMobileOpen]=useState(false),[tab,setTab]=useState('Perfil')
 return <div className="dev-settings-preview" data-preview-theme="dark"><aside className={`dev-settings-sidebar ${mobileOpen?'open':''}`}><div className="dev-settings-brand"><SphexPayLogo showName={mobileOpen} priority/><button className="btn btn-ghost icon-btn dev-settings-close" onClick={()=>setMobileOpen(false)} aria-label="Fechar menu"><X/></button></div><nav>{nav.map(([label,Icon],index)=><button type="button" key={label} className={`dev-settings-nav-item ${index===2?'active':''}`}><Icon/><span>{label}</span></button>)}</nav><small className="dev-settings-user"><i/> Preview local</small></aside>{mobileOpen&&<button type="button" className="dev-settings-backdrop" onClick={()=>setMobileOpen(false)} aria-label="Fechar menu"/>}<div className="dev-settings-main"><header className="dev-settings-topbar"><button className="btn btn-ghost icon-btn dev-settings-menu" onClick={()=>setMobileOpen(true)} aria-label="Abrir menu"><Menu/></button><div><span>MODO DE PRÉ-VISUALIZAÇÃO</span><h1>Configurações</h1><p>Preferências demonstrativas, sem alterações persistentes.</p></div><span className="dev-settings-live"><i/> Ambiente local</span></header><main className="dev-settings-content"><div className="dev-settings-notice">Nenhum dado real é consultado ou salvo nesta prévia. Chaves, webhooks e permissões permanecem protegidos.</div><section className="dev-settings-heading"><div><span>WORKSPACE</span><h2>Seu espaço, do seu jeito</h2><p>Organize perfil, preferências e segurança em um só lugar.</p></div><span className="dev-settings-status"><i/> Prévia protegida</span></section><div className="dev-settings-layout"><Card className="dev-settings-sections"><div className="dev-settings-sections-head"><span>CONFIGURAÇÕES</span><ChevronDown/></div>{sections.map(([label,Icon])=><button type="button" key={label} className={tab===label?'active':''} onClick={()=>setTab(label)}><Icon/><span>{label}</span><ChevronDown/></button>)}</Card><Card className="dev-settings-panel"><header><div><span>SEÇÃO ATUAL</span><h2>{tab}</h2><p>Valores demonstrativos para validação visual.</p></div><button className="btn btn-primary" disabled title="Disponível somente no ambiente autenticado"><Save/> Salvar alterações</button></header><SettingsContent tab={tab}/></Card></div></main></div></div>
}
function SettingsContent({tab}:{tab:string}){if(tab==='Perfil')return <><div className="dev-settings-profile"><div className="dev-settings-avatar">SP</div><div><strong>Perfil demonstrativo</strong><p>As informações pessoais não são persistidas nesta rota.</p></div><button className="btn" disabled>Alterar foto</button></div><div className="dev-settings-form-grid"><Field label="Nome" value="Operação demonstrativa"/><Field label="E-mail" value="preview@example.com"/><Field label="Telefone" value="+55 (11) 0000-0000"/><Field label="Idioma" value="Português (Brasil)"/></div></>;if(tab==='Empresa')return <div className="dev-settings-form-grid"><Field label="Nome da empresa" value="SphexPay Workspace"/><Field label="Documento" value="00.000.000/0000-00"/><Field label="País" value="Brasil"/><Field label="Moeda principal" value="BRL — Real brasileiro"/></div>;if(tab==='Notificações')return <div className="dev-settings-options"><Toggle label="Notificações internas" checked/><Toggle label="Alertas de novas vendas" checked/><Toggle label="Resumo diário" checked={false}/><Toggle label="Som de alertas" checked={false}/></div>;if(tab==='Preferências')return <div className="dev-settings-options"><Toggle label="Atualizações automáticas locais" checked/><Toggle label="Mostrar métricas compactas" checked/><Field label="Itens recentes no painel" value="6"/></div>;if(tab==='Aparência')return <div className="dev-settings-options"><Toggle label="Tema acompanha o sistema" checked/><div className="dev-settings-theme"><button className="active">Claro</button><button>Escuro</button><button>Sistema</button></div></div>;if(tab==='Segurança')return <><div className="dev-settings-options"><Toggle label="Autenticação em duas etapas" checked/><Toggle label="Alertas de novo acesso" checked/><Toggle label="Bloqueio por inatividade" checked={false}/></div><div className="dev-settings-session"><strong>Sessões e dispositivos</strong><span>MacBook Pro · sessão demonstrativa atual</span><button className="btn" disabled>Encerrar sessão</button></div></>;if(tab==='Integrações')return <div className="dev-settings-integrations">{['API de pagamentos autorizada','Webhooks','ERP / Contabilidade','CRM'].map(name=><div key={name}><Plug/><span><strong>{name}</strong><small>Não configurada nesta prévia</small></span><button className="btn" disabled>Disponível após autenticação</button></div>)}</div>;return <div className="dev-settings-bank"><WalletCards/><div><strong>Conta bancária protegida</strong><p>Dados mascarados e indisponíveis na prévia.</p></div></div>}
function Field({label,value}:{label:string;value:string}){return <label><span>{label}</span><input value={value} readOnly/></label>}
function Toggle({label,checked}:{label:string;checked:boolean}){return <label className="dev-settings-toggle"><span>{label}</span><input type="checkbox" checked={checked} readOnly/><i/></label>}
