import { useEffect,useMemo,useRef,useState } from 'react'
import { ArrowDownUp,CalendarDays,ChevronLeft,ChevronRight,Eye,Filter,LayoutDashboard,Menu,Package,RadioTower,Search,Settings,Users,WalletCards,X } from 'lucide-react'
import { Card } from '../components/ui'
import { SphexPayLogo } from '../components/branding/SphexPayLogo'
import { formatCents } from '../lib/currencyFormat'
import type { FinancialTransaction } from '../lib/dashboardFinance'

const labels={approved:'Aprovada',pending:'Pendente',declined:'Recusada',refunded:'Reembolsada',chargeback:'Chargeback'} as const
const demoRows:FinancialTransaction[]=[
 {transactionId:'preview-tx-1001',buyerName:'Cliente demonstração',productName:'Plano Scale',paymentMethod:'Pix',status:'approved',amountCents:129700,feeCents:6485,netAmountCents:123215,currency:'BRL',occurredAt:'2026-08-06T16:42:00-03:00',demo:true},
 {transactionId:'preview-tx-1002',buyerName:'Conta de teste',productName:'Oferta Pro',paymentMethod:'Cartão',status:'approved',amountCents:89700,feeCents:4485,netAmountCents:85215,currency:'BRL',occurredAt:'2026-08-06T16:18:00-03:00',demo:true},
 {transactionId:'preview-tx-1003',buyerName:'Operação fictícia',productName:'Assinatura Plus',paymentMethod:'Pix',status:'pending',amountCents:59700,feeCents:2985,netAmountCents:0,currency:'BRL',occurredAt:'2026-08-06T15:51:00-03:00',demo:true},
 {transactionId:'preview-tx-1004',buyerName:'Cliente demonstração',productName:'Checkout Express',paymentMethod:'Cartão',status:'declined',amountCents:43800,feeCents:2190,netAmountCents:0,currency:'BRL',occurredAt:'2026-08-06T15:22:00-03:00',demo:true},
 {transactionId:'preview-tx-1005',buyerName:'Conta de teste',productName:'Plano Growth',paymentMethod:'Boleto',status:'refunded',amountCents:182400,feeCents:9120,netAmountCents:0,currency:'BRL',occurredAt:'2026-08-06T14:57:00-03:00',demo:true},
 {transactionId:'preview-tx-1006',buyerName:'Cliente demonstração',productName:'Oferta Start',paymentMethod:'Pix',status:'approved',amountCents:74200,feeCents:3710,netAmountCents:70490,currency:'BRL',occurredAt:'2026-08-06T14:21:00-03:00',demo:true},
]
const nav=[['Visão geral',LayoutDashboard],['Vendas ao vivo',RadioTower],['Transações',ArrowDownUp],['Produtos',Package],['Clientes',Users],['Financeiro',WalletCards],['Configurações',Settings]] as const

export default function DevTransactionsPreview(){
 const [mobileOpen,setMobileOpen]=useState(false),[query,setQuery]=useState(''),[status,setStatus]=useState('all'),[page,setPage]=useState(1),[detail,setDetail]=useState<FinancialTransaction|null>(null),trigger=useRef<HTMLButtonElement>(null)
 const filtered=useMemo(()=>demoRows.filter(row=>`${row.transactionId} ${row.productName} ${row.buyerName||''}`.toLowerCase().includes(query.toLowerCase())&&(status==='all'||row.status===status)),[query,status]),rows=filtered.slice((page-1)*4,page*4),pages=Math.max(1,Math.ceil(filtered.length/4))
 useEffect(()=>{if(!detail)return;const close=(event:KeyboardEvent)=>{if(event.key==='Escape')setDetail(null)};window.addEventListener('keydown',close);return()=>window.removeEventListener('keydown',close)},[detail])
 const openDetail=(row:FinancialTransaction,button:HTMLButtonElement)=>{trigger.current=button;setDetail(row)}
 const closeDetail=()=>{setDetail(null);window.setTimeout(()=>trigger.current?.focus(),0)}
 return <div className="dev-transactions-preview" data-preview-theme="dark">
  <aside className={`dev-transactions-sidebar ${mobileOpen?'open':''}`}><div className="dev-transactions-brand"><SphexPayLogo showName={mobileOpen} priority/><button className="btn btn-ghost icon-btn dev-transactions-close" onClick={()=>setMobileOpen(false)} aria-label="Fechar menu"><X/></button></div><nav>{nav.map(([label,Icon],index)=><button type="button" key={label} className={`dev-transactions-nav-item ${index===2?'active':''}`}><Icon/><span>{label}</span></button>)}</nav><small className="dev-transactions-user"><i/> Preview local</small></aside>
  {mobileOpen&&<button type="button" className="dev-transactions-backdrop" onClick={()=>setMobileOpen(false)} aria-label="Fechar menu"/>}
  <div className="dev-transactions-main"><header className="dev-transactions-topbar"><button className="btn btn-ghost icon-btn dev-transactions-menu" onClick={()=>setMobileOpen(true)} aria-label="Abrir menu"><Menu/></button><div><span>MODO DE PRÉ-VISUALIZAÇÃO</span><h1>Transações</h1><p>Auditoria visual de movimentações demonstrativas.</p></div><span className="dev-transactions-live"><i/> Ambiente local</span></header>
   <main className="dev-transactions-content"><div className="dev-transactions-notice">Os dados abaixo são fictícios. Ações financeiras permanecem desativadas nesta prévia.</div><section className="dev-transactions-heading"><div><span>OPERAÇÃO</span><h2>Movimentações recentes</h2><p>Consulte status, valores e detalhes em uma visão compacta.</p></div><div className="dev-transactions-date"><CalendarDays/> Hoje <ChevronRight/></div></section><section className="dev-transactions-summary"><Summary label="Total processado" value={formatCents(293600,'BRL')} detail="3 aprovadas"/><Summary label="Pendentes" value="1" detail="aguardando análise"/><Summary label="Recusadas" value="1" detail="sem ação necessária"/><Summary label="Registros" value={String(filtered.length)} detail="nesta prévia"/></section>
    <Card className="dev-transactions-table-card"><div className="dev-transactions-toolbar"><label className="dev-transactions-search"><Search/><span className="sr-only">Buscar transações</span><input value={query} onChange={event=>{setQuery(event.target.value);setPage(1)}} placeholder="Cliente, produto ou identificador..."/>{query&&<button type="button" onClick={()=>setQuery('')} aria-label="Limpar busca"><X/></button>}</label><div className="dev-transactions-filter"><Filter/><select aria-label="Filtrar por status" value={status} onChange={event=>{setStatus(event.target.value);setPage(1)}}><option value="all">Todos os status</option>{Object.entries(labels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></div></div><div className="dev-transactions-table-wrap"><table><caption className="sr-only">Transações demonstrativas</caption><thead><tr><th>Cliente</th><th>Identificador / data</th><th>Produto</th><th>Método</th><th>Status</th><th>Valor</th><th>Líquido</th><th><span className="sr-only">Ações</span></th></tr></thead><tbody>{rows.map(row=><tr key={row.transactionId}><td><strong>{row.buyerName}</strong><small>Conta demonstrativa</small></td><td><code>{row.transactionId}</code><small>{new Date(row.occurredAt).toLocaleString('pt-BR',{timeZone:'America/Sao_Paulo'})}</small></td><td>{row.productName}</td><td>{row.paymentMethod}</td><td><Status value={row.status}/></td><td className="money">{formatCents(row.amountCents,row.currency)}</td><td className="money">{formatCents(row.netAmountCents??0,row.currency)}</td><td><button type="button" className="btn btn-ghost icon-btn" aria-label={`Ver detalhes de ${row.transactionId}`} onClick={event=>openDetail(row,event.currentTarget)}><Eye/></button></td></tr>)}</tbody></table>{!rows.length&&<div className="dev-transactions-empty">Nenhum registro corresponde aos filtros atuais.</div>}</div><footer className="dev-transactions-pagination"><span>{filtered.length} registros · Página {page} de {pages}</span><div><button className="btn btn-ghost icon-btn" disabled={page===1} onClick={()=>setPage(value=>value-1)} aria-label="Página anterior"><ChevronLeft/></button><button className="btn btn-ghost icon-btn" disabled={page===pages} onClick={()=>setPage(value=>value+1)} aria-label="Próxima página"><ChevronRight/></button></div></footer></Card>
   </main></div>
  {detail&&<div className="dev-transactions-drawer-backdrop" onMouseDown={closeDetail}><aside className="dev-transactions-drawer" role="dialog" aria-modal="true" aria-labelledby="preview-transaction-title" onMouseDown={event=>event.stopPropagation()}><header><div><span>DETALHE DEMONSTRATIVO</span><h2 id="preview-transaction-title">{detail.transactionId}</h2></div><button className="btn btn-ghost icon-btn" onClick={closeDetail} aria-label="Fechar detalhes"><X/></button></header><div className="dev-transactions-drawer-status"><Status value={detail.status}/><strong>{formatCents(detail.amountCents,detail.currency)}</strong></div><dl><Detail label="Cliente" value={detail.buyerName||'—'}/><Detail label="Produto" value={detail.productName}/><Detail label="Método" value={detail.paymentMethod}/><Detail label="Data" value={new Date(detail.occurredAt).toLocaleString('pt-BR',{timeZone:'America/Sao_Paulo'})}/><Detail label="Taxas" value={formatCents(detail.feeCents,detail.currency)}/><Detail label="Valor líquido" value={formatCents(detail.netAmountCents??0,detail.currency)}/></dl><div className="dev-transactions-disabled">Reembolso, estorno, captura e demais ações financeiras estão desativados no preview.</div></aside></div>}
 </div>
}
function Summary({label,value,detail}:{label:string;value:string;detail:string}){return <Card className="dev-transactions-summary-card"><span>{label}</span><strong>{value}</strong><small>{detail}</small></Card>}
function Status({value}:{value:FinancialTransaction['status']}){return <span className={`dev-transaction-status ${value}`}><i/>{labels[value]}</span>}
function Detail({label,value}:{label:string;value:string}){return <div><dt>{label}</dt><dd>{value}</dd></div>}
