import { useMemo } from 'react'
import { NavLink,Outlet,useLocation } from 'react-router-dom'
import { CalendarDays,Download,Landmark,LockKeyhole,WalletCards } from 'lucide-react'
import { Card,PageTitle,StatusBadge } from '../components/ui'
import { EditableValue } from '../components/common/EditableValue'
import { PeriodSelector } from '../components/common/PeriodSelector'
import { filterSales } from '../services/analyticsService'
import { downloadCsv,money,shortDate } from '../lib/utils'
import { useDemoStore } from '../store/useDemoStore'
import { withdrawalMoney } from '../services/withdrawalService'
export default function FinancialHub(){
 const {pathname}=useLocation(),withdrawalsActive=pathname.endsWith('/saques')
 return <div className="financial-module page-enter"><PageTitle title="Financeiro" subtitle="Saldos, repasses, extrato e saques da operação."/><nav className="financial-module-tabs" aria-label="Áreas do Financeiro" role="tablist"><NavLink end to="/app/financeiro" role="tab" aria-selected={!withdrawalsActive}><Landmark/> Visão geral</NavLink><NavLink to="/app/financeiro/saques" role="tab" aria-selected={withdrawalsActive}><WalletCards/> Saques</NavLink></nav><Outlet/></div>
}

export function FinancialOverview(){const s=useDemoStore(),sales=useMemo(()=>filterSales(s.sales,s.period),[s.sales,s.period]),ledger=useMemo(()=>[...s.withdrawals.map(x=>({date:x.date,description:x.status==='Concluído'?'Saque concluído':'Saque solicitado',type:'Débito',value:-x.amount,formatted:`- ${withdrawalMoney(Math.round(x.amount*100),x.currency||'BRL')}`,status:x.status})),...sales.filter(x=>x.status==='Aprovado').map(x=>({date:x.date,description:`Venda · ${x.product}`,type:'Entrada',value:x.amount-x.fee,formatted:money(x.amount-x.fee),status:'Concluído'}))].sort((a,b)=>b.date.localeCompare(a.date)),[s.withdrawals,sales]),cards=[['Disponível',s.available,WalletCards,'available'],['Saldo futuro',s.pending,CalendarDays,'pending'],['Valores bloqueados',2840,LockKeyhole,''],['Taxas no período',sales.reduce((a,x)=>a+x.fee,0),Landmark,'']] as const;return <section className="financial-page" aria-label="Visão geral financeira"><div className="financial-overview-actions"><PeriodSelector/><button className="btn" onClick={()=>downloadCsv('extrato.csv',ledger)}><Download size={16}/> Exportar extrato</button></div><div className="financial-balance-grid grid grid-cols-2 lg:grid-cols-4 gap-3 mb-5">{cards.map(([label,value,Icon,key])=><Card className="financial-balance-card p-5" key={label}><Icon size={19} className="orange mb-4"/><span className="label">{label}</span><b className="text-xl financial-money">{money(value)}</b>{key==='pending'&&<EditableValue label={label} value={value} currency onSave={next=>s.updateMetrics({pending:next})}/>}</Card>)}</div><Card className="financial-ledger-card"><div className="p-5 border-b border-[var(--line)]"><b>Histórico financeiro</b></div><div className="table-wrap"><table className="table"><thead><tr><th>Data</th><th>Descrição</th><th>Tipo</th><th>Status</th><th>Valor líquido</th></tr></thead><tbody>{ledger.map((x,i)=><tr key={`${x.date}-${i}`}><td>{shortDate(x.date)}</td><td>{x.description}</td><td>{x.type}</td><td><StatusBadge status={x.status}/></td><td className={`font-bold financial-money ${x.value<0?'text-red-500':'text-emerald-600'}`}>{x.formatted}</td></tr>)}</tbody></table></div></Card></section>}
