import { useMemo } from 'react'
import { CalendarDays,Download,Landmark,LockKeyhole,WalletCards } from 'lucide-react'
import { Card,PageTitle,StatusBadge } from '../components/ui'
import { EditableValue } from '../components/common/EditableValue'
import { PeriodSelector } from '../components/common/PeriodSelector'
import { filterSales } from '../services/analyticsService'
import { downloadCsv,money,shortDate } from '../lib/utils'
import { useDemoStore } from '../store/useDemoStore'
export default function FinancialHub(){const s=useDemoStore(),sales=useMemo(()=>filterSales(s.sales,s.period),[s.sales,s.period]),ledger=useMemo(()=>[...s.withdrawals.map(x=>({date:x.date,description:'Saque',type:'Saída',value:-x.amount,status:x.status})),...sales.filter(x=>x.status==='Aprovado').map(x=>({date:x.date,description:`Venda · ${x.product}`,type:'Entrada',value:x.amount-x.fee,status:'Concluído'}))].sort((a,b)=>b.date.localeCompare(a.date)),[s.withdrawals,sales]),cards=[['Disponível',s.available,WalletCards,'available'],['Saldo futuro',s.pending,CalendarDays,'pending'],['Valores bloqueados',2840,LockKeyhole,''],['Taxas no período',sales.reduce((a,x)=>a+x.fee,0),Landmark,'']] as const;return <div className="page-enter"><PageTitle title="Financeiro" subtitle="Saldos, repasses e extrato da operação." action={<div className="flex gap-2"><PeriodSelector/><button className="btn" onClick={()=>downloadCsv('extrato.csv',ledger)}><Download size={16}/> Exportar extrato</button></div>}/><div className="grid grid-cols-2 lg:grid-cols-4 gap-3 mb-5">{cards.map(([label,value,Icon,key])=><Card className="p-5" key={label}><Icon size={19} className="orange mb-4"/><span className="label">{label}</span><b className="text-xl">{money(value)}</b>{key&&<EditableValue label={label} value={value} currency onSave={next=>s.updateMetrics(key==='available'?{available:next}:{pending:next})}/>}</Card>)}</div><Card><div className="p-5 border-b border-[var(--line)]"><b>Histórico financeiro</b></div><div className="table-wrap"><table className="table"><thead><tr><th>Data</th><th>Descrição</th><th>Tipo</th><th>Status</th><th>Valor líquido</th></tr></thead><tbody>{ledger.map((x,i)=><tr key={`${x.date}-${i}`}><td>{shortDate(x.date)}</td><td>{x.description}</td><td>{x.type}</td><td><StatusBadge status={x.status}/></td><td className={`font-bold ${x.value<0?'text-red-500':'text-emerald-600'}`}>{money(x.value)}</td></tr>)}</tbody></table></div></Card></div>}
