/* eslint-disable @typescript-eslint/no-unused-vars */
import { Activity,Check,ChevronRight,Clipboard,Code2,Copy,ExternalLink,Globe,KeyRound,Link2,MoreHorizontal,Plus,Send,Settings2,ShieldCheck,Trash2,Webhook,Wifi } from 'lucide-react'
import { useState } from 'react'
import { Card,PageTitle,StatusBadge } from '../components/ui'

type Tab='Apps'|'Webhooks'|'Sphex API'
type AppItem={name:string;description:string;mark:string;color:string;connected:boolean}
const appSeeds:[string,string,string,string,boolean][]=[['Hotmart','Venda e afiliados em um só lugar','H','#f97316',true],['Cakto','Checkout e produtos digitais','C','#111827',false],['UTMify','Atribuição e performance','U','#7c3aed',true],['Page.me','Conversas que convertem','P','#0ea5e9',false],['Google Sheets','Dados organizados em tempo real','G','#16a34a',false],['Zapier','Automatize suas rotinas','Z','#f59e0b',false],['Slack','Alertas para o seu time','S','#e11d48',false],['Discord','Comunidade e operações','D','#5865f2',false],['WhatsApp API','Comunicação direta com clientes','W','#16a34a',false],['Telegram','Alertas e automações rápidas','T','#229ed9',false]]
const initialApps:AppItem[]=appSeeds.map(([name,description,mark,color,connected])=>({name,description,mark,color,connected}))
const webhookEvents=['venda_aprovada','pix_gerado','boleto_gerado','cartao_aprovado','assinatura_aprovada','saque_solicitado','saque_realizado']
const initialWebhooks=[{id:'wh_01',name:'Operação principal',url:'https://hooks.exemplo.com/sphexpay',events:['venda_aprovada','pix_gerado'],active:true,created:'Hoje, 09:42',last:'200 · há 4 min'}]
const keys={public:'spx_pub_demo_8f92••••••••••••e42a',private:'spx_sec_demo_••••••••••••••••91b7'}
export default function Integrations(){const [tab,setTab]=useState<Tab>('Apps'),[apps,setApps]=useState(initialApps),[webhooks,setWebhooks]=useState(initialWebhooks),[showWebhook,setShowWebhook]=useState(false),[copied,setCopied]=useState(''),[apiEnvironment,setApiEnvironment]=useState('Produção')
 const connected=apps.filter(item=>item.connected).length,copy=async(value:string,label:string)=>{try{await navigator.clipboard?.writeText(value)}catch{/* O botão continua informando o estado local. */}setCopied(label);window.setTimeout(()=>setCopied(''),1800)}
 const toggleApp=(name:string)=>setApps(items=>items.map(item=>item.name===name?{...item,connected:!item.connected}:item))
 return <div className="page-enter integrations-page"><PageTitle title="Integrações" subtitle="Conecte a SphexPay ao ecossistema que move a sua operação." action={<button className="btn btn-primary" onClick={()=>setTab('Apps')}><Plus size={16}/> Conectar app</button>}/><div className="integrations-overview"><Card><span>Integrações ativas</span><strong>{connected}</strong><small><Wifi size={12}/> Conectadas agora</small></Card><Card><span>Webhooks ativos</span><strong>{webhooks.filter(item=>item.active).length}</strong><small><Webhook size={12}/> Entrega monitorada</small></Card><Card><span>Status da API</span><strong className="integration-status"><i/> Operacional</strong><small><Activity size={12}/> Última sincronização há 2 min</small></Card><Card><span>Ambiente atual</span><strong>{apiEnvironment}</strong><small><ShieldCheck size={12}/> Controle protegido</small></Card></div><div className="integration-tabs" role="tablist">{(['Apps','Webhooks','Sphex API'] as Tab[]).map(item=><button role="tab" aria-selected={tab===item} className={tab===item?'active':''} onClick={()=>setTab(item)} key={item}>{item==='Apps'?<Link2 size={15}/>:item==='Webhooks'?<Webhook size={15}/>:<Code2 size={15}/>} {item}<ChevronRight size={13}/></button>)}</div>{tab==='Apps'&&<AppsPanel apps={apps} toggle={toggleApp}/>} {tab==='Webhooks'&&<WebhooksPanel webhooks={webhooks} setWebhooks={setWebhooks} show={showWebhook} setShow={setShowWebhook} copy={copy}/>} {tab==='Sphex API'&&<ApiPanel environment={apiEnvironment} setEnvironment={setApiEnvironment} copy={copy} copied={copied}/>} {copied&&<span className="integration-copied" role="status"><Check size={14}/> Copiado</span>}</div>}
function AppsPanel({apps,toggle}:{apps:AppItem[];toggle:(name:string)=>void}){return <section className="integration-panel"><div className="integration-section-head"><div><span className="section-eyebrow"><Link2 size={13}/> APP CENTER</span><h2>Apps para ampliar sua operação</h2><p>Conecte ferramentas que você já usa e deixe os dados fluírem com segurança.</p></div><div className="integration-search"><Globe size={15}/> Buscar app</div></div><div className="integration-app-grid">{apps.map(app=><article className="integration-app-card" key={app.name}><div className="integration-app-top"><i style={{background:app.color}}>{app.mark}</i><StatusBadge status={app.connected?'Conectado':'Desconectado'}/></div><h3>{app.name}</h3><p>{app.description}</p><button className={`btn ${app.connected?'':'btn-primary'}`} onClick={()=>toggle(app.name)}>{app.connected?<><Settings2 size={14}/> Configurar</>:<><Plus size={14}/> Conectar</>}</button>{app.connected&&<button className="integration-disconnect" onClick={()=>toggle(app.name)}>Desconectar</button>}</article>)}</div></section>}
function WebhooksPanel({webhooks,setWebhooks,show,setShow,copy}:{webhooks:typeof initialWebhooks;setWebhooks:(items:typeof initialWebhooks)=>void;show:boolean;setShow:(value:boolean)=>void;copy:(value:string,label:string)=>void}){const [name,setName]=useState(''),[url,setUrl]=useState(''),[selected,setSelected]=useState<string[]>(['venda_aprovada'])
 const create=()=>{if(!name.trim()||!url.trim())return;setWebhooks([{id:`wh_${Date.now()}`,name,url,events:selected,active:true,created:'Agora',last:'Ainda não testado'},...webhooks]);setName('');setUrl('');setSelected(['venda_aprovada']);setShow(false)}
 const remove=(id:string)=>setWebhooks(webhooks.filter(item=>item.id!==id))
 return <section className="integration-panel"><div className="integration-section-head"><div><span className="section-eyebrow"><Webhook size={13}/> EVENTOS</span><h2>Webhooks</h2><p>Envie eventos importantes para os seus sistemas e acompanhe cada tentativa.</p></div><button className="btn btn-primary" onClick={()=>setShow(true)}><Plus size={15}/> Criar webhook</button></div>{show&&<Card className="webhook-form"><div className="integration-form-grid"><label><span className="label">Nome</span><input className="input" value={name} onChange={event=>setName(event.target.value)} placeholder="Ex.: Operação principal"/></label><label><span className="label">URL do endpoint</span><input className="input" value={url} onChange={event=>setUrl(event.target.value)} placeholder="https://..."/></label></div><div className="webhook-event-picker"><span className="label">Eventos enviados</span>{webhookEvents.map(event=><label key={event}><input type="checkbox" checked={selected.includes(event)} onChange={e=>setSelected(e.target.checked?[...new Set([...selected,event])]:selected.filter(item=>item!==event))}/>{event}</label>)}</div><div className="integration-form-actions"><button className="btn" onClick={()=>setShow(false)}>Cancelar</button><button className="btn btn-primary" onClick={create}>Salvar webhook</button></div></Card>}{webhooks.length?<div className="webhook-list">{webhooks.map(item=><article key={item.id}><div className="webhook-icon"><Webhook size={18}/></div><div className="webhook-main"><div><h3>{item.name}</h3><span>{item.url}</span></div><div className="webhook-events">{item.events.map(event=><em key={event}>{event}</em>)}</div></div><div className="webhook-last"><StatusBadge status={item.active?'Ativo':'Pausado'}/><small>{item.last}</small></div><div className="webhook-actions"><button aria-label={`Copiar ${item.name}`} onClick={()=>copy(item.url,item.id)}><Copy size={15}/></button><button aria-label={`Testar ${item.name}`} onClick={()=>copy('test',`test-${item.id}`)}><Send size={15}/></button><button aria-label={`Remover ${item.name}`} onClick={()=>remove(item.id)}><Trash2 size={15}/></button><MoreHorizontal size={16}/></div></article>)}</div>:<div className="integration-empty"><Webhook/><p>Nenhum webhook configurado.</p></div>}</section>}
function ApiPanel({environment,setEnvironment,copy,copied}:{environment:string;setEnvironment:(value:string)=>void;copy:(value:string,label:string)=>void;copied:string}){return <section className="integration-panel"><div className="integration-section-head"><div><span className="section-eyebrow"><Code2 size={13}/> DESENVOLVEDORES</span><h2>Sphex API</h2><p>Conecte seus produtos com uma API clara, previsível e pronta para crescer com a sua operação.</p></div><div className="api-environment"><span>Ambiente</span><button className={environment==='Produção'?'active':''} onClick={()=>setEnvironment('Produção')}>Produção</button><button className={environment==='Demonstração'?'active':''} onClick={()=>setEnvironment('Demonstração')}>Desenvolvimento</button></div></div><div className="api-health"><div><i/><b>API operacional</b><span>99,98% de disponibilidade nos últimos 30 dias</span></div><div><span>Limite atual</span><strong>120 req/min</strong></div><div><span>Última utilização</span><strong>Hoje, 10:42</strong></div></div><div className="api-key-grid"><KeyField label="Chave pública" value={keys.public} copy={()=>copy(keys.public,'public')}/><KeyField label="Chave privada" value={keys.private} copy={()=>copy(keys.private,'private')} secret/></div><div className="api-doc-grid"><Card><div className="api-doc-head"><Clipboard size={17}/><div><h3>Primeiros passos</h3><p>Autentique suas requisições e acompanhe os eventos da operação.</p></div><ExternalLink size={15}/></div><ol><li>Use a chave no cabeçalho <code>Authorization</code>.</li><li>Envie JSON com os dados do evento.</li><li>Leia o status e o identificador retornado.</li></ol><button className="btn"><ExternalLink size={14}/> Ver documentação</button></Card><Card><div className="api-doc-head"><Code2 size={17}/><div><h3>Exemplo de requisição</h3><p>Um evento de venda aprovado.</p></div></div><pre>{`POST /v1/events\nAuthorization: Bearer spx_pub_...\n\n{\n  "type": "venda_aprovada",\n  "amount": 497.00,\n  "currency": "BRL"\n}`}</pre><button className="btn" onClick={()=>copy('POST /v1/events','payload')}><Copy size={14}/> Copiar exemplo</button></Card></div></section>}
function KeyField({label,value,copy,secret}:{label:string;value:string;copy:()=>void;secret?:boolean}){return <label className="api-key-field"><span className="label">{label} {secret&&<small>Protegida</small>}</span><div><KeyRound size={15}/><input readOnly value={value}/><button aria-label={`Copiar ${label}`} onClick={copy}><Copy size={14}/></button></div></label>}
