import { useEffect,useMemo,useState } from 'react'
import { useNavigate,useParams,useSearchParams } from 'react-router-dom'
import { ChevronLeft,ChevronRight,Eye,RefreshCcw } from 'lucide-react'
import { Card,Empty,Modal,PageTitle,SearchBox } from '../components/ui'
import { DashboardCurrencySelector,DashboardPeriodFilter } from '../components/dashboard/DashboardControls'
import { RealtimeStatus } from '../components/dashboard/RealtimeStatus'
import { ConvertedMoney } from '../components/dashboard/ConvertedMoney'
import { useAuth } from '../hooks/useAuth'
import { useDashboardCurrency } from '../hooks/useDashboardCurrency'
import { useDashboardPeriod } from '../hooks/useDashboardPeriod'
import { useLiveSales } from '../hooks/useLiveSales'
import { dashboardService } from '../services/dashboardService'
import { maskBuyerName,type ExchangeRate,type FinancialTransaction } from '../lib/dashboardFinance'
import { formatCents } from '../lib/currencyFormat'
import { demoExchangeRates } from '../demo/demoSimulationEngine'
import { TransactionStatusBadge } from '../components/transactions/TransactionStatusBadge'
import { transactionStatusLabels } from '../components/transactions/transactionStatus'

const demoRates:ExchangeRate[]=Object.entries(demoExchangeRates).filter(([currency])=>currency!=='BRL').flatMap(([currency,rate])=>[{baseCurrency:currency as 'USD'|'EUR',quoteCurrency:'BRL',rate:1/rate,source:'taxa de referência',observedAt:new Date().toISOString()},{baseCurrency:'BRL',quoteCurrency:currency as 'USD'|'EUR',rate,source:'taxa de referência',observedAt:new Date().toISOString()}])

export default function LiveSales(){
 const {user}=useAuth(),{period,setPeriod}=useDashboardPeriod(),{currency,setCurrency}=useDashboardCurrency()
 const navigate=useNavigate(),{transactionId}=useParams(),[searchParams]=useSearchParams(),requestedId=transactionId||searchParams.get('evento')
 const live=useLiveSales(user?.id,period),[rates,setRates]=useState<ExchangeRate[]>([]),[query,setQuery]=useState(''),[status,setStatus]=useState('all'),[page,setPage]=useState(1),[detail,setDetail]=useState<FinancialTransaction|null>(null),pageSize=10
 useEffect(()=>{if(live.demo)return;let active=true;dashboardService.loadRates().then(value=>{if(active)setRates(value)}).catch(()=>{});return()=>{active=false}},[live.demo])
 const effectiveRates=live.demo?demoRates:rates
 const rows=useMemo(()=>live.sales.filter(row=>`${row.transactionId} ${row.productName} ${row.buyerName||''} ${row.paymentMethod}`.toLowerCase().includes(query.toLowerCase())&&(status==='all'||row.status===status)),[live.sales,query,status]),pages=Math.max(1,Math.ceil(rows.length/pageSize)),visibleRows=rows.slice((page-1)*pageSize,page*pageSize)
 useEffect(()=>{if(!requestedId)return;const match=live.sales.find(row=>row.transactionId===decodeURIComponent(requestedId));if(match)setDetail(match)},[requestedId,live.sales])
 const openDetail=(row:FinancialTransaction)=>{setDetail(row);navigate(`/app/vendas/${encodeURIComponent(row.transactionId)}`)}
 const closeDetail=()=>{setDetail(null);if(requestedId)navigate('/app/vendas',{replace:true})}
 return <div className="live-sales-page transactions-page internal-real-page page-enter">
  <PageTitle title="Vendas" subtitle={live.demo?'Acompanhe os registros recentes. Ações financeiras reais estão desabilitadas.':'Vendas e movimentações financeiras persistidas, atualizadas em tempo real.'} action={!live.demo?<button className="btn" onClick={()=>void live.refresh()} disabled={live.loading}><RefreshCcw className={live.loading?'spin':''}/> Atualizar</button>:undefined}/>
  <Card className="dashboard-filter-bar"><DashboardPeriodFilter period={period} onChange={value=>{setPeriod(value);setPage(1)}}/><DashboardCurrencySelector currency={currency} onChange={setCurrency}/>{!live.demo&&<RealtimeStatus status={live.realtime} updatedAt={live.updatedAt} onRefresh={()=>void live.refresh()} loading={live.loading}/>}</Card>
  {live.error&&<p className="dashboard-admin-warning" role="alert">{live.error}</p>}
  <Card className="transactions-table-card"><div className="transactions-toolbar internal-filter-bar"><div className="transactions-search"><SearchBox value={query} onChange={value=>{setQuery(value);setPage(1)}} placeholder="Comprador, produto ou identificador..."/></div><label className="transactions-filter internal-filter-select"><span>Status</span><select className="input internal-filter-value" aria-label="Filtrar por status" value={status} onChange={event=>{setStatus(event.target.value);setPage(1)}}><option value="all">Todos</option>{Object.entries(transactionStatusLabels).map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></label></div>
	   <div className="table-wrap transactions-table-wrap"><table className="table"><caption className="sr-only">Vendas e movimentações de pagamento</caption><thead><tr><th>Comprador</th><th>Identificador / horário</th><th>Produto</th><th>Método</th><th>Status</th><th>Valor original</th><th>Exibição</th><th><span className="sr-only">Ações</span></th></tr></thead><tbody>{visibleRows.map(row=><tr key={`${row.transactionId}:${row.status}:${row.updatedAt||row.occurredAt}`} className="sale-enter"><td>{maskBuyerName(row.buyerName)}</td><td><b>{row.transactionId.slice(-12)}</b><p className="muted text-[11px]">{new Date(row.occurredAt).toLocaleString('pt-BR',{timeZone:'America/Sao_Paulo'})}</p></td><td>{row.productName}</td><td>{row.paymentMethod}</td><td><TransactionStatusBadge status={row.status}/></td><td className="transaction-money">{formatCents(row.amountCents,row.currency)}</td><td className="transaction-money"><ConvertedMoney amountCents={row.amountCents} sourceCurrency={row.currency} displayCurrency={currency} rates={effectiveRates}/></td><td><button className="btn icon-btn" aria-label={`Ver detalhes de ${row.transactionId}`} onClick={()=>openDetail(row)}><Eye/></button></td></tr>)}</tbody></table>{!live.loading&&!rows.length&&<Empty text="Ajuste a busca ou os filtros para encontrar uma venda." title="Nenhuma venda encontrada"/>}</div><footer className="transactions-pagination"><span>{rows.length} registro{rows.length===1?'':'s'} · Página {page} de {pages}</span><div><button className="btn icon-btn" aria-label="Página anterior de vendas" disabled={page===1} onClick={()=>setPage(value=>value-1)}><ChevronLeft/></button><button className="btn icon-btn" aria-label="Próxima página de vendas" disabled={page>=pages} onClick={()=>setPage(value=>value+1)}><ChevronRight/></button></div></footer>
  </Card>
	 {detail&&<Modal title="Detalhes da venda" className="transactions-details-modal" onClose={closeDetail}><section className="sale-detail-section"><h3>Resumo</h3><div className="transactions-details-grid">{Object.entries({Cliente:maskBuyerName(detail.buyerName),Produto:detail.productName,Status:transactionStatusLabels[detail.status],Data:new Date(detail.occurredAt).toLocaleString('pt-BR',{timeZone:'America/Sao_Paulo'})}).map(([label,value])=><div key={label}><span className="label">{label}</span><b>{value}</b></div>)}</div></section><section className="sale-detail-section"><h3>Pagamento</h3><div className="transactions-details-grid">{Object.entries({Método:detail.paymentMethod,'Valor bruto':formatCents(detail.grossAmountCents??detail.amountCents,detail.currency),Desconto:formatCents(detail.discountCents??0,detail.currency),Taxas:formatCents(detail.feeCents,detail.currency),'Valor líquido':formatCents(detail.netAmountCents??Math.max(0,detail.amountCents-detail.feeCents),detail.currency),Comissão:formatCents(detail.commissionCents??0,detail.currency)}).map(([label,value])=><div key={label}><span className="label">{label}</span><b>{value}</b></div>)}</div></section><section className="sale-detail-section"><h3>Transação</h3><div className="transactions-details-grid">{Object.entries({'Transaction ID':detail.transactionId,...(detail.productId?{'Product ID':detail.productId}:{}),'Última atualização':new Date(detail.updatedAt||detail.occurredAt).toLocaleString('pt-BR',{timeZone:'America/Sao_Paulo'})}).map(([label,value])=><div key={label}><span className="label">{label}</span><b>{value}</b></div>)}</div></section>{detail.demo&&<p className="demo-detail-warning">Reembolso, captura, cancelamento, exportação de produção e demais ações financeiras estão desabilitados.</p>}</Modal>}
 </div>
}
