import { useMemo,useState } from 'react'
import { CheckCheck,Search,Settings2,Trash2 } from 'lucide-react'
import { useNavigate } from 'react-router-dom'
import { Empty,PageTitle } from '../components/ui'
import { NotificationItem } from '../components/notifications/NotificationItem'
import { useDemoStore } from '../store/useDemoStore'

const filters=['Todas','Não lidas','Vendas','Pix','Cartão','Assinaturas','Saques','Segurança','Premiações','Arquivadas'] as const
export default function NotificationsPage(){const [filter,setFilter]=useState<(typeof filters)[number]>('Todas'),[query,setQuery]=useState(''),[visible,setVisible]=useState(10),notifications=useDemoStore(s=>s.notifications),read=useDemoStore(s=>s.markNotificationRead),readAll=useDemoStore(s=>s.markAllNotificationsRead),archive=useDemoStore(s=>s.archiveNotification),remove=useDemoStore(s=>s.deleteNotification),clear=useDemoStore(s=>s.clearNotifications),navigate=useNavigate(),unread=notifications.filter(item=>!item.read&&!item.archived).length,filtered=useMemo(()=>notifications.filter(item=>{const method=item.metadata?.method||'',matchesFilter=filter==='Todas'?!item.archived:filter==='Não lidas'?!item.read&&!item.archived:filter==='Arquivadas'?item.archived:filter==='Pix'?method==='Pix':filter==='Cartão'?method==='Cartão de crédito':filter==='Premiações'?item.kind==='achievement'||item.kind==='goal':filter==='Assinaturas'?item.category==='Assinaturas':filter==='Saques'?item.category==='Saques':filter==='Segurança'?item.category==='Segurança':item.category==='Vendas';return matchesFilter&&`${item.title} ${item.description} ${item.metadata?.buyer||''} ${item.metadata?.product||''}`.toLowerCase().includes(query.toLowerCase())}),[notifications,filter,query]);return <div className="page-enter notifications-page"><PageTitle title="Notificações" subtitle="Eventos financeiros, operacionais, premiações e alertas da conta." action={<div className="flex flex-wrap gap-2"><button className="btn" onClick={readAll} disabled={!unread}><CheckCheck/> Marcar todas como lidas</button><button className="btn" onClick={()=>{if(confirm('Limpar todo o histórico de notificações?'))clear()}} disabled={!notifications.length}><Trash2/> Limpar histórico</button><button className="btn btn-primary" onClick={()=>navigate('/configuracoes?secao=Notificações')}><Settings2/> Configurar</button></div>}/><div className="notification-summary"><span>{unread}</span><div><strong>Notificações não lidas</strong><p>Eventos individuais permanecem no histórico da SphexPay.</p></div></div><label className="notification-search"><Search/><input aria-label="Buscar notificações" placeholder="Buscar por comprador, produto ou evento..." value={query} onChange={event=>setQuery(event.target.value)}/></label><div className="notification-filters scrollbar" role="tablist" aria-label="Filtrar notificações">{filters.map(item=><button role="tab" aria-selected={filter===item} className={filter===item?'active':''} key={item} onClick={()=>{setFilter(item);setVisible(10)}}>{item}</button>)}</div><section className="panel notification-page-list">{filtered.slice(0,visible).map(item=><NotificationItem key={item.id} notification={item} onRead={read} onArchive={archive} onDelete={remove}/>)}{!filtered.length&&<Empty text="Nenhuma notificação nesta categoria."/>}</section>{visible<filtered.length&&<button className="btn notification-load" onClick={()=>setVisible(value=>value+10)}>Carregar mais</button>}</div>}
