import { useEffect,useRef as useReactRef,useState } from 'react'
import { Activity,Bell,Building2,Database,Download,FileBarChart,Grid2X2,Landmark,LayoutDashboard,MessageCircle,Plug,RefreshCcw,Save,Shield,SlidersHorizontal,UserRound,Volume2,WalletCards } from 'lucide-react'
import { useSearchParams } from 'react-router-dom'
import { Card,PageTitle } from '../components/ui'
import { AppInstallCard } from '../components/pwa/AppInstallCard'
import { useDemoStore } from '../store/useDemoStore'
import { AvatarUploader } from '../components/profile/AvatarUploader'
import { NotificationDelivery } from '../components/settings/NotificationDelivery'
import { SoundSettings } from '../components/settings/SoundSettings'
import { voiceService } from '../services/voiceService'
import { DemoControlPanel } from '../components/demo/DemoControlPanel'
import { useDashboardData } from '../providers/DashboardDataProvider'
import {mobileDockVisualStyle,normalizeMobileDockOpacity} from '../lib/mobileDockVisual'

const useRef=<T,>(initial?:T)=>useReactRef<T|undefined>(initial)

const sections=[['Perfil',UserRound],['Empresa',Building2],['Aplicativo',Download],['Notificações',Bell],['Sons e voz',Volume2],['Segurança',Shield],['Preferências',SlidersHorizontal],['Dados bancários',WalletCards],['Integrações futuras',Plug],['Dados',Database]] as const
const modeSection=['Modo',Activity] as const
type Section=(typeof sections)[number][0]|typeof modeSection[0]
// eslint-disable-next-line @typescript-eslint/no-unused-vars
export default function Settings(){const s=useDemoStore(),permission=useDashboardData(),[params,setParams]=useSearchParams(),requested=params.get('secao'),available=permission.allowed?[...sections,modeSection]:sections,initial=sections.some(([name])=>name===requested)?requested as Section:'Perfil';const [tab,setTab]=useState<Section>(initial),[saved,setSaved]=useState(false),timer=useRef<number>();useEffect(()=>{if(requested==='Modo'&&permission.allowed)setTab('Modo');if(tab==='Modo'&&!permission.loadingPermission&&!permission.allowed)setTab('Perfil')},[permission.allowed,permission.loadingPermission,requested,tab]);useEffect(()=>()=>{if(timer.current)clearTimeout(timer.current)},[]);const choose=(name:Section)=>{setTab(name);setParams({secao:name})},save=()=>{setSaved(true);if(timer.current)clearTimeout(timer.current);timer.current=window.setTimeout(()=>setSaved(false),1800)};return <div className="page-enter"><PageTitle title="Configurações" subtitle="Personalize sua conta, preferências e recursos do dispositivo."/><div className="grid lg:grid-cols-[260px_1fr] gap-5"><Card className="p-2 self-start overflow-auto"><div className="flex lg:flex-col gap-1 min-w-max">{available.map(([name,Icon])=><button className={`btn justify-start ${tab===name?'bg-[var(--orange-soft)] orange border-transparent':''}`} onClick={()=>choose(name)} key={name}><Icon size={17}/>{name}</button>)}</div></Card><Card className={tab==='Notificações'?'push-settings-shell':tab==='Modo'?'mode-settings-shell':'p-5 md:p-7'}>{tab!=='Notificações'&&tab!=='Modo'&&<><h2 className="font-bold text-lg">{tab}</h2><p className="muted text-xs mt-1 mb-6">Preferências armazenadas localmente neste navegador.</p></>}<SectionContent tab={tab}/>{tab!=='Aplicativo'&&tab!=='Notificações'&&tab!=='Modo'&&<div className="mt-7 pt-5 border-t border-[var(--line)] flex items-center gap-3"><button className="btn btn-primary" onClick={save}><Save size={16}/> Salvar preferências</button>{saved&&<span className="text-emerald-600 text-xs">Preferências salvas.</span>}</div>}</Card></div></div>}
function SectionContent({tab}:{tab:Section}){const s=useDemoStore();if(tab==='Modo')return <DemoControlPanel/>;if(tab==='Aplicativo')return <AppInstallCard/>;if(tab==='Sons e voz')return <SoundSettings/>;if(tab==='Perfil')return <div><div className="settings-profile-photo"><AvatarUploader/><div><b>Foto do perfil</b><p>PNG, JPG ou WebP · recorte e enquadramento local</p></div></div><div className="grid sm:grid-cols-2 gap-4"><Field label="Nome" value="Ronald Rodriguez"/><Field label="E-mail" value="admin@sphexpay.local" type="email"/><Field label="Telefone" value="+55 11 99999-0000"/><Field label="Idioma" value="Português (Brasil)"/></div></div>;if(tab==='Empresa')return <div className="grid sm:grid-cols-2 gap-4"><Field label="Nome da empresa" value="SphexPay Ltda."/><Field label="Documento" value="00.000.000/0000-00"/><Field label="País" value="Brasil"/><Field label="Moeda principal" value="BRL — Real brasileiro"/></div>;if(tab==='Notificações')return <NotificationDelivery/>;if(tab==='Segurança')return <><SimpleToggles labels={['Autenticação em duas etapas','Alertas de novo acesso','Bloqueio por inatividade']}/><div className="security-sessions"><h3>Sessões e dispositivos</h3>{[['MacBook Pro','São Paulo · sessão atual'],['iPhone','São Paulo · último acesso hoje']].map(([device,info],index)=><div key={device}><span><b>{device}</b><small>{info}</small></span><button className="btn" disabled={index===0}>{index===0?'Atual':'Encerrar sessão'}</button></div>)}</div><div className="mt-5 p-4 rounded-xl bg-[var(--orange-soft)] text-xs">Não armazene senhas ou credenciais financeiras nesta aplicação.</div></>;if(tab==='Preferências')return <><MobileNavigationPreferences/><Preferences/></>;if(tab==='Dados bancários')return <div className="p-5 rounded-xl border border-[var(--line)]"><b>Conta cadastrada</b><p className="muted text-sm mt-2">Agência 0001 · Conta •••• 4821</p><p className="text-xs orange mt-3">Nenhuma integração bancária oficial está conectada.</p></div>;if(tab==='Integrações futuras')return <div className="grid sm:grid-cols-2 gap-3">{['API de pagamentos autorizada','Webhooks','ERP / Contabilidade','CRM'].map(item=><div className="p-4 rounded-xl border border-[var(--line)]" key={item}><b className="text-sm">{item}</b><p className="muted text-xs mt-1">Não configurada</p><button className="btn mt-4" disabled>Em breve</button></div>)}</div>;return <div className="p-5 rounded-xl bg-[var(--panel-2)]"><b>Gerenciamento local</b><p className="muted text-sm mt-2">Restaure métricas, produtos, clientes, vendas e preferências para o conjunto inicial.</p><button className="btn mt-5 text-red-500" onClick={()=>{if(confirm('Restaurar todos os dados locais?'))s.reset()}}><RefreshCcw size={16}/> Restaurar dados iniciais</button></div>}
export function MobileNavigationPreferences(){const opacity=useDemoStore(state=>state.preferences.mobileNavigation.opacity),updatePreferences=useDemoStore(state=>state.updatePreferences),normalized=normalizeMobileDockOpacity(opacity);return <section className="mobile-navigation-preferences"><h3>Navegação mobile</h3><p>Ajuste a transparência do menu inferior sem comprometer a legibilidade.</p><div className="mobile-dock-preview"><div style={mobileDockVisualStyle(normalized) as React.CSSProperties}>{[FileBarChart,Landmark,LayoutDashboard,MessageCircle,Grid2X2].map((Icon,index)=><span className={index===2?'active':''} key={index}><Icon/><i/></span>)}</div></div><label className="mobile-opacity-control"><span>Transparência do menu mobile <b>{normalized}%</b></span><input aria-label="Transparência do menu mobile" aria-valuemin={0} aria-valuemax={100} aria-valuenow={normalized} type="range" min="0" max="100" step="1" value={normalized} onChange={event=>updatePreferences('mobileNavigation',{opacity:normalizeMobileDockOpacity(event.target.value)})}/><small><span>Mais transparente</span><span>Mais opaco</span></small></label></section>}
function Preferences(){const s=useDemoStore(),assistant=s.preferences.assistant,sales=s.preferences.sales,[voices,setVoices]=useState<SpeechSynthesisVoice[]>([]);useEffect(()=>{if(!('speechSynthesis'in window))return;const synth=window.speechSynthesis,load=()=>setVoices(synth.getVoices());load();synth.addEventListener?.('voiceschanged',load);return()=>synth.removeEventListener?.('voiceschanged',load)},[]);return <div className="preference-sections"><section><h3>Assistente</h3><Toggle label="Permitir microfone" checked={assistant.microphone} onChange={value=>s.updatePreferences('assistant',{microphone:value})}/><Toggle label="Leitura em voz alta" checked={assistant.readAloud} onChange={value=>s.updatePreferences('assistant',{readAloud:value})}/><Toggle label="Interromper fala ao enviar nova pergunta" checked={assistant.interruptOnSend} onChange={value=>s.updatePreferences('assistant',{interruptOnSend:value})}/><Select label="Idioma" value={assistant.language} onChange={value=>s.updatePreferences('assistant',{language:value})} options={[['pt-BR','Português (Brasil)'],['en-US','English (US)'],['es-ES','Español']]}/><Select label="Voz" value={assistant.voice} onChange={value=>s.updatePreferences('assistant',{voice:value})} options={[['','Padrão do dispositivo'],...voiceService.catalog(voices).map(v=>[v.voiceURI,`${v.name} · ${v.lang}`])]}/><Range label="Velocidade da fala" value={assistant.speechRate} min={.5} max={2} step={.1} onChange={value=>s.updatePreferences('assistant',{speechRate:value})}/><Range label="Volume" value={assistant.volume} min={0} max={1} step={.1} onChange={value=>s.updatePreferences('assistant',{volume:value})}/></section><section><h3>Vendas</h3><Toggle label="Atualizações automáticas" checked={sales.automaticUpdates} onChange={value=>s.setLiveSales(value)}/><Range label="Frequência das atualizações locais (segundos)" value={sales.updateFrequency} min={5} max={120} step={1} onChange={value=>s.updatePreferences('sales',{updateFrequency:value})}/><Range label="Vendas recentes no dashboard" value={sales.recentCount} min={3} max={12} step={1} onChange={value=>s.updatePreferences('sales',{recentCount:value})}/></section></div>}
function Toggle({label,checked,onChange}:{label:string;checked:boolean;onChange:(value:boolean)=>void}){return <label className="setting-toggle"><span>{label}</span><input type="checkbox" checked={checked} onChange={e=>onChange(e.target.checked)}/><i/></label>}
function Field({label,value,type='text'}:{label:string;value:string;type?:string}){return <label><span className="label">{label}</span><input className="input" defaultValue={value} type={type}/></label>}
function SimpleToggles({labels}:{labels:string[]}){return <div>{labels.map((label,index)=><label className="setting-toggle" key={label}><span>{label}</span><input type="checkbox" defaultChecked={index<2}/><i/></label>)}</div>}
function Select({label,value,onChange,options}:{label:string;value:string;onChange:(value:string)=>void;options:string[][]}){return <label className="block mt-4"><span className="label">{label}</span><select className="input" value={value} onChange={e=>onChange(e.target.value)}>{options.map(([key,text])=><option key={key} value={key}>{text}</option>)}</select></label>}
function Range({label,value,min,max,step,onChange}:{label:string;value:number;min:number;max:number;step:number;onChange:(value:number)=>void}){return <label className="block mt-4"><span className="label">{label}: {value}</span><input className="w-full accent-orange-600" type="range" value={value} min={min} max={max} step={step} onChange={e=>onChange(Number(e.target.value))}/></label>}
