import { ArrowUpRight,Check,ChevronDown,Filter,Search,ShoppingBag,Sparkles,Star,Users,X } from 'lucide-react'
import { useMemo,useState } from 'react'
import { Card,PageTitle } from '../components/ui'
import { money } from '../lib/utils'

type ShowcaseProduct={id:string;name:string;creator:string;category:string;type:string;price:number;commission:number;sales:number;accent:string;description:string;featured?:boolean}
const products:ShowcaseProduct[]=[
 {id:'ia-academy',name:'IA Academy',creator:'@futurelab',category:'Educação',type:'Curso',price:497,commission:45,sales:1280,accent:'#f15a24',description:'Formação prática para criar fluxos inteligentes e escalar operações com inteligência artificial.',featured:true},
 {id:'tok-shop',name:'Tok Shop BR',creator:'@tokcommerce',category:'E-commerce',type:'Software',price:89,commission:35,sales:942,accent:'#111827',description:'Ferramentas para organizar catálogo, afiliados e conversões em uma única operação.'},
 {id:'flow-automate',name:'Flow Automate',creator:'@flowstack',category:'Automação',type:'SaaS',price:149,commission:40,sales:731,accent:'#334155',description:'Automação visual para conectar processos, dados e times sem fricção.'},
 {id:'marketing-elite',name:'Marketing Elite',creator:'@mktclub',category:'Marketing',type:'Comunidade',price:297,commission:50,sales:608,accent:'#c2410c',description:'Playbooks, aulas e encontros para transformar aquisição em crescimento previsível.'},
 {id:'fin-prime',name:'Fin Prime',creator:'@finprime',category:'Finanças',type:'Curso',price:397,commission:38,sales:486,accent:'#166534',description:'Educação financeira aplicada para negócios digitais e criadores independentes.'},
 {id:'store-builder',name:'Store Builder',creator:'@buildfast',category:'E-commerce',type:'Software',price:249,commission:30,sales:391,accent:'#7c3aed',description:'Construa vitrines digitais rápidas, elegantes e prontas para vender.'},
 {id:'creator-pro',name:'Creator Pro',creator:'@studioalpha',category:'Marketing',type:'Mentoria',price:697,commission:55,sales:274,accent:'#be185d',description:'Mentoria avançada para posicionamento, conteúdo e monetização.'},
 {id:'data-pulse',name:'Data Pulse',creator:'@metricflow',category:'Automação',type:'SaaS',price:119,commission:42,sales:216,accent:'#0369a1',description:'Painéis enxutos para encontrar oportunidades nos seus dados de conversão.'},
]
const affiliateKey='sphexpay_showcase_affiliations'
const readAffiliations=()=>{try{return JSON.parse(localStorage.getItem(affiliateKey)||'[]') as string[]}catch{return[]}}
export default function Showcase(){const [query,setQuery]=useState(''),[category,setCategory]=useState('Todas'),[type,setType]=useState('Todos'),[sort,setSort]=useState('hot'),[selected,setSelected]=useState<ShowcaseProduct|null>(null),[affiliations,setAffiliations]=useState<string[]>(readAffiliations)
 const categories=['Todas',...new Set(products.map(item=>item.category))],types=['Todos',...new Set(products.map(item=>item.type))]
 const visible=useMemo(()=>products.filter(item=>(category==='Todas'||item.category===category)&&(type==='Todos'||item.type===type)&&`${item.name} ${item.creator} ${item.category}`.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>sort==='commission'?b.commission-a.commission:sort==='price'?a.price-b.price:sort==='recent'?b.id.localeCompare(a.id):b.sales-a.sales),[query,category,type,sort])
 const requestAffiliate=(id:string)=>{setAffiliations(current=>{const next=current.includes(id)?current:[...current,id];localStorage.setItem(affiliateKey,JSON.stringify(next));return next});setSelected(current=>current?{...current}:null)}
 return <div className="page-enter showcase-page"><PageTitle title="Vitrine" subtitle="Descubra produtos, encontre novas oportunidades e amplie sua operação como afiliado."/><section className="showcase-hero"><div><span className="section-eyebrow"><Sparkles size={14}/> ECOSSISTEMA SPHEXPAY</span><h2>Produtos que combinam com a sua audiência.</h2><p>Explore ofertas selecionadas, veja o potencial de cada produto e solicite sua afiliação em poucos passos.</p></div><div className="showcase-hero-stat"><ShoppingBag/><b>{products.length}</b><span>ofertas disponíveis</span></div></section>
 <Card className="showcase-toolbar"><label className="showcase-search"><Search size={17}/><input aria-label="Buscar produtos da vitrine" placeholder="Buscar produto, criador ou categoria" value={query} onChange={event=>setQuery(event.target.value)}/>{query&&<button aria-label="Limpar busca" onClick={()=>setQuery('')}><X size={14}/></button>}</label><div className="showcase-filters"><label><Filter size={14}/><select aria-label="Filtrar por categoria" value={category} onChange={event=>setCategory(event.target.value)}>{categories.map(value=><option key={value}>{value}</option>)}</select><ChevronDown size={13}/></label><label><select aria-label="Filtrar por tipo" value={type} onChange={event=>setType(event.target.value)}>{types.map(value=><option key={value}>{value}</option>)}</select><ChevronDown size={13}/></label><label><span>Ordenar</span><select aria-label="Ordenar vitrine" value={sort} onChange={event=>setSort(event.target.value)}><option value="hot">Mais quentes</option><option value="recent">Mais recentes</option><option value="commission">Maior comissão</option><option value="price">Menor preço</option></select><ChevronDown size={13}/></label></div></Card>
 <div className="showcase-grid">{visible.map(product=><article className={`showcase-product ${product.featured?'featured':''}`} key={product.id} onClick={()=>setSelected(product)}><div className="showcase-cover" style={{background:`linear-gradient(135deg,${product.accent},#08090d)`}}><span>{product.category}</span><b>{product.name.split(' ').map(part=>part[0]).join('').slice(0,3)}</b><i/></div><div className="showcase-product-copy"><div className="showcase-product-title"><div><h3>{product.name}</h3><small>{product.creator}</small></div><ArrowUpRight size={16}/></div><p>{product.description}</p><div className="showcase-product-meta"><span><Users size={13}/>{product.sales.toLocaleString('pt-BR')} vendas</span><span className="showcase-commission">{product.commission}% comissão</span></div><div className="showcase-product-footer"><strong>{money(product.price)}</strong><button className="btn btn-primary" onClick={event=>{event.stopPropagation();setSelected(product)}}>Ver detalhes</button></div></div></article>)}{!visible.length&&<Card className="showcase-empty"><Search/><h3>Nenhum produto encontrado</h3><p>Tente ajustar sua busca ou os filtros.</p></Card>}</div>
 {selected&&<div className="showcase-modal-backdrop" onMouseDown={()=>setSelected(null)}><section className="showcase-detail" role="dialog" aria-modal="true" aria-label={`Detalhes de ${selected.name}`} onMouseDown={event=>event.stopPropagation()}><button className="btn btn-ghost showcase-close" aria-label="Fechar detalhes" onClick={()=>setSelected(null)}><X/></button><div className="showcase-detail-cover" style={{background:`linear-gradient(135deg,${selected.accent},#08090d)`}}><span>{selected.category}</span><b>{selected.name}</b><small>{selected.creator}</small></div><div className="showcase-detail-body"><div className="showcase-detail-heading"><div><span className="section-eyebrow"><Star size={13}/> OFERTA EM DESTAQUE</span><h2>{selected.name}</h2><p>{selected.creator} · {selected.type}</p></div><div><strong>{selected.commission}%</strong><small>comissão</small></div></div><p className="showcase-detail-description">{selected.description}</p><dl className="showcase-detail-stats"><div><dt>Preço</dt><dd>{money(selected.price)}</dd></div><div><dt>Você recebe até</dt><dd>{money(selected.price*selected.commission/100)}</dd></div><div><dt>Vendas</dt><dd>{selected.sales.toLocaleString('pt-BR')}</dd></div></dl><div className="showcase-detail-actions">{affiliations.includes(selected.id)?<span className="showcase-requested"><Check size={16}/> Afiliação solicitada</span>:<button className="btn btn-primary" onClick={()=>requestAffiliate(selected.id)}>Solicitar afiliação</button>}<button className="btn" onClick={()=>setSelected(null)}>Fechar</button></div></div></section></div>}
 </div>}
