import { Check,Landmark,LoaderCircle,RefreshCcw,ShieldCheck,WalletCards,X } from 'lucide-react'
import { useCallback,useEffect,useMemo,useRef,useState } from 'react'
import { Card,PageTitle } from '../components/ui'
import { useAuth } from '../hooks/useAuth'
import { notificationService } from '../services/notificationService'
import { withdrawalAmountToMinor,withdrawalMoney,withdrawalService,type BankAccount,type SecureWithdrawal,type WalletBalance,type WithdrawalStatus } from '../services/withdrawalService'
import { useAppStore } from '../store/useAppStore'
import type { Withdrawal } from '../types'

const statusLabels:Record<WithdrawalStatus,string>={requested:'Solicitado',processing:'Em processamento',completed:'Concluído',rejected:'Recusado',cancelled:'Cancelado',failed:'Falhou'}
const legacyStatus:Record<WithdrawalStatus,Withdrawal['status']>={requested:'Solicitado',processing:'Processando',completed:'Concluído',rejected:'Recusado',cancelled:'Cancelado',failed:'Falhou'}
const toCache=(items:SecureWithdrawal[]):Withdrawal[]=>items.map(item=>({id:item.id,amount:item.grossAmountMinor/100,fee:item.feeAmountMinor/100,netAmount:item.netAmountMinor/100,currency:item.currency,date:item.requestedAt,status:legacyStatus[item.status],account:item.destinationLabel,lastDigits:item.destinationLastDigits}))

export default function WithdrawalsPage(){
 const {user}=useAuth(),syncWithdrawalCache=useAppStore(state=>state.syncWithdrawalCache),notificationPreferences=useAppStore(state=>state.preferences.notifications),[amount,setAmount]=useState(''),[accounts,setAccounts]=useState<BankAccount[]>([]),[wallets,setWallets]=useState<WalletBalance[]>([]),[withdrawals,setWithdrawals]=useState<SecureWithdrawal[]>([]),[accountId,setAccountId]=useState(''),[loading,setLoading]=useState(true),[processing,setProcessing]=useState(false),[error,setError]=useState(''),[confirmation,setConfirmation]=useState(''),[modal,setModal]=useState(false),key=useRef(''),completedNotified=useRef(new Set<string>()),availableCache=useRef(0)
 const account=accounts.find(item=>item.id===accountId),wallet=wallets.find(item=>item.currency===account?.currency)||wallets[0],amountMinor=withdrawalAmountToMinor(amount),availableMinor=wallet?.availableBalanceMinor??0
 const sync=useCallback((nextWallets:WalletBalance[],nextWithdrawals:SecureWithdrawal[])=>{setWallets(nextWallets);setWithdrawals(nextWithdrawals);const primary=nextWallets.find(item=>item.currency==='BRL')||nextWallets[0];if(primary){availableCache.current=primary.availableBalanceMinor/100;syncWithdrawalCache(availableCache.current,toCache(nextWithdrawals))}},[syncWithdrawalCache])
 const load=useCallback(async()=>{setLoading(true);setError('');try{const data=await withdrawalService.load();setAccounts(data.accounts);setAccountId(current=>current||data.accounts[0]?.id||'');sync(data.wallets,data.withdrawals)}catch(loadError){setError((loadError as Error).message)}finally{setLoading(false)}},[sync])
 useEffect(()=>{if(!user){setLoading(false);setError('Entre novamente para acessar os saques.');return}void load();return withdrawalService.subscribe(user.id,updated=>{setWithdrawals(items=>{const next=items.some(item=>item.id===updated.id)?items.map(item=>item.id===updated.id?updated:item):[updated,...items];syncWithdrawalCache(availableCache.current,toCache(next));return next});if(updated.status==='completed'&&!completedNotified.current.has(updated.id)&&notificationPreferences.device&&notificationPreferences.withdrawalEvents!==false){completedNotified.current.add(updated.id);void notificationService.showCommerce({id:`withdrawal-completed-${updated.id}`,type:'withdrawal_completed',commission:updated.netAmountMinor/100,currency:updated.currency,createdAt:updated.completedAt||new Date().toISOString(),route:'/app/saques',title:'Saque realizado com sucesso',body:`Valor enviado: ${withdrawalMoney(updated.netAmountMinor,updated.currency)}`})}})},[load,notificationPreferences.device,notificationPreferences.withdrawalEvents,syncWithdrawalCache,user])
 const validate=()=>{if(!user)return'Entre novamente para solicitar o saque.';if(!Number.isFinite(amountMinor)||amountMinor<=0)return'Informe um valor de saque válido.';if(!accountId)return'Selecione uma conta de destino.';if(!account)return'A conta selecionada não está disponível.';if(amountMinor>availableMinor)return'Saldo insuficiente para realizar este saque.';return''}
 const review=()=>{const issue=validate();if(issue){setError(issue);return}key.current=crypto.randomUUID();setError('');setModal(true)}
 const confirm=async()=>{if(processing)return;const issue=validate();if(issue){setError(issue);setModal(false);return}setProcessing(true);setError('');setConfirmation('');try{const result=await withdrawalService.request(amountMinor,accountId,key.current);if(result.duplicate)throw new Error('Esta solicitação já está sendo processada.');const nextWallets=wallets.map(item=>item.currency===result.withdrawal.currency?{...item,availableBalanceMinor:result.availableBalanceMinor}:item),nextWithdrawals=[result.withdrawal,...withdrawals.filter(item=>item.id!==result.withdrawal.id)];sync(nextWallets,nextWithdrawals);setAmount('');setModal(false);setConfirmation(`Saque solicitado com sucesso. Valor solicitado: ${withdrawalMoney(result.withdrawal.grossAmountMinor,result.withdrawal.currency)}. Ambiente de teste · Em processamento.`);if(notificationPreferences.device&&notificationPreferences.withdrawalEvents!==false)void notificationService.showCommerce({id:`withdrawal-requested-${result.withdrawal.id}`,type:'withdrawal_requested',commission:result.withdrawal.grossAmountMinor/100,currency:result.withdrawal.currency,createdAt:result.withdrawal.requestedAt,route:'/app/saques',title:'Saque solicitado',body:`Saque solicitado: ${withdrawalMoney(result.withdrawal.grossAmountMinor,result.withdrawal.currency)}`})}catch(requestError){setError((requestError as Error).message);setModal(false)}finally{setProcessing(false)}}
 const history=useMemo(()=>[...withdrawals].sort((a,b)=>b.requestedAt.localeCompare(a.requestedAt)),[withdrawals])
 return <div className="page-enter withdrawals-secure"><PageTitle title="Saques" subtitle="Solicitações protegidas, histórico persistente e saldo validado no servidor."/>
 {!withdrawalService.available()&&<div className="withdrawal-backend-warning"><ShieldCheck/><div><b>Serviço seguro indisponível</b><p>Configure o Supabase e aplique a migration de saques antes de solicitar movimentações.</p></div></div>}
 <div className="withdrawal-layout"><Card className="withdrawal-request-card"><div className="withdrawal-balance-icon"><WalletCards/></div><span className="label">{wallet?.isTestBalance?'Saldo disponível de teste':'Saldo disponível'}</span><p>{loading?<span className="withdrawal-skeleton" aria-label="Carregando saldo"/>:account?withdrawalMoney(availableMinor,account.currency):wallet?withdrawalMoney(wallet.availableBalanceMinor,wallet.currency):'Indisponível'}</p>{wallet?.isTestBalance&&<p className="withdrawal-test-note">Ambiente de teste · nenhuma transferência bancária real será realizada.</p>}<label><span className="label">Valor do saque</span><input aria-label="Valor do saque" inputMode="decimal" className="input" value={amount} onChange={event=>{setAmount(event.target.value);key.current='';setError('');setConfirmation('')}} placeholder={account?.currency==='USD'?'US$ 0.00':account?.currency==='EUR'?'€ 0,00':'R$ 0,00'}/></label><label><span className="label">Conta de destino</span><select aria-label="Conta de destino" className="input" value={accountId} onChange={event=>{setAccountId(event.target.value);key.current='';setError('');setConfirmation('')}}><option value="">Selecione uma conta</option>{accounts.map(item=><option value={item.id} key={item.id}>{item.label} · {item.bankName} · final {item.lastDigits}{item.isTest?' · Teste':''}</option>)}</select>{account?.isTest&&<small className="withdrawal-test-badge">TESTE · Ambiente sandbox</small>}</label><button className="btn btn-primary" disabled={loading||processing||!withdrawalService.available()} onClick={review}>{processing?<><LoaderCircle className="spin"/> Processando solicitação...</>:<>Confirmar solicitação</>}</button>{error&&<p className="withdrawal-error" role="alert">{error}</p>}{confirmation&&<p className="withdrawal-confirmation" role="status">{confirmation}</p>}</Card>
 <Card className="withdrawal-history-card"><header><div><b>Histórico de saques</b><span>Acompanhe suas solicitações e movimentações.</span></div><button className="btn btn-ghost" onClick={()=>void load()} disabled={loading}><RefreshCcw className={loading?'spin':''}/> Atualizar</button></header>{loading?<div className="withdrawal-state"><LoaderCircle className="spin"/><p>Carregando saques...</p></div>:error&&!history.length?<div className="withdrawal-state error"><Landmark/><p>Não foi possível carregar o histórico.</p><button className="btn" onClick={()=>void load()}>Tentar novamente</button></div>:history.length?<div className="withdrawal-history-list">{history.map(item=><article key={item.id}><div className="withdrawal-history-main"><span className={`withdrawal-status-dot ${item.status}`}/><div><b>{withdrawalMoney(item.grossAmountMinor,item.currency)}</b><small>{item.destinationLabel} · final {item.destinationLastDigits}</small></div></div><dl><div><dt>Valor líquido</dt><dd>{withdrawalMoney(item.netAmountMinor,item.currency)}</dd></div>{item.feeAmountMinor>0&&<div><dt>Taxa</dt><dd>{withdrawalMoney(item.feeAmountMinor,item.currency)}</dd></div>}<div><dt>Solicitado em</dt><dd>{new Date(item.requestedAt).toLocaleString('pt-BR')}</dd></div><div><dt>Status</dt><dd>{statusLabels[item.status]}</dd></div></dl><code title={item.id}>{item.id}</code></article>)}</div>:<div className="withdrawal-state"><Landmark/><p>Nenhum saque solicitado.</p></div>}</Card></div>
 {modal&&account&&<div className="withdrawal-modal-backdrop" role="presentation"><section role="dialog" aria-modal="true" aria-labelledby="withdrawal-confirm-title"><button className="withdrawal-modal-close" aria-label="Fechar confirmação" disabled={processing} onClick={()=>setModal(false)}><X/></button><div className="withdrawal-modal-icon"><ShieldCheck/></div><span>CONFIRMAÇÃO SEGURA</span><h2 id="withdrawal-confirm-title">Confirmar solicitação de saque</h2><dl><div><dt>Valor do saque</dt><dd>{withdrawalMoney(amountMinor,account.currency)}</dd></div><div><dt>Taxa</dt><dd>{withdrawalMoney(0,account.currency)}</dd></div><div><dt>Valor líquido</dt><dd>{withdrawalMoney(amountMinor,account.currency)}</dd></div><div><dt>Conta de destino</dt><dd>{account.label} · final {account.lastDigits}</dd></div></dl><p>A solicitação será registrada e o saldo reservado imediatamente pelo servidor.</p><footer><button className="btn" disabled={processing} onClick={()=>setModal(false)}>Cancelar</button><button className="btn btn-primary" disabled={processing} onClick={()=>void confirm()}>{processing?<><LoaderCircle className="spin"/> Processando solicitação...</>:<><Check/> Confirmar saque</>}</button></footer></section></div>}</div>
}
