import { useEffect,useRef,useState } from 'react'; import { NavLink, Outlet, useLocation,useNavigate } from 'react-router-dom';
import { LayoutDashboard,ShoppingBag,ArrowLeftRight,Package,RefreshCcw,Users,PanelTop,Link2,Landmark,WalletCards,Trophy,Sparkles,FileBarChart,Settings,Menu,ChevronsLeft,ChevronsRight,Bell,Sun,Moon,X,ChevronDown,LogOut,Store,PlugZap,Crown,FlaskConical } from 'lucide-react';
import { cn } from '../lib/utils'; import { useDemoStore } from '../store/useDemoStore'
import { NotificationBell } from './notifications/NotificationBell'
import { SearchInput } from './common/SearchInput'
import { AvatarUploader } from './profile/AvatarUploader'
import { SphexPayLogo } from './branding/SphexPayLogo'
import { useAuth } from '../hooks/useAuth'
import { useNotificationAudio } from '../hooks/useNotificationAudio'
import { useDashboardData } from '../providers/DashboardDataProvider'
const items=[['Dashboard','/app',LayoutDashboard],['Vendas','/app/vendas',ShoppingBag],['Transações','/app/transacoes',ArrowLeftRight],['Produtos','/app/produtos',Package],['Vitrine','/app/vitrine',Store],['Assinaturas','/app/assinaturas',RefreshCcw],['Clientes','/app/clientes',Users],['Checkout','/app/checkout',PanelTop],['Links de pagamento','/app/links',Link2],['Financeiro','/app/financeiro',Landmark],['Saques','/app/saques',WalletCards],['Integrações','/app/integracoes',PlugZap],['Premiações','/app/premiacoes',Trophy],['Inteligência artificial','/app/assistente',Sparkles],['Relatórios','/app/relatorios',FileBarChart],['Notificações','/app/notificacoes',Bell],['Configurações','/app/configuracoes',Settings]] as const
export function Layout(){useNotificationAudio();const [collapsed,setCollapsed]=useState(false),[mobile,setMobile]=useState(false),[demoMessage,setDemoMessage]=useState(''),menuButton=useRef<HTMLButtonElement>(null),wasMobile=useRef(false);const {theme,setTheme}=useDemoStore(),{signOut,user}=useAuth(),demo=useDashboardData(),navigate=useNavigate();const loc=useLocation();const title=items.find(i=>i[1]===loc.pathname)?.[0]||'SphexPay',logout=async()=>{try{await signOut()}finally{navigate('/',{replace:true})}}
 useEffect(()=>{const escape=(event:KeyboardEvent)=>{if(event.key==='Escape')setMobile(false)};addEventListener('keydown',escape);return()=>removeEventListener('keydown',escape)},[])
 useEffect(()=>{document.body.style.overflow=mobile?'hidden':'';if(wasMobile.current&&!mobile)menuButton.current?.focus();wasMobile.current=mobile;return()=>{document.body.style.overflow=''}},[mobile])
 return <div className="min-h-screen app-shell"><aside id="app-navigation" aria-label="Menu principal" className={cn('fixed inset-y-0 left-0 z-50 bg-[var(--panel)] border-r border-[var(--line)] transition-all duration-300 flex flex-col',collapsed?'w-[78px]':'w-[250px]',mobile?'translate-x-0':'max-lg:-translate-x-full')}>
  <div className="sidebar-brand"><SphexPayLogo showName={!collapsed} priority/><button onClick={()=>setMobile(false)} className="lg:hidden ml-auto" aria-label="Fechar menu"><X/></button></div>
  <div className="competition-sidebar-slot"><NavLink to="/app/competicao" title={collapsed?'Competição':undefined} onClick={()=>setMobile(false)} className={({isActive})=>cn('competition-sidebar-item',isActive&&'active')}><Crown size={18}/>{!collapsed&&<span>Competição<small>iPhone 17 Pro Max</small></span>}</NavLink></div>
  <nav className="flex-1 overflow-y-auto scrollbar p-3 space-y-1">{items.map(([label,path,Icon])=><NavLink key={path} to={path} aria-label={label} title={collapsed?label:undefined} onClick={()=>setMobile(false)} className={({isActive})=>cn('flex items-center gap-3 h-10 px-3 rounded-xl text-[13px] font-semibold transition-colors',isActive?'bg-[var(--orange-soft)] orange':'muted hover:bg-[var(--panel-2)] hover:text-[var(--text)]')}><Icon size={18}/>{!collapsed&&<span>{label}</span>}</NavLink>)}</nav>
  <div className="p-3 border-t border-[var(--line)] hidden lg:grid gap-1"><button className="btn btn-ghost w-full" onClick={logout} aria-label="Sair da conta"><LogOut size={18}/>{!collapsed&&'Sair'}</button><button className="btn btn-ghost w-full" onClick={()=>setCollapsed(!collapsed)}>{collapsed?<ChevronsRight size={18}/>:<><ChevronsLeft size={18}/> Recolher</>}</button></div>
 </aside>{mobile&&<button className="app-menu-backdrop fixed inset-0 bg-black/50 z-40 lg:hidden" aria-label="Fechar menu" onClick={()=>setMobile(false)}/>}<div className={cn('transition-all',collapsed?'lg:ml-[78px]':'lg:ml-[250px]')}>
  <header className="app-header"><button ref={menuButton} className="btn icon-btn lg:hidden" aria-label="Abrir menu" aria-expanded={mobile} aria-controls="app-navigation" onClick={()=>setMobile(true)}><Menu size={19}/></button><SphexPayLogo className="header-brand"/><div className="mobile-page-title font-bold text-sm md:hidden truncate">{title}</div><SearchInput/><div className="header-actions">{demo.allowed&&<button className={`demo-toggle ${demo.active?'active':''}`} aria-pressed={demo.active} disabled={demo.loadingPermission} onClick={async()=>{const enabling=!demo.active;await demo.toggle();setDemoMessage(enabling?'Modo ativado.':'Dados reais restaurados.');setTimeout(()=>setDemoMessage(''),2200)}}><FlaskConical/><span>{demo.active?'Ativo':'Modo'}</span>{demo.active&&<i/>}</button>}<button className="btn icon-btn" onClick={()=>setTheme(theme==='light'?'dark':'light')} aria-label="Alternar tema">{theme==='light'?<Moon size={18}/>:<Sun size={18}/>}</button><NotificationBell/><div className="header-profile"><AvatarUploader compact/><div className="desktop-only"><p>{user?.user_metadata?.full_name||user?.email?.split('@')[0]||'Conta SphexPay'}</p><span>Player</span></div><ChevronDown size={14} className="muted desktop-only"/></div></div></header>
  {demoMessage&&<div className="demo-toast" role="status">{demoMessage}</div>}
  <main className="app-main p-4 md:p-7 max-w-[1600px] mx-auto"><Outlet/></main>
 </div></div>}
