import { useState } from 'react'; import { NavLink, Outlet, useLocation } from 'react-router-dom';
import { LayoutDashboard,ShoppingBag,ArrowLeftRight,Package,RefreshCcw,Users,PanelTop,Link2,Landmark,WalletCards,Trophy,Sparkles,FileBarChart,Settings,Menu,ChevronsLeft,ChevronsRight,Bell,Sun,Moon,X,ChevronDown } from 'lucide-react';
import { cn } from '../lib/utils'; import { useDemoStore } from '../store/useDemoStore'
import { NotificationBell } from './notifications/NotificationBell'; import { useRealtimeSales } from '../hooks/useRealtimeSales'
import { SearchInput } from './common/SearchInput'
import { AvatarUploader } from './profile/AvatarUploader'
const items=[['Visão geral','/',LayoutDashboard],['Vendas','/vendas',ShoppingBag],['Transações','/transacoes',ArrowLeftRight],['Produtos','/produtos',Package],['Assinaturas','/assinaturas',RefreshCcw],['Clientes','/clientes',Users],['Checkout','/checkout',PanelTop],['Links de pagamento','/links',Link2],['Financeiro','/financeiro',Landmark],['Saques','/saques',WalletCards],['Premiações','/premiacoes',Trophy],['Inteligência artificial','/assistente',Sparkles],['Relatórios','/relatorios',FileBarChart],['Notificações','/notificacoes',Bell],['Configurações','/configuracoes',Settings]] as const
export function Layout(){useRealtimeSales();const [collapsed,setCollapsed]=useState(false),[mobile,setMobile]=useState(false);const {theme,setTheme}=useDemoStore();const loc=useLocation();const title=items.find(i=>i[1]===loc.pathname)?.[0]||'SphexPay'
 return <div className="min-h-screen"><aside className={cn('fixed inset-y-0 left-0 z-50 bg-[var(--panel)] border-r border-[var(--line)] transition-all duration-300 flex flex-col',collapsed?'w-[78px]':'w-[250px]',mobile?'translate-x-0':'max-lg:-translate-x-full')}>
  <div className="h-[72px] flex items-center px-5 border-b border-[var(--line)]"><div className="w-9 h-9 rounded-xl bg-[var(--orange)] text-white grid place-items-center font-black text-lg shrink-0">S</div>{!collapsed&&<span className="font-extrabold text-xl ml-3 tracking-[-.04em]">Sphex<span className="orange">Pay</span></span>}<button onClick={()=>setMobile(false)} className="lg:hidden ml-auto"><X/></button></div>
  <nav className="flex-1 overflow-y-auto scrollbar p-3 space-y-1">{items.map(([label,path,Icon])=><NavLink key={path} to={path} onClick={()=>setMobile(false)} className={({isActive})=>cn('flex items-center gap-3 h-10 px-3 rounded-xl text-[13px] font-semibold transition-colors',isActive?'bg-[var(--orange-soft)] orange':'muted hover:bg-[var(--panel-2)] hover:text-[var(--text)]')}><Icon size={18}/>{!collapsed&&<span>{label}</span>}</NavLink>)}</nav>
  <div className="p-3 border-t border-[var(--line)] hidden lg:block"><button className="btn btn-ghost w-full" onClick={()=>setCollapsed(!collapsed)}>{collapsed?<ChevronsRight size={18}/>:<><ChevronsLeft size={18}/> Recolher</>}</button></div>
 </aside>{mobile&&<div className="fixed inset-0 bg-black/50 z-40 lg:hidden" onClick={()=>setMobile(false)}/>}<div className={cn('transition-all',collapsed?'lg:ml-[78px]':'lg:ml-[250px]')}>
  <header className="app-header"><button className="btn icon-btn lg:hidden" aria-label="Abrir menu" onClick={()=>setMobile(true)}><Menu size={19}/></button><div className="font-bold text-sm md:hidden truncate">{title}</div><SearchInput/><div className="header-actions"><button className="btn icon-btn" onClick={()=>setTheme(theme==='light'?'dark':'light')} aria-label="Alternar tema">{theme==='light'?<Moon size={18}/>:<Sun size={18}/>}</button><NotificationBell/><div className="header-profile"><AvatarUploader compact/><div className="desktop-only"><p>Ronald Rodriguez</p><span>Player</span></div><ChevronDown size={14} className="muted desktop-only"/></div></div></header>
  <main className="p-4 md:p-7 max-w-[1600px] mx-auto"><Outlet/></main>
 </div></div>}
