import type { ReactNode } from 'react'; import { createPortal } from 'react-dom'; import { LoaderCircle, Search, Inbox, X } from 'lucide-react'; import { cn } from '../lib/utils'
export const Card=({children,className=''}:{children:ReactNode,className?:string})=><div className={cn('panel',className)}>{children}</div>
export const PageTitle=({title,subtitle,action}:{title:string,subtitle:string,action?:ReactNode})=><div className="flex flex-col sm:flex-row sm:items-end justify-between gap-4 mb-6"><div><h1 className="text-2xl md:text-[28px] font-bold tracking-[-.04em]">{title}</h1><p className="muted text-sm mt-1">{subtitle}</p></div>{action}</div>
export const SearchBox=({value,onChange,placeholder='Buscar...'}:{value:string,onChange:(v:string)=>void,placeholder?:string})=><label className="relative block"><Search size={16} className="absolute left-3 top-1/2 -translate-y-1/2 muted"/><input className="input pl-9" value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder}/>{value&&<button onClick={()=>onChange('')} className="absolute right-3 top-1/2 -translate-y-1/2 muted" aria-label="Limpar"><X size={15}/></button>}</label>
export const StatusBadge=({status}:{status:string})=><span className={cn('badge',status==='Aprovado'||status==='Ativo'||status==='Ativa'||status==='Concluído'?'badge-ok':status==='Recusado'||status==='Reembolsado'||status==='Inadimplente'?'badge-bad':status==='Pendente'||status==='Processando'?'badge-warn':'badge-info')}>{status}</span>
export const Empty=({text='Nenhum registro encontrado'}:{text?:string})=><div className="py-14 text-center"><Inbox className="mx-auto muted mb-3"/><p className="muted text-sm">{text}</p></div>
export const Loading=()=> <div className="py-14 flex justify-center"><LoaderCircle className="animate-spin orange"/></div>
export const Avatar=({name}:{name:string})=><div className="w-9 h-9 rounded-full bg-[var(--orange-soft)] orange grid place-items-center text-xs font-bold shrink-0">{name.split(' ').slice(0,2).map(x=>x[0]).join('')}</div>
export const Modal=({title,children,onClose}:{title:string,children:ReactNode,onClose:()=>void})=>createPortal(<div className="fixed inset-0 z-[100] bg-black/55 backdrop-blur-sm grid place-items-center p-4" onMouseDown={onClose}><div className="panel w-full max-w-xl max-h-[90vh] overflow-auto p-5" role="dialog" aria-modal="true" aria-label={title} onMouseDown={e=>e.stopPropagation()}><div className="flex items-center justify-between mb-5"><h2 className="font-bold text-lg">{title}</h2><button className="btn btn-ghost icon-btn" aria-label="Fechar" onClick={onClose}><X size={19}/></button></div>{children}</div></div>,document.body)
