import { BellRing,CalendarClock,CheckCircle2,Pause,Play,RotateCcw,Save,Send,Square,Volume2,Zap } from 'lucide-react'
import { useMemo,useState } from 'react'
import { useNotificationGenerator } from '../../hooks/useNotificationGenerator'
import { defaultGeneratorConfig,generatorTypes,intervalMilliseconds,type GeneratorConfig,type GeneratorMode, type ValueLabel } from '../../lib/notificationGenerator'
import { notificationTitles } from '../../lib/notificationCatalog'
import { audioService } from '../../services/audioService'
import { NotificationGeneratorPreview } from './NotificationGeneratorPreview'
import { NotificationGeneratorTemplates } from './NotificationGeneratorTemplates'
import { NotificationGeneratorHistory } from './NotificationGeneratorHistory'

const modes:[GeneratorMode,string,string][]=[['single','Notificação única','Um único disparo'],['batch','Disparo em lote','Quantidade e intervalo definidos'],['scheduled','Agendado','Inicia em uma data específica'],['recurring','Recorrente','Repete até o limite ou interrupção'],['demo','Simulação / demo','Somente visual, sem Push']]
const valueLabels:ValueLabel[]=['Sua comissão','Valor','Total','Recebido','Lucro','Faturamento']
const quickIntervals:[number,string][]=[[1,'1 s'],[3,'3 s'],[5,'5 s'],[10,'10 s'],[30,'30 s'],[60,'1 min'],[300,'5 min'],[600,'10 min'],[1800,'30 min'],[3600,'1 h'],[7200,'2 h']]
const quickQuantities=[1,5,10,20,50,100]
export function NotificationGeneratorPanel(){
 const generator=useNotificationGenerator(),{config,setConfig,status,sent,message}=generator,[presetName,setPresetName]=useState(''),running=status==='running'||status==='scheduled',patch=(values:Partial<GeneratorConfig>)=>setConfig(current=>({...current,...values}))
 const duration=useMemo(()=>config.continuous?null:Math.max(0,(config.quantity-sent)*intervalMilliseconds(config)),[config,sent]),progress=config.continuous?0:Math.min(100,sent/config.quantity*100)
 const selectType=(type:typeof generatorTypes[number])=>patch({types:[type],title:notificationTitles[type]})
 const setQuickInterval=(seconds:number)=>seconds>=3600?patch({intervalValue:seconds/3600,intervalUnit:'hours'}):seconds>=60?patch({intervalValue:seconds/60,intervalUnit:'minutes'}):patch({intervalValue:seconds,intervalUnit:'seconds'})
 return <div className="notification-generator"><header className="generator-hero"><div><span><Zap/> GERADOR INTELIGENTE</span><h2>Crie campanhas de notificações com precisão.</h2><p>Personalize, simule e programe alertas usando os canais já conectados à SphexPay.</p></div><dl><div><dt>Enviadas nesta execução</dt><dd>{sent}</dd></div><div><dt>Status</dt><dd>{status==='running'?'Em execução':status==='scheduled'?'Agendada':status==='paused'?'Pausada':'Pronto'}</dd></div><div><dt>Estimativa</dt><dd>{duration===null?'Contínua':duration<60000?`${Math.ceil(duration/1000)} s`:`${Math.ceil(duration/60000)} min`}</dd></div></dl></header>
 <NotificationGeneratorPreview config={config}/>
 <div className="generator-main-grid"><div className="generator-editor">
  <Section eyebrow="CONTEÚDO" title="Configuração da mensagem"><label><span className="label">Tipo principal</span><select className="input" value={config.types[0]} onChange={event=>selectType(event.target.value as typeof generatorTypes[number])}>{generatorTypes.map(type=><option key={type} value={type}>{notificationTitles[type]}</option>)}</select></label><label><span className="label">Título</span><input aria-label="Título da notificação" className="input" maxLength={70} value={config.title} onChange={event=>patch({title:event.target.value})}/></label><label><span className="label">Texto livre opcional</span><input className="input" maxLength={120} placeholder="Deixe vazio para usar a linha de valor" value={config.customBody} onChange={event=>patch({customBody:event.target.value})}/></label><div className="generator-field-grid"><label><span className="label">Tipo da linha</span><select className="input" value={config.valueLabel} onChange={event=>patch({valueLabel:event.target.value as ValueLabel})}>{valueLabels.map(value=><option key={value}>{value}:</option>)}</select></label><label><span className="label">Valor</span><input aria-label="Valor da notificação" className="input" type="number" min="0" step=".01" value={config.value} onChange={event=>patch({value:Number(event.target.value)})}/></label><label><span className="label">Moeda</span><select className="input" value={config.currency} onChange={event=>patch({currency:event.target.value as GeneratorConfig['currency']})}><option>BRL</option><option>USD</option><option>EUR</option></select></label><label><span className="label">Horário simulado</span><input className="input" disabled={!config.showTime} value={config.simulatedTime} onChange={event=>patch({simulatedTime:event.target.value})}/></label></div><Toggle label="Mostrar horário" checked={config.showTime} onChange={showTime=>patch({showTime})}/></Section>
  <Section eyebrow="VARIAÇÃO AUTOMÁTICA" title="Dados inteligentes"><Toggle label="Ativar variação automática" checked={config.variation} onChange={variation=>patch({variation})}/>{config.variation&&<><div className="generator-field-grid"><NumberField label="Valor mínimo" value={config.minValue} onChange={minValue=>patch({minValue})}/><NumberField label="Valor máximo" value={config.maxValue} onChange={maxValue=>patch({maxValue})}/></div><Toggle label="Não repetir valores iguais" checked={config.avoidRepeatedValues} onChange={avoidRepeatedValues=>patch({avoidRepeatedValues})}/><Toggle label="Alternar automaticamente tipos" checked={config.rotateTypes} onChange={rotateTypes=>patch({rotateTypes})}/><Toggle label="Alternar BRL, USD e EUR" checked={config.rotateCurrencies} onChange={rotateCurrencies=>patch({rotateCurrencies})}/><div className="generator-type-checks">{generatorTypes.map(type=><label key={type}><input type="checkbox" checked={config.types.includes(type)} onChange={event=>patch({types:event.target.checked?[...new Set([...config.types,type])]:config.types.filter(item=>item!==type)})}/><span>{notificationTitles[type]}</span></label>)}</div></>}</Section>
  <Section eyebrow="SOM" title="Identidade sonora"><Toggle label="Ativar som" checked={config.sound} onChange={sound=>patch({sound})}/><label><span className="label">Volume: {Math.round(config.volume*100)}%</span><input aria-label="Volume do gerador" className="generator-range" type="range" min="0" max="1" step=".05" value={config.volume} onChange={event=>patch({volume:Number(event.target.value)})}/></label><div className="generator-field-grid"><label><span className="label">Som</span><select className="input" value={config.soundStyle} onChange={event=>patch({soundStyle:event.target.value as GeneratorConfig['soundStyle']})}><option value="signal">Signal</option><option value="pulse">Pulse</option><option value="soft">Soft</option></select></label><button className="btn generator-inline-action" onClick={()=>void audioService.playSale(config.volume,config.soundStyle,`generator-sound-${Date.now()}`)}><Volume2/> Testar som</button></div></Section>
 </div><aside className="generator-controls">
  <Section eyebrow="MODO DE ENVIO" title="Estratégia da campanha"><div className="generator-mode-grid">{modes.map(([value,title,description])=><button className={config.mode===value?'active':''} key={value} onClick={()=>patch({mode:value,quantity:value==='single'?1:config.quantity})}><i/><span><b>{title}</b><small>{description}</small></span></button>)}</div><label><span className="label">Destino</span><select className="input" value={config.destination} onChange={event=>patch({destination:event.target.value as GeneratorConfig['destination']})}><option value="inapp">Somente dentro do gateway</option><option value="system">Navegador / sistema</option><option value="both">Gateway e sistema</option></select></label></Section>
  <Section eyebrow="FREQUÊNCIA" title="Quantidade e intervalo"><div className="generator-quick-row">{quickQuantities.map(value=><button className={config.quantity===value?'active':''} onClick={()=>patch({quantity:value})} key={value}>{value}</button>)}</div><NumberField label="Quantidade de notificações" value={config.quantity} integer onChange={quantity=>patch({quantity})}/><div className="generator-quick-row intervals">{quickIntervals.map(([seconds,label])=><button onClick={()=>setQuickInterval(seconds)} key={seconds}>{label}</button>)}</div><div className="generator-field-grid"><NumberField label="Intervalo" value={config.intervalValue} onChange={intervalValue=>patch({intervalValue})}/><label><span className="label">Unidade</span><select className="input" value={config.intervalUnit} onChange={event=>patch({intervalUnit:event.target.value as GeneratorConfig['intervalUnit']})}><option value="seconds">Segundos</option><option value="minutes">Minutos</option><option value="hours">Horas</option></select></label></div><Toggle label="Continuar até eu parar" checked={config.continuous} onChange={continuous=>patch({continuous})}/></Section>
  {(config.mode==='scheduled'||config.mode==='recurring')&&<Section eyebrow="AGENDA" title="Janela de execução"><label><span className="label">Início</span><input aria-label="Data e hora de início" className="input" type="datetime-local" value={config.startAt} onChange={event=>patch({startAt:event.target.value})}/></label><label><span className="label">Fim opcional</span><input aria-label="Data e hora de fim" className="input" type="datetime-local" value={config.endAt} onChange={event=>patch({endAt:event.target.value})}/></label></Section>}
  <Section eyebrow="PRESET" title="Salvar configuração"><div className="generator-save-preset"><input aria-label="Nome do preset" className="input" placeholder="Nome do preset" value={presetName} onChange={event=>setPresetName(event.target.value)}/><button className="btn" onClick={()=>{generator.savePreset(presetName);setPresetName('')}}><Save/> Salvar preset</button></div></Section>
 </aside></div>
 <div className="generator-command-center"><div><span>Progresso da campanha</span><b>{config.continuous?`${sent} enviados`:`${sent} de ${config.quantity}`}</b><i><em style={{width:`${progress}%`}}/></i></div><div>{!running&&status!=='paused'&&<><button className="btn" onClick={()=>void generator.test()}><BellRing/> Testar preview</button><button className="btn btn-primary" onClick={()=>generator.begin({...config,mode:'single',quantity:1})}><Send/> Enviar agora</button><button className="btn btn-primary" onClick={()=>generator.begin()}>{config.mode==='scheduled'?<CalendarClock/>:<Play/>}{config.mode==='scheduled'?'Agendar':'Iniciar sequência'}</button></>}{running&&status==='running'&&<button className="btn" onClick={generator.pause}><Pause/> Pausar</button>}{status==='paused'&&<button className="btn btn-primary" onClick={generator.resume}><Play/> Retomar</button>}{(running||status==='paused')&&<button className="btn text-red-500" onClick={generator.stop}><Square/> Parar</button>}<button className="btn btn-ghost" disabled={running} onClick={()=>setConfig({...defaultGeneratorConfig})}><RotateCcw/> Restaurar padrão</button></div>{message&&<p role="status"><CheckCircle2/>{message}</p>}</div>
 <NotificationGeneratorTemplates config={config} onChange={setConfig} presets={generator.presets} onDelete={generator.deletePreset} onDuplicate={generator.duplicatePreset}/>
 <NotificationGeneratorHistory history={generator.history} onClear={()=>generator.setHistory([])} onReuse={setConfig}/>
 </div>
}
function Section({eyebrow,title,children}:{eyebrow:string;title:string;children:React.ReactNode}){return <section className="generator-section"><div className="generator-section-head"><div><span>{eyebrow}</span><h3>{title}</h3></div></div><div className="generator-section-body">{children}</div></section>}
function Toggle({label,checked,onChange}:{label:string;checked:boolean;onChange:(value:boolean)=>void}){return <label className="setting-toggle"><span>{label}</span><input type="checkbox" checked={checked} onChange={event=>onChange(event.target.checked)}/><i/></label>}
function NumberField({label,value,integer=false,onChange}:{label:string;value:number;integer?:boolean;onChange:(value:number)=>void}){return <label><span className="label">{label}</span><input className="input" type="number" min="0" step={integer?1:.01} value={value} onChange={event=>onChange(Number(event.target.value))}/></label>}
