import { Copy,RotateCcw,Search,Trash2 } from 'lucide-react'
import { useMemo,useState } from 'react'
import { formatGeneratorValue,type GeneratorConfig,type GeneratorHistory } from '../../lib/notificationGenerator'

const statusLabel={completed:'Concluída',running:'Em execução',paused:'Pausada',cancelled:'Cancelada',scheduled:'Agendada',failed:'Falhou'}
export function NotificationGeneratorHistory({history,onClear,onReuse}:{history:GeneratorHistory[];onClear:()=>void;onReuse:(config:GeneratorConfig)=>void}){
 const [query,setQuery]=useState(''),filtered=useMemo(()=>history.filter(item=>`${item.title} ${item.currency} ${item.status}`.toLowerCase().includes(query.toLowerCase())),[history,query])
 return <section className="generator-history"><div className="generator-section-head"><div><span>ATIVIDADE</span><h3>Histórico de disparos</h3></div><button className="btn btn-ghost" onClick={onClear} disabled={!history.length}><Trash2/> Limpar</button></div><label className="generator-history-search"><Search/><input aria-label="Buscar no histórico do gerador" placeholder="Buscar campanha, moeda ou status" value={query} onChange={event=>setQuery(event.target.value)}/></label><div className="generator-history-list">{filtered.slice(0,20).map(item=><article key={item.id}><div><i className={item.status}/><span><b>{item.title}</b><small>{new Date(item.createdAt).toLocaleString('pt-BR')} · {item.destination}</small></span></div><dl><div><dt>Valor</dt><dd>{formatGeneratorValue(item.value,item.currency)}</dd></div><div><dt>Progresso</dt><dd>{item.sent}/{item.requested||'∞'}</dd></div><div><dt>Status</dt><dd>{statusLabel[item.status]}</dd></div></dl><div><button aria-label={`Reenviar ${item.title}`} onClick={()=>onReuse({...item.config,mode:'single',quantity:1})}><RotateCcw/></button><button aria-label={`Duplicar configuração ${item.title}`} onClick={()=>onReuse({...item.config})}><Copy/></button></div></article>)}{!filtered.length&&<p>Nenhum disparo encontrado.</p>}</div></section>
}
