import type { RealtimeChannel,SupabaseClient } from '@supabase/supabase-js'
import { supabase } from '../../lib/supabase'
import type { FeedMode,SocialConversation,SocialMessage,SocialNotice,SocialPost,SocialProfile } from './types'

const client=()=>{if(!supabase)throw new Error('SOCIAL_UNAVAILABLE');return supabase}
const signedMediaCache=new Map<string,{url:string;expiresAt:number}>()
const profile=(r:Record<string,unknown>):SocialProfile=>({userId:String(r.user_id),username:String(r.username),displayName:String(r.display_name),bio:String(r.bio||''),avatarUrl:r.avatar_url?String(r.avatar_url):undefined,coverUrl:r.cover_url?String(r.cover_url):undefined,website:r.website?String(r.website):undefined,location:r.location?String(r.location):undefined,badges:Array.isArray(r.badges)?r.badges.map(String):[]})
const post=(r:Record<string,unknown>,me:string):SocialPost=>{const author=(r.social_profiles||{}) as Record<string,unknown>,media=(r.social_post_media||[]) as Record<string,unknown>[],likes=(r.social_likes||[]) as Record<string,unknown>[],bookmarks=(r.social_bookmarks||[]) as Record<string,unknown>[],follows=(r.social_follows||[]) as Record<string,unknown>[];return{id:String(r.id),authorId:String(r.author_id),body:String(r.body||''),createdAt:String(r.created_at),updatedAt:String(r.updated_at),replyToId:r.reply_to_id?String(r.reply_to_id):undefined,repostOfId:r.repost_of_id?String(r.repost_of_id):undefined,profile:profile(author),media:media.map(x=>({id:String(x.id),type:String(x.media_type) as 'image'|'video',url:String(x.url)})),likes:likes.length,comments:Number(r.comment_count||0),reposts:Number(r.repost_count||0),liked:likes.some(x=>x.user_id===me),bookmarked:bookmarks.some(x=>x.user_id===me),following:follows.some(x=>x.follower_id===me)}}
const postSelect='id,author_id,body,created_at,updated_at,reply_to_id,repost_of_id,social_profiles!social_posts_author_id_fkey(*),social_post_media(id,media_type,url),social_likes(user_id),social_bookmarks(user_id)'
export const usernameFrom=(user:{id:string;email?:string;user_metadata?:Record<string,unknown>})=>{const base=String(user.user_metadata?.user_name||user.user_metadata?.full_name||user.email?.split('@')[0]||'creator').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9_]/g,'_').replace(/_+/g,'_').slice(0,18).replace(/^_+|_+$/g,'');return`${base.length>=3?base:'creator'}_${user.id.slice(0,5)}`}
export const socialService={
 async ensureProfile(user:{id:string;email?:string;user_metadata?:Record<string,unknown>}){const c=client(),{data}=await c.from('social_profiles').select('*').eq('user_id',user.id).maybeSingle();if(data)return profile(data);const row={user_id:user.id,username:usernameFrom(user),display_name:String(user.user_metadata?.full_name||user.email?.split('@')[0]||'Criador Sphex')};const {data:created,error}=await c.from('social_profiles').insert(row).select().single();if(error)throw error;return profile(created)},
 async updateProfile(userId:string,input:Partial<SocialProfile>){const payload={username:input.username?.toLowerCase().trim(),display_name:input.displayName?.trim(),bio:input.bio?.trim(),website:input.website?.trim()||null,location:input.location?.trim()||null,avatar_url:input.avatarUrl||null,cover_url:input.coverUrl||null,updated_at:new Date().toISOString()};const {data,error}=await client().from('social_profiles').update(payload).eq('user_id',userId).select().single();if(error)throw error;return profile(data)},
 async getProfile(username:string){const {data,error}=await client().from('social_profiles').select('*').eq('username',username.toLowerCase()).single();if(error)throw error;return profile(data)},
 async feed(me:string,mode:FeedMode,cursor?:string,tag?:string,authorId?:string){let q=client().from('social_posts').select(postSelect).eq('status','published').is('reply_to_id',null).order('created_at',{ascending:false}).order('id',{ascending:false}).limit(15);const [{data:f},{data:m}]=await Promise.all([client().from('social_follows').select('following_id').eq('follower_id',me),client().from('social_mutes').select('muted_user_id').eq('user_id',me)]),following=(f||[]).map(x=>x.following_id),muted=(m||[]).map(x=>x.muted_user_id);if(cursor)q=q.lt('created_at',cursor);if(authorId)q=q.eq('author_id',authorId);else if(muted.length)q=q.not('author_id','in',`(${muted.join(',')})`);if(mode==='following')q=q.in('author_id',following.concat(me));if(mode==='saved'){const {data:b}=await client().from('social_bookmarks').select('post_id').eq('user_id',me);const ids=(b||[]).map(x=>x.post_id);if(!ids.length)return[];q=q.in('id',ids)}if(mode==='tag'&&tag)q=q.ilike('body',`%#${tag.replace(/[^a-z0-9_]/gi,'')}%`);const {data,error}=await q;if(error)throw error;return(data||[]).map(x=>{const mapped=post(x as unknown as Record<string,unknown>,me);mapped.following=following.includes(mapped.authorId);return mapped})},
 async createPost(body:string,replyTo?:string,repostOf?:string){const {data,error}=await client().rpc('social_create_post',{p_body:body,p_reply_to:replyTo||null,p_repost_of:repostOf||null});if(error)throw error;return String(data)},
 async getPost(me:string,id:string){const {data,error}=await client().from('social_posts').select(postSelect).eq('id',id).eq('status','published').single();if(error)throw error;return post(data as unknown as Record<string,unknown>,me)},
 async editPost(userId:string,id:string,body:string){const {error}=await client().from('social_posts').update({body:body.trim(),updated_at:new Date().toISOString()}).eq('id',id).eq('author_id',userId);if(error)throw error},
 async deletePost(userId:string,id:string){const {error}=await client().from('social_posts').update({status:'deleted',deleted_at:new Date().toISOString(),body:''}).eq('id',id).eq('author_id',userId);if(error)throw error},
 async toggle(table:'social_likes'|'social_bookmarks',userId:string,postId:string,on:boolean){const q=client().from(table);const {error}=on?await q.insert({user_id:userId,post_id:postId}):await q.delete().eq('user_id',userId).eq('post_id',postId);if(error)throw error},
 async follow(userId:string,otherId:string,on:boolean){const q=client().from('social_follows');const {error}=on?await q.insert({follower_id:userId,following_id:otherId}):await q.delete().eq('follower_id',userId).eq('following_id',otherId);if(error)throw error},
 async relationship(table:'social_blocks'|'social_mutes',userId:string,otherId:string,on:boolean){if(table==='social_blocks'){const q=client().from('social_blocks'),{error}=on?await q.insert({blocker_id:userId,blocked_id:otherId}):await q.delete().eq('blocker_id',userId).eq('blocked_id',otherId);if(error)throw error}else{const q=client().from('social_mutes'),{error}=on?await q.insert({user_id:userId,muted_user_id:otherId}):await q.delete().eq('user_id',userId).eq('muted_user_id',otherId);if(error)throw error}},
 async report(userId:string,targetId:string,reason:string,details:string){const {error}=await client().from('social_reports').insert({reporter_id:userId,target_type:'post',target_id:targetId,reason,details});if(error)throw error},
 async discover(me:string,query=''){let q=client().from('social_profiles').select('*').neq('user_id',me).limit(10);if(query)q=q.or(`username.ilike.%${query.replace(/[,()%]/g,'')}%,display_name.ilike.%${query.replace(/[,()%]/g,'')}%`);const {data,error}=await q;if(error)throw error;return(data||[]).map(profile)},
 async ranking(me:string,category:string){const {data,error}=await client().rpc('social_ranking',{category,exclude_user:me});if(error)throw error;return(data||[]).map(profile)},
 async searchPosts(me:string,query:string){const term=query.trim().slice(0,80);if(term.length<2)return[];const {data,error}=await client().rpc('social_search_posts',{search_query:term}).select(postSelect);if(error)throw error;const rows=(Array.isArray(data)?data:data?[data]:[]) as unknown as Record<string,unknown>[];return rows.map(x=>post(x,me))},
 async comments(me:string,postId:string){const {data,error}=await client().from('social_posts').select(postSelect).eq('reply_to_id',postId).eq('status','published').order('created_at').limit(100);if(error)throw error;return(data||[]).map(x=>post(x as unknown as Record<string,unknown>,me))},
 async notifications(){const {data,error}=await client().from('social_notifications').select('*,actor:social_profiles!social_notifications_actor_id_fkey(*)').order('created_at',{ascending:false}).limit(50);if(error)throw error;return(data||[]).map(r=>({id:r.id,recipientId:r.recipient_id,actorId:r.actor_id,type:r.type,entityType:r.entity_type,entityId:r.entity_id,readAt:r.read_at,createdAt:r.created_at,actor:r.actor?profile(r.actor):undefined} as SocialNotice))},
 async readNotifications(ids?:string[]){let q=client().from('social_notifications').update({read_at:new Date().toISOString()}).is('read_at',null);if(ids?.length)q=q.in('id',ids);const {error}=await q;if(error)throw error},
 async conversations(me:string){const {data,error}=await client().from('social_conversation_members').select('conversation_id,last_read_at,social_conversations(id,updated_at,social_conversation_members(user_id,social_profiles(*)),social_messages(created_at))').eq('user_id',me);if(error)throw error;return(data||[]).map((r:any)=>({id:r.social_conversations.id,updatedAt:r.social_conversations.updated_at,members:r.social_conversations.social_conversation_members.filter((m:any)=>m.user_id!==me).map((m:any)=>profile(m.social_profiles)),unread:r.social_conversations.social_messages.filter((m:any)=>!r.last_read_at||m.created_at>r.last_read_at).length} as SocialConversation))},
 async openConversation(otherId:string){const {data,error}=await client().rpc('social_open_conversation',{other_user:otherId});if(error)throw error;return String(data)},
 async messages(conversationId:string){const {data,error}=await client().from('social_messages').select('*').eq('conversation_id',conversationId).is('deleted_at',null).order('created_at').limit(100);if(error)throw error;return(data||[]).map(r=>({id:r.id,conversationId:r.conversation_id,senderId:r.sender_id,body:r.body,createdAt:r.created_at} as SocialMessage))},
 async sendMessage(userId:string,conversationId:string,body:string){const {data,error}=await client().from('social_messages').insert({sender_id:userId,conversation_id:conversationId,body:body.trim()}).select().single();if(error)throw error;return{id:data.id,conversationId:data.conversation_id,senderId:data.sender_id,body:data.body,createdAt:data.created_at} as SocialMessage},
 subscribe(table:'social_notifications'|'social_messages',filter:string,callback:(row?:Record<string,unknown>)=>void){return client().channel(`social:${table}:${filter}`).on('postgres_changes',{event:'INSERT',schema:'public',table,filter},payload=>callback(payload.new)).subscribe()},
 unsubscribe(channel?:RealtimeChannel){if(channel)void client().removeChannel(channel)},
 async signedUrl(path?:string){if(!path)return'';if(/^https?:\/\//i.test(path))return path;const cached=signedMediaCache.get(path);if(cached&&cached.expiresAt>Date.now())return cached.url;const {data,error}=await client().storage.from('social-media').createSignedUrl(path,300);if(error)throw error;signedMediaCache.set(path,{url:data.signedUrl,expiresAt:Date.now()+240000});return data.signedUrl},
 async upload(_userId:string,file:File,kind:'posts'|'avatars'|'covers',conversationId?:string){if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>10*1024*1024)throw new Error('INVALID_MEDIA');const body=new FormData();body.append('file',file);body.append('kind',kind);if(conversationId)body.append('conversationId',conversationId);const {data,error}=await client().functions.invoke('social-media-upload',{body});if(error||!data?.path)throw error||new Error('UPLOAD_FAILED');return String(data.path)}
}
export type SocialClient=SupabaseClient
