import { useEffect,useRef,useState } from 'react'
import { Activity,ArrowRight,ChevronLeft,ChevronRight,Gift,Layers3,Network,ShieldCheck } from 'lucide-react'
import { Link } from 'react-router-dom'
import { competitionConfig } from '../../config/competition'
import { SphexPayLogo } from '../branding/SphexPayLogo'

const slides=[
 {eyebrow:'SPHEXPAY PERFORMANCE',title:'Controle, performance e escala para o seu negócio digital.',copy:'Automação financeira, inteligência operacional e uma visão clara para decisões mais rápidas.',action:'Conhecer a plataforma',kind:'gateway' as const},
 {eyebrow:'COMPETIÇÃO SPHEXPAY',title:`${competitionConfig.promotionalTitle}.`,copy:competitionConfig.bannerDescription,action:'Ver regulamento',kind:'competition' as const}
]
export function OverviewHeroCarousel(){
 const [active,setActive]=useState(0),[paused,setPaused]=useState(false),touchStart=useRef<number|null>(null)
 useEffect(()=>{const reduced=matchMedia('(prefers-reduced-motion: reduce)');if(paused||reduced.matches)return;const timer=window.setInterval(()=>setActive(value=>(value+1)%slides.length),6500);return()=>window.clearInterval(timer)},[paused])
 const go=(index:number)=>setActive((index+slides.length)%slides.length)
 const finishSwipe=(clientX:number)=>{if(touchStart.current===null)return;const distance=clientX-touchStart.current;touchStart.current=null;setPaused(false);if(Math.abs(distance)>44)go(active+(distance<0?1:-1))}
 return <section className="overview-carousel spx-operation-hero" aria-roledescription="carrossel" aria-label="Destaques SphexPay" onMouseEnter={()=>setPaused(true)} onMouseLeave={()=>setPaused(false)} onFocusCapture={()=>setPaused(true)} onBlurCapture={event=>{if(!event.currentTarget.contains(event.relatedTarget))setPaused(false)}} onTouchStart={event=>{setPaused(true);touchStart.current=event.touches[0]?.clientX??null}} onTouchEnd={event=>finishSwipe(event.changedTouches[0]?.clientX??0)} onTouchCancel={()=>{touchStart.current=null;setPaused(false)}}>
  <div className="overview-track" style={{transform:`translateX(-${active*100}%)`}}>{slides.map((slide,index)=><article className={`overview-slide ${slide.kind}`} aria-hidden={active!==index} key={slide.title}><div className="overview-copy"><span>{slide.eyebrow}</span><h2>{slide.title}</h2><p>{slide.copy}</p>{slide.kind==='competition'?<Link className="overview-cta" tabIndex={active===index?0:-1} to="/app/competicao#regulamento">{slide.action}<ArrowRight/></Link>:<button type="button" tabIndex={active===index?0:-1}>{slide.action}<ArrowRight/></button>}</div>{slide.kind==='gateway'?<div className="gateway-art operation-core" aria-hidden="true"><div className="operation-orbit orbit-outer"><i/><i/></div><div className="operation-orbit orbit-inner"><i/></div><div className="operation-axis axis-horizontal"/><div className="operation-axis axis-vertical"/><div className="operation-brand"><SphexPayLogo className="hero-brand" showName={false}/><span>OPERATION CORE</span></div><div className="operation-node node-processing"><Activity/><span>PROCESSING</span><b>ACTIVE</b></div><div className="operation-node node-network"><Network/><span>NETWORK</span><b>STABLE</b></div><div className="operation-packet packet-one"/><div className="operation-packet packet-two"/><div className="art-stack operation-performance"><Layers3/><span>98,7%</span><small>Performance demonstrativa</small><i><b/></i></div><div className="operation-integrity"><ShieldCheck/><span>CORE STATUS</span><b>OPERATIONAL</b></div></div>:<div className="iphone-art" aria-hidden="true"><img className="competition-product-image" src={competitionConfig.image} alt=""/><div className="prize-seal"><Gift/><span>PRÊMIO</span></div></div>}</article>)}</div>
  <div className="overview-controls"><button type="button" aria-label="Banner anterior" onClick={()=>go(active-1)}><ChevronLeft/></button><div>{slides.map((_,index)=><button type="button" key={index} aria-label={`Exibir banner ${index+1}`} aria-current={active===index} className={active===index?'active':''} onClick={()=>go(index)}/>)}</div><button type="button" aria-label="Próximo banner" onClick={()=>go(active+1)}><ChevronRight/></button></div>
 </section>
}
