import {createClient} from '@supabase/supabase-js'

const api=process.env.API_URL,anon=process.env.PUBLISHABLE_KEY,service=process.env.SERVICE_ROLE_KEY
if(!api||!anon||!service)throw new Error('Supabase local não configurado')
const admin=createClient(api,service),password='Local-Mobile-Qa-Aa1!',stamp=Date.now(),created=[]
const makeUser=async(label)=>{const email=`mobile-${label}-${stamp}@example.invalid`,{data:{user},error}=await admin.auth.admin.createUser({email,password,email_confirm:true,user_metadata:{full_name:`Mobile ${label}`,onboarding_complete:true}});if(error)throw error;created.push(user.id);const client=createClient(api,anon),login=await client.auth.signInWithPassword({email,password});if(login.error)throw login.error;await client.from('social_profiles').insert({user_id:user.id,username:`mobile_${label}_${String(stamp).slice(-6)}`,display_name:`Mobile ${label}`});return{email,user,client,session:login.data.session}}
const delay=ms=>new Promise(resolve=>setTimeout(resolve,ms))
let socket,nextId=1
const runtimeErrors=[]
const pending=new Map()
const call=(method,params={})=>new Promise((resolve,reject)=>{const id=nextId++;pending.set(id,{resolve,reject});socket.send(JSON.stringify({id,method,params}))})
const evaluate=async expression=>{const response=await call('Runtime.evaluate',{expression,awaitPromise:true,returnByValue:true});if(response.result.exceptionDetails)throw new Error(response.result.exceptionDetails.text);return response.result.result.value}
const navigate=async path=>{const sameOrigin=await evaluate(`location.origin==='http://127.0.0.1:4173'`);if(sameOrigin){await evaluate(`history.pushState({},'',${JSON.stringify(path)});dispatchEvent(new PopStateEvent('popstate'))`)}else await call('Page.navigate',{url:`http://127.0.0.1:4173${path}`});await delay(1800)}
const waitForSocial=async()=>{for(let attempt=0;attempt<60;attempt++){if(await evaluate(`Boolean(document.querySelector('.social-page'))`))return;await delay(500)}throw new Error(`Social não montou em ${await evaluate('location.href')}: ${await evaluate('document.body.innerText.slice(0,500)')}`)}
try{
 const A=await makeUser('a'),B=await makeUser('b'),post=await A.client.rpc('social_create_post',{p_body:'Post para QA mobile',p_reply_to:null,p_repost_of:null}),conversation=await A.client.rpc('social_open_conversation',{other_user:B.user.id});if(post.error||conversation.error)throw post.error||conversation.error
 await A.client.from('social_messages').insert({conversation_id:conversation.data,sender_id:A.user.id,body:'Mensagem para validar chat mobile'})
 const targets=await fetch('http://127.0.0.1:9222/json').then(response=>response.json()),target=targets.find(item=>item.type==='page');if(!target)throw new Error('Brave CDP indisponível')
 socket=new WebSocket(target.webSocketDebuggerUrl);await new Promise((resolve,reject)=>{socket.onopen=resolve;socket.onerror=reject});socket.onmessage=event=>{const message=JSON.parse(event.data);if(message.method==='Runtime.exceptionThrown')runtimeErrors.push(message.params?.exceptionDetails?.exception?.description||message.params?.exceptionDetails?.text);if(message.id&&pending.has(message.id)){const item=pending.get(message.id);pending.delete(message.id);message.error?item.reject(new Error(message.error.message)):item.resolve(message)}}
 await call('Page.enable');await call('Runtime.enable');await navigate('/entrar')
 await evaluate(`localStorage.setItem('sb-localhost-auth-token',${JSON.stringify(JSON.stringify(A.session))});location.href='http://127.0.0.1:4173/app/social'`);await delay(1800);runtimeErrors.length=0
 const sizes=[[320,568],[360,800],[375,812],[390,844],[430,932]],viewports={}
 for(const [width,height] of sizes){await call('Emulation.setDeviceMetricsOverride',{width,height,deviceScaleFactor:2,mobile:true,screenWidth:width,screenHeight:height});await navigate('/app/social');await waitForSocial();viewports[width]=await evaluate(`(()=>{const page=document.querySelector('.social-page'),nav=document.querySelector('.social-mobile-nav'),discover=document.querySelector('.social-discover');return{social:Boolean(page),overflow:document.documentElement.scrollWidth<=innerWidth&&document.body.scrollWidth<=innerWidth,bottomNav:Boolean(nav)&&getComputedStyle(nav).display!=='none',discover:Boolean(discover)&&getComputedStyle(discover).display==='none',safe:Boolean(nav)&&getComputedStyle(nav).height.length>0,location:location.pathname}})()`)}
 const routes=['/app/social','/app/social/explore','/app/social/notifications','/app/social/messages','/app/social/saved','/app/social/ranking',`/app/social/@${A.client.auth.getUser?`mobile_a_${String(stamp).slice(-6)}`:''}`,`/app/social/post/${post.data}`],routeChecks=[],routeErrors={}
 await call('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:2,mobile:true,screenWidth:390,screenHeight:844})
 for(const route of routes){const before=runtimeErrors.length;await navigate(route);await waitForSocial();routeChecks.push(await evaluate(`Boolean(document.querySelector('.social-page'))&&document.documentElement.scrollWidth<=innerWidth`));if(runtimeErrors.length>before)routeErrors[route]=runtimeErrors.slice(before)}
 await navigate('/app/social/messages');await waitForSocial();for(let attempt=0;attempt<60;attempt++){if(await evaluate(`Boolean(document.querySelector('.social-messages>aside>button'))`))break;await delay(500)}await evaluate(`document.querySelector('.social-messages>aside>button')?.click()`);for(let attempt=0;attempt<60;attempt++){if(await evaluate(`Boolean(document.querySelector('.social-chat textarea'))`))break;await delay(500)}await evaluate(`document.querySelector('.social-chat textarea')?.focus()`);await call('Emulation.setDeviceMetricsOverride',{width:390,height:520,deviceScaleFactor:2,mobile:true,screenWidth:390,screenHeight:844});await delay(300)
 const keyboardDetails=await evaluate(`(()=>{const input=document.querySelector('.social-chat textarea'),send=document.querySelector('.social-chat form button'),chat=document.querySelector('.social-chat');if(!input||!send||!chat)return{pass:false,missing:true,path:location.href,text:document.body.innerText.slice(-500)};const viewport=visualViewport?.height||innerHeight;return{pass:input.getBoundingClientRect().bottom<=viewport&&send.getBoundingClientRect().bottom<=viewport&&chat.scrollWidth<=chat.clientWidth,inputBottom:input.getBoundingClientRect().bottom,sendBottom:send.getBoundingClientRect().bottom,viewport,chatWidth:chat.clientWidth,scrollWidth:chat.scrollWidth}})()`),keyboard=keyboardDetails.pass
 keyboardDetails.runtimeErrors=runtimeErrors.slice(-5);keyboardDetails.routeErrors=routeErrors
 const result={realBrowser:true,viewports,allRoutes:routeChecks.every(Boolean),chatKeyboard:keyboard,keyboardDetails,safeArea:Object.values(viewports).every(value=>value.safe),responsive:Object.values(viewports).every(value=>value.social&&value.overflow&&value.bottomNav&&value.discover)}
 if(!result.allRoutes||!result.chatKeyboard||!result.safeArea||!result.responsive)throw new Error(JSON.stringify(result))
 console.log(JSON.stringify(result,null,2));socket.close()
}finally{for(const id of created)await admin.auth.admin.deleteUser(id)}
