import { BrowserRouter,Navigate,Route,Routes } from 'react-router-dom'
import { Layout } from './components/Layout'
import Dashboard from './pages/Dashboard'
import { ProductsPage } from './pages/Commerce'
import { CheckoutPage,LinksPage,WithdrawalsPage } from './pages/Operations'
import Settings from './pages/Settings'
import NotificationsPage from './pages/Notifications'
import AssistantPage from './pages/Assistant'
import AwardsPage from './pages/Awards'
import LiveReports from './pages/LiveReports'
import FinancialHub from './pages/FinancialHub'
import { EditableCustomers,EditableSubscriptions } from './pages/EditableRecords'
import LiveSales from './pages/LiveSales'
export default function App(){return <BrowserRouter><Routes><Route element={<Layout/>}><Route index element={<Dashboard/>}/><Route path="vendas" element={<LiveSales/>}/><Route path="transacoes" element={<LiveSales transactions/>}/><Route path="produtos" element={<ProductsPage/>}/><Route path="assinaturas" element={<EditableSubscriptions/>}/><Route path="clientes" element={<EditableCustomers/>}/><Route path="checkout" element={<CheckoutPage/>}/><Route path="links" element={<LinksPage/>}/><Route path="financeiro" element={<FinancialHub/>}/><Route path="saques" element={<WithdrawalsPage/>}/><Route path="premiacoes" element={<AwardsPage/>}/><Route path="assistente" element={<AssistantPage/>}/><Route path="relatorios" element={<LiveReports/>}/><Route path="notificacoes" element={<NotificationsPage/>}/><Route path="configuracoes" element={<Settings/>}/><Route path="*" element={<Navigate to="/" replace/>}/></Route></Routes></BrowserRouter>}
