-- Sphex Social V1. Additive only; no legacy objects or commercial data are changed.
create extension if not exists pg_trgm with schema extensions;
create extension if not exists unaccent with schema extensions;
create or replace function public.social_normalize_search(value text) returns text language sql immutable strict parallel safe set search_path=public,extensions as $$select lower(extensions.unaccent('extensions.unaccent'::regdictionary,value))$$;

create table public.social_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  username text not null unique check (username = lower(username) and username ~ '^[a-z0-9_]{3,24}$'),
  display_name text not null check (char_length(display_name) between 1 and 80),
  bio text not null default '' check (char_length(bio) <= 280),
  avatar_url text, cover_url text, website text check (website is null or website ~ '^https://[^[:space:]]+$'), location text,
  badges text[] not null default '{}',
  created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
  constraint social_profile_reserved_username check (username <> all(array['admin','support','sphex','sphexpay','api','dashboard']))
);
create table public.social_posts (
  id uuid primary key default gen_random_uuid(), author_id uuid not null references public.social_profiles(user_id) on delete cascade,
  body text not null default '' check (char_length(body) <= 2000), visibility text not null default 'public' check (visibility in ('public','followers')),
  reply_to_id uuid references public.social_posts(id) on delete set null,
  repost_of_id uuid references public.social_posts(id) on delete set null,
  status text not null default 'published' check (status in ('published','deleted')),
  created_at timestamptz not null default now(), updated_at timestamptz not null default now(), deleted_at timestamptz,
  constraint social_post_has_content check (status='deleted' or char_length(trim(body)) > 0 or repost_of_id is not null)
);
create table public.social_post_media (
  id uuid primary key default gen_random_uuid(), post_id uuid not null references public.social_posts(id) on delete cascade,
  owner_id uuid not null references auth.users(id) on delete cascade,
  media_type text not null check (media_type = 'image'), url text not null,
  order_index smallint not null default 0 check (order_index between 0 and 3), created_at timestamptz not null default now(), unique(post_id,order_index)
);
create table public.social_likes (user_id uuid references public.social_profiles(user_id) on delete cascade, post_id uuid references public.social_posts(id) on delete cascade, created_at timestamptz not null default now(), primary key(user_id,post_id));
create table public.social_follows (follower_id uuid references public.social_profiles(user_id) on delete cascade, following_id uuid references public.social_profiles(user_id) on delete cascade, created_at timestamptz not null default now(), primary key(follower_id,following_id), check(follower_id<>following_id));
create table public.social_bookmarks (user_id uuid references auth.users(id) on delete cascade, post_id uuid references public.social_posts(id) on delete cascade, created_at timestamptz not null default now(), primary key(user_id,post_id));
create table public.social_notifications (
 id uuid primary key default gen_random_uuid(), recipient_id uuid not null references public.social_profiles(user_id) on delete cascade, actor_id uuid references public.social_profiles(user_id) on delete set null,
 type text not null check(type in ('follow','like','comment','reply','repost','mention','message')), entity_type text not null check(entity_type in ('post','profile','conversation')),
 entity_id uuid not null, read_at timestamptz, created_at timestamptz not null default now(), check(recipient_id<>actor_id)
);
create table public.social_conversations (id uuid primary key default gen_random_uuid(), pair_key text not null unique, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.social_conversation_members (conversation_id uuid references public.social_conversations(id) on delete cascade, user_id uuid references public.social_profiles(user_id) on delete cascade, last_read_at timestamptz, joined_at timestamptz not null default now(), primary key(conversation_id,user_id));
create table public.social_messages (id uuid primary key default gen_random_uuid(), conversation_id uuid not null references public.social_conversations(id) on delete cascade, sender_id uuid not null references public.social_profiles(user_id) on delete cascade, body text not null check(char_length(trim(body)) between 1 and 4000), media_url text, created_at timestamptz not null default now(), deleted_at timestamptz);
create table public.social_blocks (blocker_id uuid references auth.users(id) on delete cascade, blocked_id uuid references auth.users(id) on delete cascade, created_at timestamptz not null default now(), primary key(blocker_id,blocked_id), check(blocker_id<>blocked_id));
create table public.social_mutes (user_id uuid references auth.users(id) on delete cascade, muted_user_id uuid references auth.users(id) on delete cascade, created_at timestamptz not null default now(), primary key(user_id,muted_user_id), check(user_id<>muted_user_id));
create table public.social_reports (id uuid primary key default gen_random_uuid(), reporter_id uuid not null references auth.users(id) on delete cascade, target_type text not null check(target_type in ('post','profile','message')), target_id uuid not null, reason text not null check(reason in ('spam','harassment','inappropriate','scam','violence','other')), details text not null default '' check(char_length(details)<=1000), status text not null default 'open' check(status in ('open','reviewing','resolved','dismissed')), created_at timestamptz not null default now(), unique(reporter_id,target_type,target_id));

create index social_posts_feed_idx on public.social_posts(status,created_at desc,id desc);
create index social_posts_author_idx on public.social_posts(author_id,created_at desc);
create index social_posts_reply_idx on public.social_posts(reply_to_id,created_at);
create index social_posts_body_search_idx on public.social_posts using gin(body extensions.gin_trgm_ops);
create index social_posts_fts_pt_idx on public.social_posts using gin(to_tsvector('portuguese',body));
create index social_posts_unaccent_search_idx on public.social_posts using gin(public.social_normalize_search(body) extensions.gin_trgm_ops);
create index social_profiles_search_idx on public.social_profiles using gin((username||' '||display_name) extensions.gin_trgm_ops);
create index social_follows_following_idx on public.social_follows(following_id,follower_id);
create index social_likes_post_idx on public.social_likes(post_id);
create index social_bookmarks_user_idx on public.social_bookmarks(user_id,created_at desc);
create index social_notifications_unread_idx on public.social_notifications(recipient_id,created_at desc) where read_at is null;
create unique index social_notifications_dedupe_idx on public.social_notifications(recipient_id,actor_id,type,entity_type,entity_id);
create index social_messages_conversation_idx on public.social_messages(conversation_id,created_at desc);
create index social_members_user_idx on public.social_conversation_members(user_id,conversation_id);

create or replace function public.social_is_blocked(a uuid,b uuid) returns boolean language sql stable security definer set search_path=public as $$select exists(select 1 from social_blocks where (blocker_id=a and blocked_id=b) or (blocker_id=b and blocked_id=a))$$;
create or replace function public.social_is_member(cid uuid,uid uuid) returns boolean language sql stable security definer set search_path=public as $$select exists(select 1 from social_conversation_members where conversation_id=cid and user_id=uid)$$;
create or replace function public.social_recent_actions(actor uuid, action_type text, window_start timestamptz) returns bigint language sql stable security definer set search_path=public as $$select count(*) from social_notifications where actor_id=actor and type=action_type and created_at>window_start$$;
create or replace function public.social_create_post(p_body text,p_reply_to uuid default null,p_repost_of uuid default null) returns uuid language plpgsql security invoker set search_path=public as $$declare result uuid;begin if auth.uid() is null then raise exception 'AUTH_REQUIRED'; end if; if char_length(trim(coalesce(p_body,'')))=0 and p_repost_of is null then raise exception 'CONTENT_REQUIRED'; end if; if (select count(*) from social_posts where author_id=auth.uid() and created_at>now()-interval '1 minute')>=10 then raise exception 'RATE_LIMITED'; end if; if p_reply_to is not null and (select count(*) from social_posts where id=p_reply_to and status='published')=0 then raise exception 'POST_UNAVAILABLE'; end if; if p_repost_of is not null and (select count(*) from social_posts where id=p_repost_of and status='published')=0 then raise exception 'POST_UNAVAILABLE'; end if; if exists(select 1 from social_posts where author_id=auth.uid() and body=trim(p_body) and created_at>now()-interval '30 seconds') then raise exception 'DUPLICATE_POST'; end if; insert into social_posts(author_id,body,reply_to_id,repost_of_id) values(auth.uid(),trim(coalesce(p_body,'')),p_reply_to,p_repost_of) returning id into result; return result;end$$;
create or replace function public.social_open_conversation(other_user uuid) returns uuid language plpgsql security definer set search_path=public as $$declare result uuid; pair text;begin if auth.uid() is null or other_user=auth.uid() or social_is_blocked(auth.uid(),other_user) then raise exception 'CONVERSATION_NOT_ALLOWED'; end if; if not exists(select 1 from social_profiles where user_id=other_user) then raise exception 'PROFILE_NOT_FOUND'; end if; if (select count(*) from social_conversations c join social_conversation_members m on m.conversation_id=c.id where m.user_id=auth.uid() and c.created_at>now()-interval '1 minute')>=10 then raise exception 'RATE_LIMITED'; end if; pair:=least(auth.uid()::text,other_user::text)||':'||greatest(auth.uid()::text,other_user::text); insert into social_conversations(pair_key) values(pair) on conflict(pair_key) do update set pair_key=excluded.pair_key returning id into result; insert into social_conversation_members(conversation_id,user_id) values(result,auth.uid()),(result,other_user) on conflict do nothing; return result;end$$;
create or replace function public.social_ranking(category text default 'relevant', exclude_user uuid default null) returns setof public.social_profiles language sql stable security invoker set search_path=public as $$
 select p from social_profiles p
 left join lateral (select count(*) followers from social_follows f where f.following_id=p.user_id) fc on true
 left join lateral (select count(*) posts from social_posts s where s.author_id=p.user_id and s.status='published' and s.created_at>now()-interval '30 days') pc on true
 left join lateral (select count(*) engagement from social_likes l join social_posts s on s.id=l.post_id where s.author_id=p.user_id and l.created_at>now()-interval '30 days') ec on true
 left join lateral (select count(*) rising from social_follows f where f.following_id=p.user_id and f.created_at>now()-interval '7 days') rc on true
 where (exclude_user is null or p.user_id<>exclude_user)
 order by case when category='active' then pc.posts end desc, case when category='followed' then fc.followers end desc, case when category='rising' then rc.rising end desc, (pc.posts*2+ec.engagement+fc.followers) desc, p.created_at asc limit 50
$$;
create or replace function public.social_search_posts(search_query text) returns setof public.social_posts language sql stable security invoker set search_path=public as $$
 select p from public.social_posts p
 where p.status='published' and p.reply_to_id is null
  and char_length(trim(search_query)) between 2 and 80
  and (to_tsvector('portuguese',p.body) @@ websearch_to_tsquery('portuguese',search_query)
   or public.social_normalize_search(p.body) like '%'||public.social_normalize_search(search_query)||'%')
 order by ts_rank_cd(to_tsvector('portuguese',p.body),websearch_to_tsquery('portuguese',search_query)) desc,p.created_at desc
 limit 30
$$;

alter table public.social_profiles enable row level security; alter table public.social_posts enable row level security; alter table public.social_post_media enable row level security; alter table public.social_likes enable row level security; alter table public.social_follows enable row level security; alter table public.social_bookmarks enable row level security; alter table public.social_notifications enable row level security; alter table public.social_conversations enable row level security; alter table public.social_conversation_members enable row level security; alter table public.social_messages enable row level security; alter table public.social_blocks enable row level security; alter table public.social_mutes enable row level security; alter table public.social_reports enable row level security;
alter table public.social_profiles force row level security; alter table public.social_posts force row level security; alter table public.social_post_media force row level security; alter table public.social_likes force row level security; alter table public.social_follows force row level security; alter table public.social_bookmarks force row level security; alter table public.social_notifications force row level security; alter table public.social_conversations force row level security; alter table public.social_conversation_members force row level security; alter table public.social_messages force row level security; alter table public.social_blocks force row level security; alter table public.social_mutes force row level security; alter table public.social_reports force row level security;

create policy social_profiles_read on public.social_profiles for select to authenticated using(not public.social_is_blocked(auth.uid(),user_id));
create policy social_profiles_insert on public.social_profiles for insert to authenticated with check(user_id=auth.uid()); create policy social_profiles_update on public.social_profiles for update to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid());
create policy social_posts_read on public.social_posts for select to authenticated using(author_id=auth.uid() or (status='published' and not public.social_is_blocked(auth.uid(),author_id) and (visibility='public' or exists(select 1 from public.social_follows where follower_id=auth.uid() and following_id=author_id))));
create policy social_posts_insert on public.social_posts for insert to authenticated with check(author_id=auth.uid()); create policy social_posts_update on public.social_posts for update to authenticated using(author_id=auth.uid()) with check(author_id=auth.uid());
create policy social_media_read on public.social_post_media for select to authenticated using(exists(select 1 from public.social_posts p where p.id=post_id)); create policy social_media_write on public.social_post_media for insert to authenticated with check(owner_id=auth.uid() and exists(select 1 from public.social_posts p where p.id=post_id and p.author_id=auth.uid())); create policy social_media_delete on public.social_post_media for delete to authenticated using(owner_id=auth.uid());
create policy social_likes_read on public.social_likes for select to authenticated using(exists(select 1 from public.social_posts p where p.id=post_id)); create policy social_likes_insert on public.social_likes for insert to authenticated with check(user_id=auth.uid() and public.social_recent_actions(auth.uid(),'like',now()-interval '1 minute')<60 and exists(select 1 from public.social_posts p where p.id=post_id and p.author_id<>auth.uid() and not public.social_is_blocked(auth.uid(),p.author_id))); create policy social_likes_delete on public.social_likes for delete to authenticated using(user_id=auth.uid());
create policy social_follows_read on public.social_follows for select to authenticated using(not public.social_is_blocked(auth.uid(),follower_id) and not public.social_is_blocked(auth.uid(),following_id)); create policy social_follows_insert on public.social_follows for insert to authenticated with check(follower_id=auth.uid() and public.social_recent_actions(auth.uid(),'follow',now()-interval '1 minute')<30 and not public.social_is_blocked(follower_id,following_id)); create policy social_follows_delete on public.social_follows for delete to authenticated using(follower_id=auth.uid());
create policy social_bookmarks_owner on public.social_bookmarks for all to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid());
create policy social_notifications_owner on public.social_notifications for select to authenticated using(recipient_id=auth.uid()); create policy social_notifications_update on public.social_notifications for update to authenticated using(recipient_id=auth.uid()) with check(recipient_id=auth.uid());
create policy social_conversations_members on public.social_conversations for select to authenticated using(public.social_is_member(id,auth.uid())); create policy social_members_members on public.social_conversation_members for select to authenticated using(public.social_is_member(conversation_id,auth.uid())); create policy social_members_update on public.social_conversation_members for update to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid());
create policy social_messages_members on public.social_messages for select to authenticated using(public.social_is_member(conversation_id,auth.uid())); create policy social_messages_send on public.social_messages for insert to authenticated with check(sender_id=auth.uid() and public.social_is_member(conversation_id,auth.uid()) and not exists(select 1 from social_conversation_members cm where cm.conversation_id=social_messages.conversation_id and social_is_blocked(auth.uid(),cm.user_id)) and (select count(*) from social_messages m where m.sender_id=auth.uid() and m.created_at>now()-interval '1 minute')<30); create policy social_messages_delete on public.social_messages for update to authenticated using(sender_id=auth.uid()) with check(sender_id=auth.uid() and public.social_is_member(conversation_id,auth.uid()));
create policy social_blocks_owner on public.social_blocks for all to authenticated using(blocker_id=auth.uid()) with check(blocker_id=auth.uid()); create policy social_mutes_owner on public.social_mutes for all to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid()); create policy social_reports_insert on public.social_reports for insert to authenticated with check(reporter_id=auth.uid()); create policy social_reports_read_own on public.social_reports for select to authenticated using(reporter_id=auth.uid());

create or replace function public.social_notify() returns trigger language plpgsql security definer set search_path=public as $$begin if tg_table_name='social_follows' then insert into social_notifications(recipient_id,actor_id,type,entity_type,entity_id) values(new.following_id,new.follower_id,'follow','profile',new.follower_id) on conflict do nothing; elsif tg_table_name='social_likes' then insert into social_notifications(recipient_id,actor_id,type,entity_type,entity_id) select author_id,new.user_id,'like','post',new.post_id from social_posts where id=new.post_id and author_id<>new.user_id on conflict do nothing; elsif tg_table_name='social_posts' then if new.reply_to_id is not null then insert into social_notifications(recipient_id,actor_id,type,entity_type,entity_id) select author_id,new.author_id,case when reply_to_id is null then 'comment' else 'reply' end,'post',new.id from social_posts where id=new.reply_to_id and author_id<>new.author_id on conflict do nothing; elsif new.repost_of_id is not null then insert into social_notifications(recipient_id,actor_id,type,entity_type,entity_id) select author_id,new.author_id,'repost','post',new.id from social_posts where id=new.repost_of_id and author_id<>new.author_id on conflict do nothing; end if; elsif tg_table_name='social_messages' then insert into social_notifications(recipient_id,actor_id,type,entity_type,entity_id) select user_id,new.sender_id,'message','conversation',new.conversation_id from social_conversation_members where conversation_id=new.conversation_id and user_id<>new.sender_id on conflict do nothing; end if; return new;end$$;
create or replace function public.social_notify_mentions() returns trigger language plpgsql security definer set search_path=public as $$begin insert into social_notifications(recipient_id,actor_id,type,entity_type,entity_id) select p.user_id,new.author_id,'mention','post',new.id from social_profiles p join (select distinct lower(m[1]) username from regexp_matches(new.body,'@([a-z0-9_]{3,24})','g') m limit 10) tags on tags.username=p.username where p.user_id<>new.author_id and not social_is_blocked(new.author_id,p.user_id) on conflict do nothing;return new;end$$;
create trigger social_follow_notification after insert on public.social_follows for each row execute function public.social_notify(); create trigger social_like_notification after insert on public.social_likes for each row execute function public.social_notify(); create trigger social_comment_notification after insert on public.social_posts for each row execute function public.social_notify(); create trigger social_mention_notification after insert on public.social_posts for each row execute function public.social_notify_mentions(); create trigger social_message_notification after insert on public.social_messages for each row execute function public.social_notify();
create or replace function public.social_block_cleanup() returns trigger language plpgsql security definer set search_path=public as $$begin delete from social_follows where (follower_id=new.blocker_id and following_id=new.blocked_id) or (follower_id=new.blocked_id and following_id=new.blocker_id); return new;end$$; create trigger social_block_cleanup_trigger after insert on public.social_blocks for each row execute function public.social_block_cleanup();

insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types) values('social-media','social-media',false,10485760,array['image/jpeg','image/png','image/webp']) on conflict(id) do update set public=false,file_size_limit=excluded.file_size_limit,allowed_mime_types=excluded.allowed_mime_types;
create or replace function public.social_can_read_media(object_name text, viewer uuid) returns boolean language sql stable security definer set search_path=public,storage as $$
 select viewer is not null and (
  split_part(object_name,'/',1)=viewer::text
  or exists(select 1 from public.social_profiles p where (p.avatar_url=object_name or p.cover_url=object_name) and not public.social_is_blocked(viewer,p.user_id))
  or exists(select 1 from public.social_post_media m join public.social_posts p on p.id=m.post_id where m.url=object_name and p.status='published' and not public.social_is_blocked(viewer,p.author_id) and (p.visibility='public' or p.author_id=viewer or exists(select 1 from public.social_follows f where f.follower_id=viewer and f.following_id=p.author_id)))
  or exists(select 1 from public.social_messages m where m.media_url=object_name and public.social_is_member(m.conversation_id,viewer))
 )
$$;
create policy social_storage_read on storage.objects for select to authenticated using(bucket_id='social-media' and public.social_can_read_media(name,auth.uid()));
create policy social_storage_delete on storage.objects for delete to authenticated using(bucket_id='social-media' and split_part(name,'/',1)=auth.uid()::text);

grant select,insert,update,delete on public.social_profiles,public.social_posts,public.social_post_media,public.social_likes,public.social_follows,public.social_bookmarks,public.social_conversation_members,public.social_messages,public.social_blocks,public.social_mutes to authenticated;
grant select,update on public.social_notifications to authenticated; grant select on public.social_conversations to authenticated; grant select,insert on public.social_reports to authenticated; grant execute on function public.social_create_post(text,uuid,uuid),public.social_open_conversation(uuid),public.social_ranking(text,uuid),public.social_search_posts(text),public.social_can_read_media(text,uuid) to authenticated;
alter publication supabase_realtime add table public.social_notifications; alter publication supabase_realtime add table public.social_messages;
