import {supabase} from '../../lib/supabase'
const client=()=>{if(!supabase)throw new Error('SUPABASE_UNAVAILABLE');return supabase}
export type ModuleName='tracking'|'order_bumps'|'funnel_steps'|'coupons'|'coproducers'|'affiliates'|'links'
const tables:Record<ModuleName,string>={tracking:'product_tracking_integrations',order_bumps:'product_order_bumps',funnel_steps:'product_funnel_steps',coupons:'product_coupons',coproducers:'product_coproducers',affiliates:'product_affiliates',links:'product_links'}
const digest=async(value:string)=>{const bytes=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(value));return [...new Uint8Array(bytes)].map(x=>x.toString(16).padStart(2,'0')).join('')}
export const buildTrackedUrl=(base:string,tracking:Record<string,string>)=>{const allowed=['utm_source','utm_medium','utm_campaign','utm_content','utm_term','src','sck'],url=new URL(base,'https://sphexpay.invalid');for(const key of allowed){const value=tracking[key]?.trim();if(value)url.searchParams.set(key,value)}return url.origin==='https://sphexpay.invalid'?`${url.pathname}${url.search}`:url.toString()}
export const isInvalidProductRelation=(productId:string,relatedProductId:string)=>Boolean(productId&&relatedProductId&&productId===relatedProductId)
const activity=async(sellerId:string,productId:string,action:string,entityId?:string,metadata:Record<string,unknown>={})=>{await client().from('product_activity_log').insert({seller_id:sellerId,actor_id:sellerId,product_id:productId,action,entity_type:action.split('.')[0],entity_id:entityId,metadata})}
export const advancedService={
 async list(module:ModuleName,productId:string){const {data,error}=await client().from(tables[module]).select('*').eq('product_id',productId).order('created_at',{ascending:false});if(error)throw error;return(data||[]) as Record<string,unknown>[]},
 async save(module:ModuleName,sellerId:string,productId:string,input:Record<string,unknown>){const table=tables[module],record:Record<string,unknown>={...input,product_id:productId,seller_id:sellerId,updated_at:new Date().toISOString()};delete record.id;const response=input.id?await client().from(table).update(record).eq('id',String(input.id)).eq('seller_id',sellerId).select().single():await client().from(table).insert(record).select().single();if(response.error)throw response.error;await activity(sellerId,productId,`${module}.${input.id?'updated':'created'}`,String(response.data.id));return response.data as Record<string,unknown>},
 async setStatus(module:ModuleName,sellerId:string,productId:string,id:string,status:string){const {error}=await client().from(tables[module]).update({status,updated_at:new Date().toISOString()}).eq('id',id).eq('seller_id',sellerId);if(error)throw error;await activity(sellerId,productId,`${module}.status_changed`,id,{status})},
 async remove(module:ModuleName,sellerId:string,productId:string,id:string){const table=tables[module],soft=['order_bumps','funnel_steps','coupons','links'].includes(module),payload=soft?{deleted_at:new Date().toISOString(),status:'archived'}:null;const query=payload?client().from(table).update(payload):client().from(table).delete();const {error}=await query.eq('id',id).eq('seller_id',sellerId);if(error)throw error;await activity(sellerId,productId,`${module}.removed`,id)},
 async reorder(module:'order_bumps'|'funnel_steps',sellerId:string,productId:string,ids:string[]){await Promise.all(ids.map((id,position)=>client().from(tables[module]).update({position,updated_at:new Date().toISOString()}).eq('id',id).eq('seller_id',sellerId)));await activity(sellerId,productId,`${module}.reordered`)},
 async getDelivery(productId:string){const {data,error}=await client().from('product_delivery_settings').select('id,product_id,seller_id,provider,config,enabled,last_test_at,last_test_status,updated_at').eq('product_id',productId).maybeSingle();if(error)throw error;return data as Record<string,unknown>|null},
 async saveDelivery(sellerId:string,productId:string,input:{provider:string;config:Record<string,unknown>;enabled:boolean;secret?:string}){const record:Record<string,unknown>={seller_id:sellerId,product_id:productId,provider:input.provider,config:input.config,enabled:input.enabled,updated_at:new Date().toISOString()};if(input.secret)record.secret_digest=await digest(input.secret);const {error}=await client().from('product_delivery_settings').upsert(record,{onConflict:'product_id'});if(error)throw error;await activity(sellerId,productId,'delivery.updated')},
 async getAffiliateSettings(productId:string){const {data,error}=await client().from('product_affiliate_settings').select('*').eq('product_id',productId).maybeSingle();if(error)throw error;return data as Record<string,unknown>|null},
 async saveAffiliateSettings(sellerId:string,productId:string,input:Record<string,unknown>){const {error}=await client().from('product_affiliate_settings').upsert({...input,seller_id:sellerId,product_id:productId,updated_at:new Date().toISOString()},{onConflict:'product_id'});if(error)throw error;await activity(sellerId,productId,'affiliate.settings_updated')},
 async inviteAffiliate(sellerId:string,productId:string,email:string){const code=crypto.randomUUID().replaceAll('-','');const {data,error}=await client().from('product_affiliates').insert({seller_id:sellerId,product_id:productId,email:email.trim().toLowerCase(),invite_code:code}).select().single();if(error)throw error;await activity(sellerId,productId,'affiliate.invited',String(data.id));return data},
 async getFunnelSettings(productId:string){const {data,error}=await client().from('product_funnel_settings').select('*').eq('product_id',productId).maybeSingle();if(error)throw error;return data as Record<string,unknown>|null},
 async saveFunnelSettings(sellerId:string,productId:string,input:Record<string,unknown>){const {error}=await client().from('product_funnel_settings').upsert({...input,seller_id:sellerId,product_id:productId,updated_at:new Date().toISOString()},{onConflict:'product_id'});if(error)throw error;await activity(sellerId,productId,'funnel.settings_updated')},
 async history(productId:string){const {data,error}=await client().from('product_activity_log').select('id,action,entity_type,entity_id,metadata,created_at').eq('product_id',productId).order('created_at',{ascending:false}).limit(100);if(error)throw error;return data||[]}
}
