import {useState} from 'react'
import {ArrowUp,ArrowDown,Check,Code2,Copy,Upload} from 'lucide-react'
import type {CheckoutElementKey,CheckoutSlot,CheckoutTemplate} from './checkoutTemplate'
import {parseCheckoutTemplate,providedCheckoutTemplate} from './checkoutTemplate'

export function CheckoutTemplatePanel({value,onApply}:{value?:CheckoutTemplate;onApply:(template:CheckoutTemplate)=>void}){
 const [text,setText]=useState(()=>JSON.stringify(value||providedCheckoutTemplate,null,2)),[error,setError]=useState(''),[message,setMessage]=useState('')
 const apply=(raw:string)=>{try{const model=parseCheckoutTemplate(raw);onApply(model);setText(JSON.stringify(model,null,2));setError('');setMessage('Modelo aplicado ao rascunho. Confira a prévia e publique.')}catch(e){setError(e instanceof Error?e.message:'Modelo inválido.');setMessage('')}}
 const mobileModel=value||providedCheckoutTemplate
 const mobileChange=(key:CheckoutElementKey,direction:number)=>{const model=structuredClone(mobileModel),order=model.config.mobile_elements_order,index=order.indexOf(key),target=index+direction;if(target<0||target>=order.length)return;[order[index],order[target]]=[order[target],order[index]];apply(JSON.stringify(model))}
 const changeSlot=(key:CheckoutElementKey,slot:CheckoutSlot)=>{const model=structuredClone(mobileModel);model.config.mobile_elements_slots[key]=slot;apply(JSON.stringify(model))}
 const read=async(file?:File)=>{if(!file)return;try{if(file.size>65536)throw new Error('O modelo deve ter até 64 KB.');const raw=await file.text();parseCheckoutTemplate(raw);setText(raw);setError('');setMessage('Arquivo carregado. Clique em Aplicar JSON para usar o modelo.')}catch(e){setError(e instanceof Error?e.message:'Não foi possível ler o arquivo.')}}
 return <div className="studio-template-panel"><h3><Code2/> Modelo do checkout</h3><p>O modelo enviado usa tema claro, destaque índigo, banner com shimmer e posições próprias no celular.</p><button type="button" className="btn btn-primary" onClick={()=>apply(JSON.stringify(providedCheckoutTemplate))}>Aplicar modelo enviado<Check/></button><details><summary>Celular: ordem e posições</summary><p>Elementos sem conteúdo ficam ocultos no link público. A ordem vale dentro de cada posição.</p><div className="studio-template-order">{mobileModel.config.mobile_elements_order.map((key,index)=><div key={key}><span>{key.replaceAll('_',' ')}</span><button type="button" aria-label={`Subir ${key}`} disabled={index===0} onClick={()=>mobileChange(key,-1)}><ArrowUp/></button><button type="button" aria-label={`Descer ${key}`} disabled={index===mobileModel.config.mobile_elements_order.length-1} onClick={()=>mobileChange(key,1)}><ArrowDown/></button><select className="input" aria-label={`Posição de ${key} no celular`} value={mobileModel.config.mobile_elements_slots[key]||'sidebar'} onChange={e=>changeSlot(key,e.target.value as CheckoutSlot)}><option value="top">Topo do checkout</option><option value="sidebar">Antes do formulário</option><option value="pre_cta">Antes do botão</option><option value="form_bottom">Abaixo do formulário</option></select></div>)}</div></details><details><summary>Configuração JSON</summary><label>Modelo na versão 1<textarea className="input" rows={12} value={text} spellCheck={false} onChange={e=>{setText(e.target.value);setMessage('')}}/></label><div className="studio-template-actions"><button className="btn" type="button" onClick={()=>apply(text)}>Aplicar JSON</button><label className="btn"><Upload/> Importar arquivo<input type="file" accept=".json,application/json" onChange={e=>{void read(e.target.files?.[0]);e.target.value=''}}/></label><button className="btn" type="button" onClick={async()=>{try{await navigator.clipboard.writeText(text);setMessage('JSON copiado.')}catch{setError('Selecione o JSON e copie pelo teclado.')}}}><Copy/> Copiar JSON</button></div></details>{error&&<p className="co-property-error" role="alert">{error}</p>}{message&&<p className="studio-template-message" role="status">{message}</p>}</div>
}
