import {supabase} from '../../lib/supabase'
export type CheckoutStatus='draft'|'published'|'paused'|'archived'
export type CheckoutComponentType='logo'|'text'|'title'|'image'|'video'|'benefits'|'list'|'badge'|'warranty'|'testimonial'|'faq'|'timer'|'divider'|'spacer'|'banner'|'order_summary'|'buyer_form'|'payment_methods'|'order_bump'|'button'|'notice'|'footer'|'social_proof'|'purchase_notification'|'exit_intent'
export type CheckoutBlock={id:string;type:CheckoutComponentType;hidden?:boolean;props:Record<string,string|number|boolean|string[]>}
export type CheckoutDesign={primary:string;accent:string;background:string;card:string;text:string;radius:number;width:number;font:'Inter'|'system-ui'|'Arial';buttonStyle:'solid'|'soft'|'outline'}
export type CheckoutSettings={buyerName:boolean;buyerEmail:boolean;buyerPhone:boolean;buyerTaxId:boolean;buyerAddress:boolean;showPrice:boolean;showDiscount:boolean;coupon:boolean;installments:boolean;warranty:boolean;timer:boolean;repeatEmail:boolean;optimizedFill:boolean;saveAllowedData:boolean;salesPageBack:boolean;redirectUrl:string;threeDS:boolean;captcha:boolean}
export type ProductCheckout={id:string;productId:string;sellerId:string;offerId:string;name:string;slug:string;template:string;status:CheckoutStatus;isDefault:boolean;layout:CheckoutBlock[];design:CheckoutDesign;settings:CheckoutSettings;publishedVersionId:string|null;lockVersion:number;createdAt:string;updatedAt:string;visits?:number;starts?:number;purchases?:number}
const defaults:CheckoutDesign={primary:'#ff6a2f',accent:'#f15a24',background:'#f6f6f3',card:'#ffffff',text:'#171717',radius:14,width:980,font:'Inter',buttonStyle:'solid'}
export const defaultSettings:CheckoutSettings={buyerName:true,buyerEmail:true,buyerPhone:false,buyerTaxId:false,buyerAddress:false,showPrice:true,showDiscount:true,coupon:true,installments:true,warranty:true,timer:false,repeatEmail:false,optimizedFill:true,saveAllowedData:false,salesPageBack:true,redirectUrl:'',threeDS:false,captcha:false}
const block=(type:CheckoutComponentType,props:CheckoutBlock['props']):CheckoutBlock=>({id:crypto.randomUUID(),type,props})
export const templateLayout=(template:string):CheckoutBlock[]=>template==='blank'?[]:[block('title',{text:'Finalize sua compra',align:'left',size:30,weight:700,padding:0,margin:0,color:'',background:'',radius:0}),block('benefits',{items:['Acesso ao produto adquirido','Pagamento em ambiente seguro'],title:'Você recebe'}),block('buyer_form',{title:'Seus dados'}),block('order_summary',{title:'Resumo do pedido'}),block('payment_methods',{title:'Pagamento'}),block('button',{text:'Continuar com segurança'}),block('warranty',{title:'Garantia',text:'Confira as condições da oferta.'}),block('footer',{text:'Compra protegida conforme os termos da oferta.'})]
const client=()=>{if(!supabase)throw new Error('SUPABASE_UNAVAILABLE');return supabase}
const row=(r:Record<string,unknown>):ProductCheckout=>({id:String(r.id),productId:String(r.product_id),sellerId:String(r.seller_id),offerId:String(r.offer_id),name:String(r.name),slug:String(r.slug),template:String(r.template),status:r.status as CheckoutStatus,isDefault:Boolean(r.is_default),layout:(r.draft_layout||[]) as CheckoutBlock[],design:{...defaults,...(r.draft_design as object||{})},settings:{...defaultSettings,...(r.draft_settings as object||{})},publishedVersionId:r.published_version_id?String(r.published_version_id):null,lockVersion:Number(r.lock_version),createdAt:String(r.created_at),updatedAt:String(r.updated_at)})
export const checkoutService={
 async list(productId:string){const {data,error}=await client().from('product_checkouts').select('*,checkout_analytics_events(event_type)').eq('product_id',productId).is('deleted_at',null).order('updated_at',{ascending:false});if(error)throw error;return(data||[]).map(raw=>{const c=row(raw as Record<string,unknown>),events=(raw.checkout_analytics_events||[]) as {event_type:string}[];c.visits=events.filter(x=>x.event_type==='page_view').length;c.starts=events.filter(x=>x.event_type==='checkout_started').length;c.purchases=events.filter(x=>x.event_type==='purchase').length;return c})},
 async get(productId:string,id:string){const {data,error}=await client().from('product_checkouts').select('*').eq('id',id).eq('product_id',productId).is('deleted_at',null).single();if(error)throw error;return row(data as Record<string,unknown>)},
 async create(sellerId:string,productId:string,input:{name:string;offerId:string;template:string}){const layout=templateLayout(input.template),slug=`${input.name.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'')}-${crypto.randomUUID().slice(0,6)}`;const {data,error}=await client().from('product_checkouts').insert({seller_id:sellerId,product_id:productId,offer_id:input.offerId,name:input.name,slug,template:input.template,draft_layout:layout,draft_design:defaults,draft_settings:defaultSettings}).select().single();if(error)throw error;return row(data as Record<string,unknown>)},
 async saveDraft(id:string,lockVersion:number,layout:CheckoutBlock[],design:CheckoutDesign,settings:CheckoutSettings){const {data,error}=await client().rpc('save_checkout_draft',{p_checkout_id:id,p_expected_lock:lockVersion,p_layout:layout,p_design:design,p_settings:settings});if(error)throw Object.assign(new Error(error.message),{code:error.code});return Number(data)},
 async publish(id:string,lockVersion:number,key:string){const {data,error}=await client().rpc('publish_checkout',{p_checkout_id:id,p_expected_lock:lockVersion,p_idempotency_key:key});if(error)throw Object.assign(new Error(error.message),{code:error.code});return data as {versionId:string;version:number;lockVersion:number;duplicate?:boolean}},
 async duplicate(sellerId:string,c:ProductCheckout){const copy=await this.create(sellerId,c.productId,{name:`${c.name} — cópia`,offerId:c.offerId,template:c.template});const lock=await this.saveDraft(copy.id,copy.lockVersion,c.layout,c.design,c.settings);return{...copy,lockVersion:lock}},
 async setStatus(sellerId:string,id:string,status:CheckoutStatus){const {error}=await client().from('product_checkouts').update({status,updated_at:new Date().toISOString()}).eq('id',id).eq('seller_id',sellerId);if(error)throw error},
 async makeDefault(_sellerId:string,productId:string,id:string){const {error}=await client().rpc('set_default_checkout',{p_product_id:productId,p_checkout_id:id});if(error)throw error},
 async remove(sellerId:string,id:string){const {error}=await client().from('product_checkouts').update({deleted_at:new Date().toISOString(),status:'archived'}).eq('id',id).eq('seller_id',sellerId);if(error)throw error},
 async versions(checkoutId:string){const {data,error}=await client().from('checkout_versions').select('id,version,published_at,created_at').eq('checkout_id',checkoutId).order('version',{ascending:false});if(error)throw error;return data||[]},
 async restore(checkoutId:string,versionId:string,lockVersion:number){const {data,error}=await client().rpc('restore_checkout_version',{p_checkout_id:checkoutId,p_version_id:versionId,p_expected_lock:lockVersion});if(error)throw error;return Number(data)}
}
