import {supabase} from '../../lib/supabase'
import type {Product,ProductDraft,ProductOffer,ProductStatus} from './types'

const productFields='id,seller_id,name,slug,description,category,tags,image_url,sales_page_url,product_type,status,billing_type,warranty_days,support_email,producer_display_name,price_cents,currency,created_at,updated_at,archived_at,product_offers(id,product_id,name,price_cents,currency,billing_type,billing_interval,installments,trial_days,setup_fee_cents,max_charges,access_duration_days,warranty_days,status,is_default,updated_at),payment_transactions(amount_cents,status)'
const offerFrom=(r:Record<string,unknown>):ProductOffer=>({id:String(r.id),productId:String(r.product_id),name:String(r.name),priceCents:Number(r.price_cents),currency:(r.currency||'BRL') as ProductOffer['currency'],billingType:r.billing_type as ProductOffer['billingType'],billingInterval:(r.billing_interval||null) as ProductOffer['billingInterval'],installments:Number(r.installments||1),trialDays:r.trial_days==null?null:Number(r.trial_days),setupFeeCents:r.setup_fee_cents==null?null:Number(r.setup_fee_cents),maxCharges:r.max_charges==null?null:Number(r.max_charges),accessDurationDays:r.access_duration_days==null?null:Number(r.access_duration_days),warrantyDays:r.warranty_days==null?null:Number(r.warranty_days),status:r.status as ProductStatus,isDefault:Boolean(r.is_default),updatedAt:String(r.updated_at)})
const fromRow=(r:Record<string,unknown>):Product=>{const offers=(r.product_offers as Record<string,unknown>[]||[]),transactions=(r.payment_transactions as {amount_cents:number;status:string}[]||[]),approved=transactions.filter(x=>x.status==='approved');return{id:String(r.id),sellerId:String(r.seller_id),name:String(r.name),slug:String(r.slug||''),description:String(r.description||''),category:String(r.category||''),tags:Array.isArray(r.tags)?r.tags.map(String):[],imageUrl:r.image_url?String(r.image_url):null,salesPageUrl:r.sales_page_url?String(r.sales_page_url):null,productType:String(r.product_type||'digital'),status:r.status as ProductStatus,billingType:r.billing_type as Product['billingType'],warrantyDays:r.warranty_days==null?null:Number(r.warranty_days),supportEmail:String(r.support_email||''),producerDisplayName:String(r.producer_display_name||''),priceCents:Number(r.price_cents||0),currency:(r.currency||'BRL') as Product['currency'],createdAt:String(r.created_at),updatedAt:String(r.updated_at),archivedAt:r.archived_at?String(r.archived_at):null,sales:approved.length,revenueCents:approved.reduce((a,x)=>a+Number(x.amount_cents||0),0),offer:offers.length?offerFrom(offers.find(x=>x.is_default)||offers[0]):null}}
const requireClient=()=>{if(!supabase)throw new Error('SUPABASE_UNAVAILABLE');return supabase}
const log=async(sellerId:string,productId:string,action:string,entityType='product',entityId?:string,metadata:Record<string,unknown>={})=>{const client=requireClient();await client.from('product_activity_log').insert({seller_id:sellerId,actor_id:sellerId,product_id:productId,action,entity_type:entityType,entity_id:entityId,metadata})}
export const productServiceV2={
 async list(){const {data,error}=await requireClient().from('products').select(productFields).is('deleted_at',null).order('updated_at',{ascending:false});if(error)throw error;return(data||[]).map(r=>fromRow(r as Record<string,unknown>))},
 async get(id:string){const {data,error}=await requireClient().from('products').select(productFields).eq('id',id).is('deleted_at',null).single();if(error)throw error;return fromRow(data as Record<string,unknown>)},
 async slugAvailable(slug:string,exceptId?:string){let query=requireClient().from('products').select('id',{count:'exact',head:true}).eq('slug',slug).is('deleted_at',null);if(exceptId)query=query.neq('id',exceptId);const {count,error}=await query;if(error)throw error;return count===0},
 async create(_sellerId:string,draft:ProductDraft){const {data,error}=await requireClient().rpc('create_product_v2',{p_input:draft});if(error)throw error;return String(data)},
 async update(sellerId:string,id:string,patch:Partial<Product>){const record:Record<string,unknown>={};const map:Record<string,string>={name:'name',slug:'slug',description:'description',category:'category',tags:'tags',imageUrl:'image_url',salesPageUrl:'sales_page_url',productType:'product_type',status:'status',billingType:'billing_type',warrantyDays:'warranty_days',supportEmail:'support_email',producerDisplayName:'producer_display_name'};Object.entries(map).forEach(([key,column])=>{if(key in patch)record[column]=patch[key as keyof Product]});if(patch.status==='archived')record.archived_at=new Date().toISOString();else if(patch.status)record.archived_at=null;const {error}=await requireClient().from('products').update(record).eq('id',id).eq('seller_id',sellerId);if(error)throw error;await log(sellerId,id,'product.updated')},
 async setStatus(sellerId:string,id:string,status:ProductStatus){await this.update(sellerId,id,{status})},
 async duplicate(sellerId:string,product:Product){const draft:ProductDraft={name:`${product.name} — cópia`,slug:`${product.slug||'produto'}-copia-${Date.now().toString(36)}`,description:product.description,category:product.category,tags:product.tags,imageUrl:product.imageUrl,salesPageUrl:product.salesPageUrl,productType:product.productType,status:'draft',billingType:product.billingType,offerName:`${product.offer?.name||'Oferta principal'} — cópia`,priceCents:product.offer?.priceCents||product.priceCents,currency:product.currency,billingInterval:product.offer?.billingInterval||null,installments:product.offer?.installments||1,trialDays:product.offer?.trialDays||null,setupFeeCents:product.offer?.setupFeeCents||null,maxCharges:product.offer?.maxCharges||null,accessDurationDays:product.offer?.accessDurationDays||null,warrantyDays:product.warrantyDays,deliveryProvider:'payment_only',deliveryConfig:{}};return this.create(sellerId,draft)},
 async remove(sellerId:string,id:string,sales:number){if(sales>0)return this.setStatus(sellerId,id,'archived');const {error}=await requireClient().from('products').update({deleted_at:new Date().toISOString(),status:'archived',active:false}).eq('id',id).eq('seller_id',sellerId);if(error)throw error;await log(sellerId,id,'product.deleted')},
 async listOffers(productId:string){const {data,error}=await requireClient().from('product_offers').select('*').eq('product_id',productId).is('deleted_at',null).order('is_default',{ascending:false});if(error)throw error;return(data||[]).map(r=>offerFrom(r as Record<string,unknown>))},
 async saveOffer(sellerId:string,productId:string,input:Partial<ProductOffer> & {name:string;priceCents:number;billingType:Product['billingType'];currency:Product['currency']}){const client=requireClient(),record={seller_id:sellerId,product_id:productId,name:input.name,price_cents:input.priceCents,billing_type:input.billingType,currency:input.currency,billing_interval:input.billingInterval,installments:input.installments||1,trial_days:input.trialDays,status:input.status||'draft',is_default:Boolean(input.isDefault),updated_at:new Date().toISOString()};const response=input.id?await client.from('product_offers').update(record).eq('id',input.id).eq('seller_id',sellerId).select('id').single():await client.from('product_offers').insert(record).select('id').single();if(response.error)throw response.error;await log(sellerId,productId,input.id?'offer.updated':'offer.created','offer',String(response.data.id),{priceCents:input.priceCents})},
 async uploadImage(sellerId:string,file:File){if(file.size>5*1024*1024||!['image/jpeg','image/png','image/webp'].includes(file.type))throw new Error('INVALID_IMAGE');const extensions:Record<string,string>={'image/jpeg':'jpg','image/png':'png','image/webp':'webp'},safeExt=extensions[file.type],path=`${sellerId}/${crypto.randomUUID()}.${safeExt}`,client=requireClient(),{error}=await client.storage.from('product-images').upload(path,file,{upsert:false,contentType:file.type});if(error)throw error;return client.storage.from('product-images').getPublicUrl(path).data.publicUrl}
}
