import { BellRing,CheckCircle2,MonitorSmartphone,Pencil,RefreshCcw,Trash2,XCircle } from 'lucide-react'
import { useCallback,useEffect,useState } from 'react'
import { useAuth } from '../../hooks/useAuth'
import { browserPermissionService, type BrowserNotificationStatus } from '../../services/browserPermissionService'
import { pushSubscriptionService,type PushDevice,type PushDiagnostic } from '../../services/pushSubscriptionService'
import { useDemoStore } from '../../store/useDemoStore'
import type { NotificationPreferences } from '../../types'
import { NotificationGeneratorPanel } from '../notifications/NotificationGeneratorPanel'

const statusText:Record<BrowserNotificationStatus,string>={unsupported:'Navegador incompatível',insecure:'Conexão segura necessária',default:'Não autorizadas',granted:'Ativadas',denied:'Permissão bloqueada'}
const indicator=(value:boolean)=>value?<CheckCircle2 className="push-diagnostic-ok"/>:<XCircle className="push-diagnostic-fail"/>
const installed=()=>matchMedia('(display-mode: standalone)').matches||Boolean((navigator as Navigator&{standalone?:boolean}).standalone)

export function NotificationDelivery(){
 const {user}=useAuth(),preferences=useDemoStore(state=>state.preferences.notifications),update=useDemoStore(state=>state.updatePreferences)
 const [status,setStatus]=useState<BrowserNotificationStatus>(()=>browserPermissionService.status()),[subscribed,setSubscribed]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[diagnostics,setDiagnostics]=useState<PushDiagnostic|null>(null),[devices,setDevices]=useState<PushDevice[]>([]),[selectedDeviceId,setSelectedDeviceId]=useState(''),[editingId,setEditingId]=useState(''),[editingName,setEditingName]=useState('')
 const set=(values:Partial<NotificationPreferences>)=>update('notifications',values)
 const refresh=useCallback(async()=>{setStatus(browserPermissionService.status());const [result,registeredDevices]=await Promise.all([pushSubscriptionService.diagnose(),pushSubscriptionService.devices()]);setDiagnostics(result);setDevices(registeredDevices);const enabled=registeredDevices.filter(device=>device.enabled);setSelectedDeviceId(current=>enabled.some(device=>device.deviceId===current)?current:enabled.find(device=>device.isCurrentDevice)?.deviceId||enabled[0]?.deviceId||'');setSubscribed(result.subscription&&result.saved)},[])
 useEffect(()=>{void refresh()},[refresh])
 const activate=async()=>{if(!user){setMessage('SESSION_MISSING: entre novamente para registrar este dispositivo.');return}if(busy)return;setBusy(true);setMessage('Solicitando permissão e registrando dispositivo...');try{const result=await pushSubscriptionService.subscribe();setStatus(browserPermissionService.status());setSubscribed(result.ok);set({device:result.ok,internal:false,sound:false});setMessage(result.message);if(result.device)setSelectedDeviceId(result.device.deviceId);await refresh()}finally{setBusy(false)}}
 const remove=async(device:PushDevice)=>{if(busy)return;setBusy(true);try{const ok=await pushSubscriptionService.removeDevice(device);if(ok){if(device.isCurrentDevice){setSubscribed(false);set({device:false})}setMessage('Dispositivo removido.')}else setMessage('DEVICE_UPDATE_FAILED: não foi possível remover este dispositivo.');await refresh()}finally{setBusy(false)}}
 const rename=async(device:PushDevice)=>{if(busy)return;setBusy(true);try{const ok=await pushSubscriptionService.updateDevice(device.id,{deviceName:editingName});setMessage(ok?'Nome do dispositivo atualizado.':'DEVICE_UPDATE_FAILED: não foi possível renomear.');if(ok)setEditingId('');await refresh()}finally{setBusy(false)}}
 const toggleDevice=async(device:PushDevice)=>{if(busy)return;setBusy(true);try{const ok=await pushSubscriptionService.updateDevice(device.id,{enabled:!device.enabled});setMessage(ok?'Status do dispositivo atualizado.':'DEVICE_UPDATE_FAILED: não foi possível atualizar.');await refresh()}finally{setBusy(false)}}
 const testDevice=async(deviceId:string)=>{if(busy)return;setBusy(true);setMessage('Enviando teste ao dispositivo...');try{const result=await pushSubscriptionService.sendTest(deviceId);setMessage(`${result.code&&!result.ok?`${result.code}: `:''}${result.message}`);await refresh()}finally{setBusy(false)}}
 const test=()=>testDevice(selectedDeviceId)
 const permission=status==='granted'?'Ativada':statusText[status],connectionState=!diagnostics?'Verificando':diagnostics.permission==='granted'&&diagnostics.subscription&&diagnostics.saved&&diagnostics.serviceWorkerActive&&diagnostics.vapidConfigured&&diagnostics.backendConfigured&&diagnostics.storageConfigured?'Dispositivo conectado':diagnostics.permission==='denied'?'Bloqueado':diagnostics.subscription&&!diagnostics.saved?'Reativação necessária':'Pronto para ativar'
 return <><div className="notification-delivery device-only-settings">
  <section>
   <h3>Dispositivo atual</h3>
   <div className="device-permission"><div className={`permission-dot ${subscribed?'granted':status}`}/><MonitorSmartphone/><div><span className="label">Status da conexão</span><b>{connectionState}</b><small>{pushSubscriptionService.deviceLabel()} · {permission}</small></div></div>
   {devices.some(device=>device.enabled)&&<label className="mt-4 block"><span className="label">Dispositivo para teste</span><select className="input" value={selectedDeviceId} onChange={event=>setSelectedDeviceId(event.target.value)}>{devices.filter(device=>device.enabled).map(device=><option value={device.deviceId} key={device.id}>{device.name} · {device.browser} no {device.operatingSystem}</option>)}</select></label>}
   <div className="flex flex-wrap gap-2 mt-5"><button className="btn btn-primary" onClick={()=>void activate()} disabled={busy||status==='unsupported'||status==='insecure'||status==='denied'}>{busy?'Processando...':subscribed?'Revalidar dispositivo':'Ativar notificações neste dispositivo'}</button><button className="btn" onClick={()=>void test()} disabled={busy||!selectedDeviceId||status!=='granted'}><BellRing/> Testar no meu dispositivo</button><button className="btn btn-ghost" onClick={()=>void refresh()} disabled={busy}><RefreshCcw/> Atualizar diagnóstico</button></div>
   {message&&<p className="text-xs muted mt-3" role="status">{message}</p>}
   <section className="push-diagnostics"><h4>Diagnóstico do dispositivo</h4><Diagnostic label="HTTPS ativo" value={diagnostics?.https??(window.isSecureContext||location.hostname==='localhost')}/><Diagnostic label="Sessão autenticada" value={diagnostics?.sessionAuthenticated??false}/><Diagnostic label="device_id criado" value={diagnostics?.deviceIdentityCreated??false}/><Diagnostic label="PushSubscription existente" value={diagnostics?.subscription??subscribed}/><Diagnostic label="Registro confirmado no servidor" value={diagnostics?.databaseConfirmed??false}/><Diagnostic label="Dispositivo atual encontrado" value={diagnostics?.currentDeviceFound??false}/><Diagnostic label="Dispositivos ativos" value={(diagnostics?.activeDevices??0)>0} text={String(diagnostics?.activeDevices??0)}/><Diagnostic label="Chave pública válida" value={diagnostics?.vapidValid??false}/><Diagnostic label="Service Worker pronto" value={diagnostics?.serviceWorkerReady??false}/><Diagnostic label="Backend Push disponível" value={diagnostics?.backendConfigured??false}/><span>Último status HTTP: {diagnostics?.lastHttpStatus??'—'}</span><span>Último código seguro: {diagnostics?.lastErrorCode||'—'}</span><span>Última entrega: {diagnostics?.lastDelivery||'—'}</span></section>
   {status==='denied'&&<p className="text-[11px] muted mt-4">As notificações estão bloqueadas no navegador ou nas configurações do sistema.</p>}{/iPhone|iPad|iPod/.test(navigator.userAgent)&&!installed()&&<p className="text-[11px] muted mt-4">Adicione a SphexPay à Tela de Início e abra pelo ícone para ativar notificações.</p>}
  </section>
  <section><div className="flex items-center justify-between gap-3"><h3>Meus dispositivos</h3><button className="btn btn-ghost" onClick={()=>void refresh()} disabled={busy}><RefreshCcw/> Atualizar status</button></div><div className="grid gap-3 mt-4">{devices.map(device=><article className="generator-section" key={device.id}><div className="generator-section-body"><div className="flex items-start justify-between gap-3"><div><b>{device.name}</b><p className="muted text-xs">{device.browser} no {device.operatingSystem}</p>{device.isCurrentDevice&&<span className="label">Este dispositivo</span>}<p className="text-xs mt-2">{device.status} · Último acesso: {new Date(device.lastSeenAt).toLocaleString('pt-BR')}</p></div><span className={`permission-dot ${device.enabled?'granted':'denied'}`}/></div>{editingId===device.id?<div className="flex gap-2 mt-3"><input className="input" value={editingName} maxLength={120} onChange={event=>setEditingName(event.target.value)}/><button className="btn btn-primary" onClick={()=>void rename(device)} disabled={busy||editingName.trim().length<2}>Salvar</button><button className="btn" onClick={()=>setEditingId('')}>Cancelar</button></div>:<div className="flex flex-wrap gap-2 mt-3"><button className="btn" onClick={()=>{setEditingId(device.id);setEditingName(device.name)}}><Pencil/> Renomear</button><button className="btn" onClick={()=>void testDevice(device.deviceId)} disabled={!device.enabled||busy}><BellRing/> Testar</button><button className="btn" onClick={()=>void toggleDevice(device)}>{device.enabled?'Desativar':'Ativar'}</button><button className="btn text-red-500" onClick={()=>void remove(device)}><Trash2/> Remover</button></div>}</div></article>)}</div></section>
  <section><h3>Eventos enviados ao dispositivo</h3><Toggle label="Notificações de vendas" checked={preferences.sales} onChange={sales=>set({sales})}/><Toggle label="Notificações de Pix" checked={preferences.pixGenerated!==false} onChange={pixGenerated=>set({pixGenerated})}/><Toggle label="Notificações de cartão" checked={preferences.cardApproved!==false} onChange={cardApproved=>set({cardApproved})}/><Toggle label="Notificações de boleto" checked={preferences.boletoEvents!==false} onChange={boletoEvents=>set({boletoEvents})}/><Toggle label="Notificações de assinaturas" checked={preferences.subscriptionEvents!==false} onChange={subscriptionEvents=>set({subscriptionEvents})}/><Toggle label="Notificações de saques" checked={preferences.withdrawalEvents!==false} onChange={withdrawalEvents=>set({withdrawalEvents})}/></section>
  <section><h3>Entrega nativa</h3><div className="generator-fixed-destination"><BellRing/><span><b>Notificação do sistema</b><small>Som e alertas controlados pelo dispositivo</small></span></div><p className="text-xs muted mt-4">Eventos comerciais aparecem somente nas notificações do sistema operacional.</p></section>
 </div><NotificationGeneratorPanel/></>
}
function Diagnostic({label,value,text}:{label:string;value:boolean;text?:string}){return <span className="push-diagnostic-row">{indicator(value)}<span>{label}</span><b>{text|| (value?'Disponível':'Não disponível')}</b></span>}
function Toggle({label,checked,onChange}:{label:string;checked:boolean;onChange:(value:boolean)=>void}){return <label className="setting-toggle"><span>{label}</span><input type="checkbox" checked={checked} onChange={event=>onChange(event.target.checked)}/><i/></label>}
